// Generated by scripts/normalize-luxury-art.cjs; immutable catalogue IDs.
import type { ImageSourcePropType } from 'react-native';

export const LUXURY_ART: Record<string, ImageSourcePropType> = {
  'rare_watch_collection': require('@/assets/images/luxury-v2/rare_watch_collection.webp'),
  'museum_diamond': require('@/assets/images/luxury-v2/museum_diamond.webp'),
  'fine_art_collection': require('@/assets/images/luxury-v2/fine_art_collection.webp'),
  'supercar': require('@/assets/images/luxury-v2/supercar.webp'),
  'racehorse': require('@/assets/images/luxury-v2/racehorse.webp'),
  'vineyard_estate': require('@/assets/images/luxury-v2/vineyard_estate.webp'),
  'luxury_yacht': require('@/assets/images/luxury-v2/luxury_yacht.webp'),
  'private_jet': require('@/assets/images/luxury-v2/private_jet.webp'),
  'private_island': require('@/assets/images/luxury-v2/private_island.webp'),
  'trophy_penthouse': require('@/assets/images/luxury-v2/trophy_penthouse.webp'),
  'mega_yacht': require('@/assets/images/luxury-v2/mega_yacht.webp'),
  'sports_team_stake': require('@/assets/images/luxury-v2/sports_team_stake.webp'),
};
