/**
 * Styles for the Work screen (app/(tabs)/work.tsx).
 *
 * Extracted verbatim from the route file to keep the screen logic readable
 * (the file was ~4,600 lines, ~73% of it this stylesheet). This is a static
 * module-level StyleSheet with no component-scope dependencies.
 */
import { Platform, StyleSheet } from 'react-native';
import {
  scale,
  fontScale,
  responsiveSpacing,
  responsiveFontSize,
  responsiveBorderRadius,
} from '@/utils/scaling';
import { getResponsiveValue } from '@/utils/responsiveDesign';

export const styles = StyleSheet.create({
    background: {
        flex: 1,
        backgroundColor: '#0F172A',
    },
    backgroundDark: {
        backgroundColor: '#0F172A',
    },
    container: {
        flex: 1,
    },
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: 'rgba(15, 23, 42, 0.6)',
        margin: responsiveSpacing.lg,
        borderRadius: responsiveBorderRadius.lg,
        padding: responsiveSpacing.xs,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        overflow: 'hidden',
    },
    tabContainerDark: {
        backgroundColor: 'rgba(15, 23, 42, 0.6)',
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    tab: {
        flex: 1,
        paddingVertical: responsiveSpacing.sm,
        alignItems: 'center',
        borderRadius: responsiveBorderRadius.md,
        backgroundColor: 'transparent',
    },
    activeTab: {
        backgroundColor: '#3B82F6',
        ...Platform.select({
          web: { boxShadow: '0px 2px 4px rgba(59, 130, 246, 0.2)' } as any,
          default: {
            shadowColor: '#3B82F6',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 4,
          },
        }),
        elevation: 3,
    },
    tabText: {
        fontSize: responsiveFontSize.sm,
        fontWeight: '600',
        color: '#64748B',
        letterSpacing: 0.3,
    },
    activeTabText: {
        color: '#FFFFFF',
        fontWeight: '700',
    },
    tabTextDark: {
        color: '#D1D5DB',
        fontWeight: '500',
    },
    content: {
        flex: 1,
        paddingHorizontal: responsiveSpacing.lg,
        paddingTop: responsiveSpacing.sm,
        paddingBottom: responsiveSpacing.lg,
    },
    sectionDescription: {
        fontSize: responsiveFontSize.base,
        color: '#64748B',
        marginBottom: responsiveSpacing.xl,
        lineHeight: 24,
        fontWeight: '500',
    },
    sectionDescriptionDark: {
        color: '#D1D5DB',
        fontWeight: '400',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
        marginTop: 4,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1F2937',
    },
    sectionTitleDark: {
        color: '#F9FAFB',
    },
    subheader: {
        fontSize: 18,
        fontWeight: '600',
        marginTop: 8,
        marginBottom: 8,
        color: '#1F2937',
    },
    subheaderDark: {
        color: '#F3F4F6',
    },
    comingSoonText: {
        fontSize: 16,
        color: '#6B7280',
        marginBottom: 10,
    },
    comingSoonTextDark: {
        color: '#D1D5DB',
    },
    lockedCareerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: 'rgba(107, 114, 128, 0.15)',
        borderRadius: 12,
        marginBottom: 12,
        gap: 12,
        borderWidth: 1,
        borderColor: 'rgba(107, 114, 128, 0.3)',
    },
    lockedCareerText: {
        flex: 1,
        fontSize: fontScale(14),
        color: '#6B7280',
        lineHeight: fontScale(20),
    },
    lockedCareerTextDark: {
        color: '#9CA3AF',
    },
    careerCard: {
        padding: responsiveSpacing.lg,
        backgroundColor: '#FFFFFF',
        borderRadius: responsiveBorderRadius.xl,
        marginBottom: responsiveSpacing.md,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.06)',
        // Beautiful light mode shadows
        ...Platform.select({
          web: { boxShadow: '0px 3px 8px rgba(0, 0, 0, 0.06)' } as any,
          default: {
            shadowColor: 'rgba(0,0,0,0.06)',
            shadowOffset: { width: 0, height: 3 },
            shadowOpacity: 1,
            shadowRadius: 8,
          },
        }),
        elevation: 3,
    },
    careerCardDark: {
        backgroundColor: '#1F2937',
        borderColor: '#374151',
        ...Platform.select({
          web: { boxShadow: '0px 1px 3px rgba(0, 0, 0, 0.25)' } as any,
          default: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.25,
            shadowRadius: 3,
          },
        }),
        elevation: 1,
    },
    careerCardActive: {
        borderColor: '#22C55E',
        borderWidth: 2,
        ...Platform.select({
          web: { boxShadow: '0px 4px 12px rgba(34, 197, 94, 0.2)' } as any,
          default: {
            shadowColor: 'rgba(34, 197, 94, 0.2)',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 1,
            shadowRadius: 12,
          },
        }),
        elevation: 4,
    },
    careerCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: scale(8),
    },
    careerName: {
        fontSize: responsiveFontSize.xl,
        fontWeight: '800',
        color: '#0F172A',
        marginBottom: responsiveSpacing.xs,
        letterSpacing: -0.5,
        // Light mode: subtle text shadow for emphasis
        ...Platform.select({
          web: { textShadow: '0px 1px 2px rgba(0,0,0,0.1)' } as any,
          default: {
            textShadowColor: 'rgba(0,0,0,0.1)',
            textShadowOffset: { width: 0, height: 1 },
            textShadowRadius: 2,
          },
        }),
    },
    careerNameDark: {
        color: '#F9FAFB',
        textShadowColor: 'transparent',
        fontWeight: '700',
    },
    careerDescription: {
        fontSize: responsiveFontSize.sm,
        color: '#64748B',
        lineHeight: responsiveFontSize.lg,
        fontWeight: '500',
    },
    careerDescriptionDark: {
        color: '#9CA3AF',
        fontWeight: '400',
    },
    careerSalary: {
        fontSize: fontScale(16),
        fontWeight: '600',
        color: '#22C55E',
    },
    careerSalaryDark: {
        color: '#4ADE80',
    },
    jobCard: {
        padding: getResponsiveValue(12, 16, 20, 24),
        borderRadius: getResponsiveValue(8, 12, 16, 20),
        marginBottom: getResponsiveValue(12, 16, 20, 24),
        boxShadow: '0px 2px 3px rgba(0, 0, 0, 0.1)',
        ...Platform.select({
          web: { boxShadow: '0px 2px 3px rgba(0, 0, 0, 0.1)' } as any,
          default: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 3,
          },
        }),
        elevation: 2,
    },
    // Street job styles (blue theme) - Compressed
    streetJobContainer: {
        marginBottom: 12,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        ...Platform.select({
          web: { boxShadow: '0px 1px 3px rgba(37, 99, 235, 0.3)' } as any,
          default: {
            shadowColor: '#2563EB',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.3,
            shadowRadius: 3,
          },
        }),
        elevation: 3,
    },
    streetJobGlass: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: 12,
    },
    streetJobHeader: {
        padding: 10,
        borderRadius: 12,
    },
    streetJobHeaderContent: {
        gap: 4,
    },
    streetJobTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    streetJobTitleContainer: {
        flex: 1,
        gap: 2,
    },
    streetJobName: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    streetJobBadge: {
        backgroundColor: '#2563EB',
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 3,
        alignSelf: 'flex-start',
    },
    streetJobBadgeText: {
        fontSize: 8,
        fontWeight: '700',
        color: '#FFFFFF',
        letterSpacing: 0.5,
    },
    streetJobRankContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        backgroundColor: 'rgba(37, 99, 235, 0.2)',
        paddingHorizontal: 4,
        paddingVertical: 2,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#2563EB',
    },
    streetJobRank: {
        fontSize: 10,
        fontWeight: '600',
        color: '#60A5FA',
    },
    streetJobDescription: {
        fontSize: 10,
        color: '#B0B0B0',
        lineHeight: 14,
        fontWeight: '400',
    },
    streetJobStatsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        backgroundColor: 'rgba(59, 130, 246, 0.05)',
        padding: 6,
        gap: 3,
    },
    streetStatCard: {
        flex: 1,
        minWidth: '30%',
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        borderRadius: 4,
        padding: 4,
        alignItems: 'center',
        borderWidth: 0.5,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    streetStatCardDark: {
        backgroundColor: 'rgba(59, 130, 246, 0.15)',
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    streetStatIcon: {
        width: 16,
        height: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 1,
    },
    streetStatLabel: {
        fontSize: 9,
        color: '#9CA3AF',
        fontWeight: '600',
        marginBottom: 1,
    },
    streetStatValue: {
        fontSize: 11,
        color: '#FFFFFF',
        fontWeight: '700',
    },
    streetJobActionContainer: {
        backgroundColor: '#0A1628',
        padding: 8,
        alignItems: 'center',
    },
    streetJobButtonWrapper: {
        width: '100%',
    },
    streetJobButton: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 6,
        alignItems: 'center',
        boxShadow: '0px 2px 4px rgba(37, 99, 235, 0.4)',
        ...Platform.select({
          web: { boxShadow: '0px 2px 4px rgba(37, 99, 235, 0.4)' } as any,
          default: {
            shadowColor: '#2563EB',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.4,
            shadowRadius: 4,
          },
        }),
        elevation: 4,
    },
    streetJobButtonText: {
        fontSize: 13,
        fontWeight: '900',
        color: '#FFFFFF',
        letterSpacing: 1,
    },
    streetJobButtonTextDisabled: {
        opacity: 0.5,
    },
    // Career job styles (green theme) - Compressed
    careerJobContainer: {
        marginBottom: 10,
        borderRadius: 10,
        overflow: 'hidden',
        backgroundColor: 'transparent',
        borderWidth: 0.5,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        ...Platform.select({
          web: { boxShadow: '0px 1px 3px rgba(16, 185, 129, 0.075)' } as any,
          default: {
            shadowColor: 'rgba(16, 185, 129, 0.15)',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.5,
            shadowRadius: 3,
          },
        }),
        elevation: 2,
    },
    careerGlass: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: 12,
    },
    careerJobHeader: {
        padding: 10,
    },
    careerJobHeaderContent: {
        gap: 4,
    },
    careerJobTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    careerJobTitleContainer: {
        flex: 1,
        gap: 2,
    },
    careerJobName: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    careerJobBadge: {
        backgroundColor: '#059669',
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 3,
        alignSelf: 'flex-start',
    },
    careerJobBadgeText: {
        fontSize: 8,
        fontWeight: '700',
        color: '#FFFFFF',
        letterSpacing: 0.5,
    },
    careerJobSalaryContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#10B981',
    },
    lockedSalaryBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: 'rgba(245, 158, 11, 0.15)',
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#F59E0B',
    },
    lockedSalaryText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#F59E0B',
    },
    careerJobSalaryLabel: {
        fontSize: 10,
        color: '#A7F3D0',
        fontWeight: '600',
    },
    careerJobSalary: {
        fontSize: 12,
        fontWeight: '800',
        color: '#34D399',
    },
    careerJobDescription: {
        fontSize: 10,
        color: '#D1FAE5',
        lineHeight: 14,
        fontWeight: '400',
    },
    careerJobStatsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        backgroundColor: 'rgba(4, 120, 87, 0.08)',
        padding: 6,
        gap: 3,
    },
    careerStatCard: {
        flex: 1,
        minWidth: '30%',
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        borderRadius: 4,
        padding: 4,
        alignItems: 'center',
        borderWidth: 0.5,
        borderColor: 'rgba(255, 255, 255, 0.25)',
    },
    careerStatIcon: {
        width: 16,
        height: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 1,
    },
    careerStatLabel: {
        fontSize: 9,
        color: '#CFFAFE',
        fontWeight: '600',
        marginBottom: 1,
    },
    careerStatValue: {
        fontSize: 11,
        color: '#FFFFFF',
        fontWeight: '700',
    },
    careerJobActionContainer: {
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        padding: 12,
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: 'rgba(16, 185, 129, 0.2)',
    },
    careerButtonWrapper: {
        position: 'relative',
        borderRadius: 8,
        overflow: 'hidden',
    },
    careerButtonBlur: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    careerJobButton: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 6,
        alignItems: 'center',
        backgroundColor: 'transparent',
    },
    careerQuitButton: {
        backgroundColor: '#EF4444',
    },
    careerJobButtonDisabled: {
        backgroundColor: '#6EE7B7',
        opacity: 0.6,
    },
    careerJobButtonText: {
        fontSize: 13,
        fontWeight: '900',
        color: '#FFFFFF',
        letterSpacing: 1,
    },
    careerJobButtonTextDisabled: {
        opacity: 0.6,
    },
    careerJobButtonQuit: {
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.8)',
    },
    // Requirement chips (shared)
    crimeReqChipsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
        marginTop: 6,
    },
    reqChip: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 999,
        borderWidth: 1,
    },
    reqChipOwned: {
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        borderColor: '#10B981',
    },
    reqChipMissing: {
        backgroundColor: 'rgba(239, 68, 68, 0.15)',
        borderColor: '#EF4444',
    },
    reqChipText: {
        fontSize: 10,
        fontWeight: '700',
    },
    reqChipTextOwned: {
        color: '#10B981',
    },
    reqChipTextMissing: {
        color: '#EF4444',
    },
    // Crime styles - Compressed
    crimeJobContainer: {
        marginBottom: 10,
        borderRadius: 10,
        overflow: 'hidden',
        backgroundColor: 'transparent',
        borderWidth: 0.5,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        ...Platform.select({
          web: { boxShadow: '0px 1px 3px rgba(220, 38, 38, 0.075)' } as any,
          default: {
            shadowColor: 'rgba(220, 38, 38, 0.15)',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.5,
            shadowRadius: 3,
          },
        }),
        elevation: 2,
    },
    crimeJobGlass: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: 12,
    },
    crimeJobHeader: {
        padding: 10,
        borderRadius: 12,
    },
    crimeJobHeaderContent: {
        gap: 4,
    },
    crimeJobTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    crimeJobTitleContainer: {
        flex: 1,
        gap: 2,
    },
    crimeJobName: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    crimeJobBadge: {
        backgroundColor: '#DC2626',
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 3,
        alignSelf: 'flex-start',
    },
    crimeJobBadgeText: {
        fontSize: 8,
        fontWeight: '700',
        color: '#FFFFFF',
        letterSpacing: 0.5,
    },
    crimeJobRankContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        backgroundColor: 'rgba(220, 38, 38, 0.2)',
        paddingHorizontal: 4,
        paddingVertical: 2,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#DC2626',
    },
    crimeJobRank: {
        fontSize: 10,
        fontWeight: '600',
        color: '#FF6B6B',
    },
    crimeJobDescription: {
        fontSize: 10,
        color: '#B0B0B0',
        lineHeight: 14,
        fontWeight: '400',
    },
    crimeJobStatsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        backgroundColor: 'rgba(220, 38, 38, 0.05)',
        padding: 6,
        gap: 3,
    },
    crimeStatCard: {
        flex: 1,
        minWidth: '30%',
        backgroundColor: 'rgba(220, 38, 38, 0.1)',
        borderRadius: 4,
        padding: 4,
        alignItems: 'center',
        borderWidth: 0.5,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    crimeStatIcon: {
        width: 16,
        height: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 1,
    },
    crimeStatLabel: {
        fontSize: 9,
        color: '#888888',
        fontWeight: '600',
        marginBottom: 1,
    },
    crimeStatValue: {
        fontSize: 11,
        color: '#FFFFFF',
        fontWeight: '700',
    },
    crimeStatValueDisabled: {
        opacity: 0.3,
    },
    crimeJobActionContainer: {
        backgroundColor: 'rgba(220, 38, 38, 0.05)',
        padding: 6,
        alignItems: 'center',
        borderTopWidth: 0.5,
        borderTopColor: 'rgba(220, 38, 38, 0.15)',
    },
    crimeJobButtonWrapper: {
        width: '100%',
    },
    crimeJobButton: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 6,
        alignItems: 'center',
        boxShadow: '0px 2px 4px rgba(220, 38, 38, 0.4)',
        ...Platform.select({
          web: { boxShadow: '0px 2px 4px rgba(220, 38, 38, 0.4)' } as any,
          default: {
            shadowColor: '#DC2626',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.4,
            shadowRadius: 4,
          },
        }),
        elevation: 4,
    },
    crimeJobButtonText: {
        fontSize: 13,
        fontWeight: '900',
        color: '#FFFFFF',
        letterSpacing: 1,
    },
    crimeJobButtonTextDisabled: {
        opacity: 0.5,
    },
    jailBox: {
        alignItems: 'center',
        padding: 20,
    },
    bailButtonWrapper: {
        marginTop: 12,
    },
    jobHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: responsiveSpacing.sm,
    },
    jobInfo: {
        flex: 1,
    },
    jobName: {
        fontSize: getResponsiveValue(14, 16, 18, 20),
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: getResponsiveValue(4, 6, 8, 10),
    },
    jobNameDark: {
        color: '#F9FAFB',
    },
    rankBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FEF3C7',
        paddingHorizontal: responsiveSpacing.sm,
        paddingVertical: scale(2),
        borderRadius: responsiveBorderRadius.md,
        alignSelf: 'flex-start',
    },
    rankText: {
        fontSize: responsiveFontSize.sm,
        color: '#92400E',
        marginLeft: responsiveSpacing.xs,
        fontWeight: '500',
    },
    salary: {
        fontSize: responsiveFontSize.lg,
        fontWeight: '600',
        color: '#10B981',
    },
    salaryHidden: {
        fontSize: responsiveFontSize.sm,
        color: '#6B7280',
        marginLeft: scale(6),
    },
    salaryHiddenDark: {
        color: '#E5E7EB',
    },
    workButton: {
        backgroundColor: '#3B82F6',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 6,
    },
    actionButton: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 6,
    },
    teamSelectContainer: {
        flexDirection: 'row',
        gap: 8,
    },
    workButtonContainer: {
        alignItems: 'flex-end',
        minWidth: 80,
        position: 'relative',
    },
    feedbackPopup: {
        position: 'absolute',
        right: 0,
        bottom: '100%',
        marginBottom: 8,
        backgroundColor: '#3B82F6',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
        zIndex: 1,
    },
    feedbackPopupText: {
        color: '#FFFFFF',
        fontSize: 10,
    },
    appliedButton: {
        backgroundColor: '#F59E0B',
    },
    acceptedButton: {
        backgroundColor: '#10B981',
    },
    quitButton: {
        backgroundColor: '#EF4444',
    },
    disabledButton: {
        backgroundColor: '#E5E7EB',
    },
    workButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    appliedButtonText: {
        color: '#FFFFFF',
    },
    acceptedButtonText: {
        color: '#FFFFFF',
    },
    quitButtonText: {
        color: '#FFFFFF',
    },
    disabledButtonText: {
        color: '#9CA3AF',
    },
    jobDescription: {
        fontSize: responsiveFontSize.sm,
        color: '#6B7280',
        marginBottom: responsiveSpacing.sm,
        lineHeight: 16,
    },
    jobDescriptionDark: {
        color: '#D1D5DB',
    },
    perks: {
        marginBottom: 15,
    },
    perk: {
        fontSize: 13,
        color: '#1F2937',
        marginBottom: 2,
    },
    perkDark: {
        color: '#F3F4F6',
    },
    jobStats: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: responsiveSpacing.sm,
        gap: getResponsiveValue(8, 10, 12, 14),
    },
    statItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 20,
    },
    statText: {
        fontSize: 14,
        color: '#374151',
        marginLeft: 4,
    },
    statTextDark: {
        color: '#D1D5DB',
    },
    negativeStatsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: getResponsiveValue(8, 10, 12, 14),
        paddingVertical: getResponsiveValue(8, 10, 12, 14),
        paddingHorizontal: getResponsiveValue(12, 14, 16, 18),
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        borderRadius: getResponsiveValue(8, 10, 12, 14),
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        alignSelf: 'flex-start',
    },
    negativeStatsButtonCircle: {
        width: getResponsiveValue(32, 36, 40, 44),
        height: getResponsiveValue(32, 36, 40, 44),
        borderRadius: getResponsiveValue(16, 18, 20, 22),
        backgroundColor: 'rgba(239, 68, 68, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: getResponsiveValue(8, 10, 12, 14),
    },
    negativeStatsButtonText: {
        fontSize: getResponsiveValue(12, 14, 16, 18),
        fontWeight: '600',
        color: '#EF4444',
    },
    negativeStatsButtonTextDark: {
        color: '#F87171',
    },
    negativeStatsModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    negativeStatsModalContainer: {
        width: '90%',
        maxWidth: 500,
        borderRadius: getResponsiveValue(16, 20, 24, 28),
        overflow: 'hidden',
    },
    negativeStatsModalContent: {
        padding: getResponsiveValue(20, 24, 28, 32),
    },
    negativeStatsModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: getResponsiveValue(20, 24, 28, 32),
    },
    negativeStatsModalIconContainer: {
        width: getResponsiveValue(48, 56, 64, 72),
        height: getResponsiveValue(48, 56, 64, 72),
        borderRadius: getResponsiveValue(24, 28, 32, 36),
        backgroundColor: 'rgba(239, 68, 68, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: getResponsiveValue(12, 14, 16, 18),
    },
    negativeStatsModalTitleContainer: {
        flex: 1,
    },
    negativeStatsModalTitle: {
        fontSize: getResponsiveValue(20, 24, 28, 32),
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: getResponsiveValue(4, 6, 8, 10),
    },
    negativeStatsModalTitleDark: {
        color: '#F9FAFB',
    },
    negativeStatsModalSubtitle: {
        fontSize: getResponsiveValue(14, 16, 18, 20),
        fontWeight: '500',
        color: '#6B7280',
    },
    negativeStatsModalSubtitleDark: {
        color: '#9CA3AF',
    },
    negativeStatsModalCloseButton: {
        width: getResponsiveValue(32, 36, 40, 44),
        height: getResponsiveValue(32, 36, 40, 44),
        borderRadius: getResponsiveValue(16, 18, 20, 22),
        backgroundColor: 'rgba(0, 0, 0, 0.05)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    negativeStatsModalBody: {
        marginBottom: getResponsiveValue(20, 24, 28, 32),
    },
    negativeStatsModalDescription: {
        fontSize: getResponsiveValue(14, 16, 18, 20),
        color: '#6B7280',
        marginBottom: getResponsiveValue(16, 20, 24, 28),
        lineHeight: getResponsiveValue(20, 24, 28, 32),
    },
    negativeStatsModalDescriptionDark: {
        color: '#9CA3AF',
    },
    negativeStatsList: {
        gap: getResponsiveValue(12, 14, 16, 18),
    },
    negativeStatItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: getResponsiveValue(12, 14, 16, 18),
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        borderRadius: getResponsiveValue(8, 10, 12, 14),
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    negativeStatIconContainer: {
        width: getResponsiveValue(36, 40, 44, 48),
        height: getResponsiveValue(36, 40, 44, 48),
        borderRadius: getResponsiveValue(18, 20, 22, 24),
        backgroundColor: 'rgba(239, 68, 68, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: getResponsiveValue(12, 14, 16, 18),
    },
    negativeStatInfo: {
        flex: 1,
    },
    negativeStatLabel: {
        fontSize: getResponsiveValue(14, 16, 18, 20),
        fontWeight: '600',
        color: '#374151',
        marginBottom: getResponsiveValue(4, 6, 8, 10),
    },
    negativeStatLabelDark: {
        color: '#D1D5DB',
    },
    negativeStatValue: {
        fontSize: getResponsiveValue(16, 18, 20, 22),
        fontWeight: '700',
        color: '#EF4444',
    },
    negativeStatsWarningBox: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: getResponsiveValue(12, 14, 16, 18),
        backgroundColor: 'rgba(245, 158, 11, 0.1)',
        borderRadius: getResponsiveValue(8, 10, 12, 14),
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        marginTop: getResponsiveValue(12, 14, 16, 18),
        gap: getResponsiveValue(8, 10, 12, 14),
    },
    negativeStatsWarningText: {
        flex: 1,
        fontSize: getResponsiveValue(14, 16, 18, 20),
        fontWeight: '600',
        color: '#92400E',
    },
    negativeStatsWarningTextDark: {
        color: '#FCD34D',
    },
    negativeStatsModalCloseButtonBottom: {
        marginTop: getResponsiveValue(8, 10, 12, 14),
    },
    negativeStatsModalCloseButtonGradient: {
        paddingVertical: getResponsiveValue(14, 16, 18, 20),
        paddingHorizontal: getResponsiveValue(24, 28, 32, 36),
        borderRadius: getResponsiveValue(10, 12, 14, 16),
        alignItems: 'center',
    },
    negativeStatsModalCloseButtonText: {
        fontSize: getResponsiveValue(16, 18, 20, 22),
        fontWeight: '700',
        color: '#FFFFFF',
    },
    requirements: {
        marginBottom: responsiveSpacing.sm,
    },
    requirementsTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 5,
    },
    requirementsTitleDark: {
        color: '#D1D5DB',
    },
    requirement: {
        fontSize: 12,
        color: '#EF4444',
        marginBottom: 2,
    },
    metRequirement: {
        color: '#10B981',
    },
    requirementDark: {
        color: '#F87171',
    },
    lockedSalaryRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    lockedHint: {
        marginTop: 6,
        color: '#6B7280',
        fontSize: 12,
    },
    lockedHintDark: {
        color: '#E5E7EB',
    },
    listButton: {
        backgroundColor: '#E0E7FF',
        padding: 6,
        borderRadius: 12,
        marginLeft: 8,
    },
    listButtonDark: {
        backgroundColor: '#1E40AF',
    },
    iconRow: {
        flexDirection: 'row',
    },
    lockedText: {
        color: '#EF4444',
        textAlign: 'center',
        marginBottom: 8,
    },
    lockedCard: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FEE2E2',
        borderColor: '#EF4444',
        borderWidth: 2,
    },
    lockedCardDark: {
        backgroundColor: '#7F1D1D',
        borderColor: '#F87171',
    },
    contractPaper: {
        backgroundColor: '#FEFCE8',
        padding: 20,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#DDD6FE',
    },
    contractTitle: {
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 12,
        fontStyle: 'italic',
        color: '#1F2937',
    },
    contractLine: {
        fontSize: 14,
        marginBottom: 6,
        fontStyle: 'italic',
        color: '#374151',
    },
    signButton: {
        backgroundColor: '#10B981',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 6,
        marginTop: 10,
    },
    signButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    offerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    divisionTabs: {
        flexDirection: 'row',
        marginBottom: 10,
    },
    divisionTab: {
        paddingVertical: 4,
        paddingHorizontal: 8,
        marginRight: 6,
        borderRadius: 4,
        backgroundColor: '#E5E7EB',
    },
    activeDivisionTab: {
        backgroundColor: '#3B82F6',
    },
    divisionTabText: {
        fontSize: 12,
        color: '#1F2937',
    },
    activeDivisionTabText: {
        color: '#F9FAFB',
    },
    highlightedTeam: {
        color: '#3B82F6',
        fontWeight: '700',
    },
    upgradesSection: {
        marginTop: 12,
    },
    upgradeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
        backgroundColor: 'rgba(107, 114, 128, 0.15)',
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(107, 114, 128, 0.3)',
    },
    upgradeRowDark: {
        backgroundColor: '#1F2937',
    },
    upgradeInfo: {
        flex: 1,
        paddingRight: 8,
    },
    upgradeName: {
        color: '#1F2937',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'System',
    },
    upgradeNameDark: {
        color: '#F9FAFB',
    },
    upgradeDesc: {
        color: '#4B5563',
        fontSize: 14,
        fontFamily: 'System',
    },
    upgradeDescDark: {
        color: '#D1D5DB',
    },
    upgradeButton: {
        backgroundColor: '#6366F1',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.15)',
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 2,
    },
    upgradeButtonText: {
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 16,
        fontFamily: 'System',
    },
    progressContainer: {
        marginTop: scale(4),
    },
    progressBarBg: {
        height: scale(4),
        backgroundColor: '#E5E7EB',
        borderRadius: scale(2),
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#3B82F6',
        borderRadius: scale(2),
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        width: '85%',
        maxHeight: '80%',
    },
    modalContentDark: {
        backgroundColor: '#1F2937',
    },
    modalList: {
        maxHeight: 200,
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 12,
        color: '#111827',
    },
    modalTitleDark: {
        color: '#F9FAFB',
    },
    modalItem: {
        fontSize: 14,
        color: '#374151',
        marginBottom: 4,
    },
    modalItemDark: {
        color: '#D1D5DB',
    },
    modalCloseButton: {
        marginTop: 12,
        alignSelf: 'center',
        backgroundColor: '#3B82F6',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    modalCloseText: {
        color: '#FFFFFF',
        fontWeight: '600',
        marginLeft: 4,
    },
    modalCloseIcon: {
        position: 'absolute',
        top: 10,
        right: 10,
        zIndex: 1,
    },
    skillScroll: {
        maxHeight: '70%',
        marginTop: 10,
    },
    skillTreeSection: {
        marginBottom: 16,
    },
    skillTreeSkill: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 8,
        color: '#1F2937',
    },
    skillTreeSkillDark: {
        color: '#F3F4F6',
    },
    skillUpgradeButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 6,
    },
    skillUpgradeText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    skillLevelTop: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: responsiveSpacing.xs,
    },
    skillLevelLabel: {
        fontWeight: '600',
        marginBottom: 4,
        color: '#1F2937',
    },
    skillLevelLabelDark: {
        color: '#F3F4F6',
    },
    skillLevelConnector: {
        width: 2,
        height: 20,
        backgroundColor: '#9CA3AF',
        alignSelf: 'center',
    },
    skillTreeRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
    },
    progressSection: {
        marginTop: 10,
    },
    progressInfo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: scale(3),
    },
    progressLabel: {
        fontSize: responsiveFontSize.sm,
        color: '#6B7280',
    },
    progressLabelDark: {
        color: '#9CA3AF',
    },
    progressPercent: {
        fontSize: responsiveFontSize.sm,
        fontWeight: '600',
        color: '#3B82F6',
    },
    progressPercentDark: {
        color: '#93C5FD',
    },
    progressBar: {
        height: 4,
        backgroundColor: '#E5E7EB',
        borderRadius: 2,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#3B82F6',
        borderRadius: 2,
    },
    maxPromotionText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#16A34A',
        textAlign: 'center',
    },
    maxPromotionTextDark: {
        color: '#4ADE80',
    },
    promoteButton: {
        borderRadius: 8,
        overflow: 'hidden',
        marginTop: 8,
    },
    promoteButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        gap: 8,
    },
    promoteButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '700',
    },
    scrollContainer: {
        position: 'absolute',
        right: 10,
        top: 20,
        bottom: 20,
        width: 4,
        zIndex: 1,
    },
    scrollIndicator: {
        flex: 1,
        justifyContent: 'center',
    },
    scrollBar: {
        width: 4,
        height: 40,
        backgroundColor: '#E5E7EB',
        borderRadius: 2,
    },
    scrollThumb: {
        width: 4,
        height: 20,
        backgroundColor: '#9CA3AF',
        borderRadius: 2,
    },
    bailSection: {
        marginBottom: 20,
    },
    skillTreeContainer: {
        marginBottom: 24,
    },
    currentUpgrade: {
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        padding: responsiveSpacing.md,
        borderRadius: responsiveBorderRadius.sm,
        marginBottom: responsiveSpacing.md,
        borderLeftWidth: 2,
        borderLeftColor: '#10B981',
    },
    upgradeTitle: {
        fontSize: responsiveFontSize.base,
        fontWeight: '600',
        color: '#10B981',
        marginBottom: responsiveSpacing.xs,
    },
    upgradeTitleDark: {
        color: '#34D399',
    },
    upgradeEffect: {
        fontSize: responsiveFontSize.sm,
        color: '#059669',
    },
    upgradeEffectDark: {
        color: '#10B981',
    },
    upgradesContainer: {
        marginTop: 12,
    },
    upgradeCard: {
        marginBottom: 8,
        borderRadius: 8,
        overflow: 'hidden',
    },
    upgradeGradient: {
        padding: 12,
    },
    upgradeHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    upgradeLevel: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    upgradeCost: {
        marginTop: 6,
    },
    costText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },
    unlockedUpgrade: {
        opacity: 0.7,
    },
    availableUpgrade: {
        boxShadow: '0px 2px 4px rgba(59, 130, 246, 0.3)',
        ...Platform.select({
          web: { boxShadow: '0px 2px 4px rgba(59, 130, 246, 0.3)' } as any,
          default: {
            shadowColor: '#3B82F6',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.3,
            shadowRadius: 4,
          },
        }),
        elevation: 3,
    },
    lockedUpgrade: {
        opacity: 0.5,
    },
    unlockedText: {
        color: '#FFFFFF',
    },
    skillTreeButton: {
        backgroundColor: '#3B82F6',
        padding: responsiveSpacing.md,
        borderRadius: responsiveBorderRadius.sm,
        alignItems: 'center',
        marginTop: responsiveSpacing.md,
    },
    skillTreeButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: responsiveFontSize.base,
    },
    skillsContainer: {
        gap: responsiveSpacing.md,
        marginBottom: responsiveSpacing.lg,
    },
    skillCard: {
        borderRadius: responsiveBorderRadius.lg,
        overflow: 'hidden',
        ...Platform.select({
          web: { boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.15)' } as any,
          default: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.15,
            shadowRadius: 12,
          },
        }),
        elevation: 6,
    },
    skillCardGradient: {
        padding: responsiveSpacing.lg,
        flexDirection: 'row',
        alignItems: 'center',
        gap: responsiveSpacing.md,
    },
    skillIconContainer: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    skillIconContainerDark: {
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    skillCrownBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#FEF3C7',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#F59E0B',
    },
    skillInfo: {
        flex: 1,
    },
    skillName: {
        fontSize: responsiveFontSize.lg,
        fontWeight: '700',
        color: '#111827',
        marginBottom: responsiveSpacing.xs,
    },
    skillNameDark: {
        color: '#F9FAFB',
    },
    skillLevelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: responsiveSpacing.sm,
        marginBottom: responsiveSpacing.sm,
    },
    skillLevelBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: 'rgba(245, 158, 11, 0.15)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    skillLevelText: {
        fontSize: responsiveFontSize.sm,
        fontWeight: '600',
        color: '#92400E',
    },
    skillLevelTextDark: {
        color: '#FBBF24',
    },
    talentPointsBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: 'rgba(59, 130, 246, 0.15)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    talentPointsText: {
        fontSize: responsiveFontSize.sm,
        fontWeight: '600',
        color: '#1E40AF',
    },
    talentPointsTextDark: {
        color: '#60A5FA',
    },
    skillProgressWrapper: {
        marginBottom: responsiveSpacing.xs,
    },
    skillProgressBarBg: {
        height: 8,
        backgroundColor: 'rgba(0, 0, 0, 0.1)',
        borderRadius: 4,
        overflow: 'hidden',
        marginBottom: 6,
    },
    skillProgressBarBgDark: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
    },
    skillProgressBarFill: {
        height: '100%',
        borderRadius: 4,
    },
    skillProgressText: {
        fontSize: responsiveFontSize.xs,
        color: '#6B7280',
        fontWeight: '500',
    },
    skillProgressTextDark: {
        color: '#9CA3AF',
    },
    unlockedTalentsBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        alignSelf: 'flex-start',
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        marginTop: 4,
    },
    unlockedTalentsText: {
        fontSize: responsiveFontSize.xs,
        fontWeight: '600',
        color: '#065F46',
    },
    unlockedTalentsTextDark: {
        color: '#10B981',
    },

    // Liquid Glass Hobby Styles - Compact Design
    liquidGlassHeader: {
        marginBottom: 12,
        borderRadius: 12,
        overflow: 'hidden',
    },
    headerGlass: {
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        backdropFilter: 'blur(20px)',
    },
    liquidGlassTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 4,
        textAlign: 'center',
    },
    liquidGlassSubtitle: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        lineHeight: 18,
        textAlign: 'center',
    },
    hobbiesContainer: {
        gap: 8,
    },
    liquidGlassCard: {
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        backdropFilter: 'blur(20px)',
    },
    cardGlass: {
        padding: 12,
        borderRadius: 12,
    },
    lockedGlassCard: {
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(107, 114, 128, 0.3)',
        backdropFilter: 'blur(20px)',
    },
    lockedGlass: {
        padding: 12,
        borderRadius: 12,
        alignItems: 'center',
    },
    lockedHobbyName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#9CA3AF',
        marginBottom: 4,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    iconContainer: {
        width: 70,
        height: 70,
        borderRadius: 35,
        marginRight: 12,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
    },
    hobbyInfo: {
        flex: 1,
        alignItems: 'center',
    },
    hobbyName: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 2,
        textAlign: 'center',
    },
    levelBadge: {
        backgroundColor: 'rgba(59, 130, 246, 0.3)',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 8,
        alignSelf: 'center',
    },
    levelText: {
        fontSize: 10,
        fontWeight: '600',
        color: '#60A5FA',
        textAlign: 'center',
    },
    hobbyActionButtons: {
        flexDirection: 'row',
        gap: 6,
        justifyContent: 'flex-end',
        marginTop: 4,
        marginBottom: 4,
        alignItems: 'center',
    },
    hobbyActionButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        overflow: 'hidden',
    },
    hobbyActionButtonGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 18,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    hobbyImage: {
        width: 60,
        height: 60,
        resizeMode: 'contain',
    },
    topActionButtons: {
        flexDirection: 'row',
        gap: 4,
        alignItems: 'center',
    },
    compactButton: {
        borderRadius: 6,
        overflow: 'hidden',
        minWidth: 60,
        minHeight: 28,
    },
    compactButtonGradient: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: 28,
    },
    compactButtonText: {
        fontSize: 10,
        fontWeight: '600',
        color: '#FFFFFF',
        textAlign: 'center',
    },
    actionButtons: {
        flexDirection: 'row',
        gap: 8,
        justifyContent: 'center',
    },
    glassButton: {
        borderRadius: 8,
        overflow: 'hidden',
        width: 90,
        minHeight: 36,
    },
    disabledGlassButton: {
        opacity: 0.5,
    },
    buttonGradient: {
        paddingHorizontal: 8,
        paddingVertical: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        backdropFilter: 'blur(10px)',
        minHeight: 36,
        justifyContent: 'center',
        alignItems: 'center',
    },
    glassButtonText: {
        fontSize: 11,
        fontWeight: '600',
        color: '#FFFFFF',
        textAlign: 'center',
    },
    disabledGlassButtonText: {
        color: 'rgba(255,255,255,0.5)',
    },
    glassDescription: {
        fontSize: 13,
        color: 'rgba(255,255,255,0.8)',
        lineHeight: 16,
        marginBottom: 8,
        textAlign: 'center',
    },
    statsGrid: {
        flexDirection: 'row',
        gap: 6,
        marginBottom: 8,
    },
    statCard: {
        flex: 1,
        borderRadius: 8,
        overflow: 'hidden',
    },
    statGlass: {
        padding: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        backdropFilter: 'blur(10px)',
        alignItems: 'center',
    },
    statLabel: {
        fontSize: 10,
        color: 'rgba(255,255,255,0.7)',
        marginTop: 4,
        marginBottom: 2,
        textAlign: 'center',
    },
    statValue: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FFFFFF',
        textAlign: 'center',
    },
    glassProgressBar: {
        height: 6,
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 3,
        overflow: 'hidden',
        marginBottom: 4,
    },
    glassProgressFill: {
        height: '100%',
        borderRadius: 3,
    },
    progressText: {
        fontSize: 10,
        color: 'rgba(255,255,255,0.7)',
        textAlign: 'center',
    },
    upgradesTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 6,
        textAlign: 'center',
    },
    // New Full-Width Upgrade Buttons
    upgradeButtonFull: {
        marginBottom: 6,
        borderRadius: 8,
        overflow: 'hidden',
    },
    disabledUpgradeButtonFull: {
        opacity: 0.5,
    },
    upgradeButtonFullGradient: {
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        backdropFilter: 'blur(10px)',
    },
    upgradeButtonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    upgradeButtonInfo: {
        flex: 1,
        marginRight: 8,
    },
    upgradeButtonName: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 2,
    },
    upgradeButtonDesc: {
        fontSize: 10,
        color: 'rgba(255,255,255,0.8)',
        lineHeight: 12,
    },
    upgradeButtonCost: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    disabledUpgradeButtonText: {
        color: 'rgba(255,255,255,0.5)',
    },
    feedbackBubble: {
        backgroundColor: 'rgba(16, 185, 129, 0.2)',
        padding: 6,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        marginTop: 6,
    },
    feedbackText: {
        fontSize: 11,
        color: '#10B981',
        textAlign: 'center',
    },
    emptyState: {
        padding: 20,
        alignItems: 'center',
    },
    emptyStateText: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.6)',
        textAlign: 'center',
    },

    // Income Modal Styles - Liquid Glass Design
    incomeModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 15,
    },
    incomeModalContainer: {
        width: '92%',
        height: '80%',
        maxWidth: 450,
        borderRadius: 20,
        overflow: 'hidden',
        boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)',
        elevation: 15,
        ...Platform.select({
          web: { boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)' } as any,
          default: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.4,
            shadowRadius: 12,
          },
        }),
    },
    incomeModalGlass: {
        flex: 1,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.2)',
        padding: 24,
        minHeight: 400,
    },
    incomeModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 30,
    },
    incomeModalIconContainer: {
        width: 70,
        height: 70,
        borderRadius: 35,
        marginRight: 20,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    incomeModalHobbyImage: {
        width: 60,
        height: 60,
        resizeMode: 'contain',
    },
    incomeModalIconGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 25,
    },
    incomeModalTitleContainer: {
        flex: 1,
    },
    incomeModalTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 6,
    },
    incomeModalSubtitle: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.8)',
    },
    incomeModalCloseButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        overflow: 'hidden',
    },
    incomeModalCloseGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 25,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
    },
    incomeModalTotalContainer: {
        marginBottom: 25,
        borderRadius: 18,
        overflow: 'hidden',
    },
    incomeModalTotalGlass: {
        padding: 25,
        borderRadius: 18,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        alignItems: 'center',
    },
    incomeModalTotalLabel: {
        fontSize: 18,
        color: 'rgba(255,255,255,0.9)',
        marginBottom: 10,
        textAlign: 'center',
    },
    incomeModalTotalAmount: {
        fontSize: 36,
        fontWeight: '900',
        color: '#10B981',
        textAlign: 'center',
    },
    incomeModalItemsContainer: {
        flex: 1,
        marginBottom: 20,
        maxHeight: 300,
    },
    incomeModalItem: {
        marginBottom: 15,
        borderRadius: 15,
        overflow: 'hidden',
    },
    incomeModalItemGlass: {
        padding: 18,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    incomeModalItemInfo: {
        flex: 1,
    },
    incomeModalItemName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 5,
    },
    incomeModalItemGrade: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.7)',
    },
    incomeModalItemAmountContainer: {
        alignItems: 'flex-end',
    },
    incomeModalItemAmount: {
        fontSize: 18,
        fontWeight: '700',
        color: '#10B981',
    },
    incomeModalItemPeriod: {
        fontSize: 12,
        color: 'rgba(255,255,255,0.6)',
    },
    incomeModalFooter: {
        borderRadius: 15,
        overflow: 'hidden',
    },
    incomeModalFooterGlass: {
        padding: 18,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        alignItems: 'center',
    },
    incomeModalFooterText: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        textAlign: 'center',
        fontStyle: 'italic',
    },

    // Tabbed Modal Styles - Liquid Glass Design
    tabbedModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 15,
    },
    tabbedModalContainer: {
        width: '96%',
        height: '96%',
        maxWidth: 560,
        borderRadius: 20,
        overflow: 'hidden',
        boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)',
        elevation: 15,
        ...Platform.select({
          web: { boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)' } as any,
          default: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.4,
            shadowRadius: 12,
          },
        }),
    },
    tabbedModalGlass: {
        flex: 1,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.2)',
        padding: 24,
        minHeight: 560,
    },
    tabbedModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    tabbedModalIconContainer: {
        width: 50,
        height: 50,
        borderRadius: 25,
        marginRight: 15,
        overflow: 'hidden',
    },
    tabbedModalIconGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 25,
    },
    tabbedModalTitleContainer: {
        flex: 1,
    },
    tabbedModalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    tabbedModalSubtitle: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
    },
    tabbedModalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        overflow: 'hidden',
    },
    tabbedModalCloseGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    tabbedModalTabs: {
        flexDirection: 'row',
        marginBottom: 20,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    tabbedModalTab: {
        flex: 1,
        borderRadius: 12,
        overflow: 'hidden',
    },
    tabbedModalTabActive: {
        // Active state handled by gradient colors
    },
    tabbedModalTabGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        gap: 8,
    },
    tabbedModalTabText: {
        fontSize: 14,
        fontWeight: '600',
        color: 'rgba(255,255,255,0.7)',
    },
    tabbedModalTabTextActive: {
        color: '#FFFFFF',
    },
    tabbedModalContent: {
        flex: 1,
    },
    tabbedModalTabContent: {
        paddingBottom: 10,
    },
    tabbedModalContentTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 16,
        textAlign: 'center',
    },
    tabbedModalItem: {
        marginBottom: 12,
        borderRadius: 12,
        overflow: 'hidden',
    },
    tabbedModalItemGlass: {
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    tabbedModalItemInfo: {
        flex: 1,
        marginRight: 12,
    },
    tabbedModalItemName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    tabbedModalItemDetails: {
        fontSize: 12,
        color: 'rgba(255,255,255,0.7)',
    },
    tabbedModalItemButton: {
        borderRadius: 8,
        overflow: 'hidden',
    },
    tabbedModalItemButtonGradient: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    tabbedModalItemButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
        textAlign: 'center',
    },
    tabbedModalEmptyState: {
        padding: 40,
        alignItems: 'center',
    },
    tabbedModalEmptyText: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.6)',
        textAlign: 'center',
    },
    tabbedModalLeagueInfo: {
        padding: 20,
        borderRadius: 12,
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        alignItems: 'center',
    },
    tabbedModalLeagueText: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        textAlign: 'center',
        marginBottom: 16,
        lineHeight: 20,
    },
    tabbedModalLeagueButton: {
        borderRadius: 10,
        overflow: 'hidden',
    },
    tabbedModalLeagueButtonGradient: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    tabbedModalLeagueButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
        textAlign: 'center',
    },

    // Contract Modal Styles - Liquid Glass Design
    contractModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    contractModalContainer: {
        width: '90%',
        maxWidth: 400,
        maxHeight: '80%',
        borderRadius: 20,
        overflow: 'hidden',
    },
    contractModalGlass: {
        flex: 1,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.3)',
        padding: 20,
    },
    contractModalContent: {
        flex: 1,
    },
    contractModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    contractModalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#FFFFFF',
        flex: 1,
    },
    contractModalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        overflow: 'hidden',
    },
    contractModalCloseGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    contractModalBody: {
        flex: 1,
        marginBottom: 20,
    },
    contractModalInfo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginBottom: 8,
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    contractModalLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: 'rgba(255,255,255,0.8)',
    },
    contractModalValue: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    contractModalActionButton: {
        borderRadius: 12,
        overflow: 'hidden',
        marginTop: 10,
    },
    contractModalActionGradient: {
        paddingVertical: 16,
        paddingHorizontal: 24,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    contractModalActionText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    contractModalEmptyText: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.7)',
        textAlign: 'center',
        marginTop: 20,
    },
    contractModalOfferItem: {
        marginBottom: 12,
        borderRadius: 12,
        overflow: 'hidden',
    },
    contractModalOfferGlass: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    contractModalOfferInfo: {
        flex: 1,
        marginRight: 12,
    },
    contractModalOfferTeam: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    contractModalOfferDetails: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        marginBottom: 4,
    },
    contractModalOfferPay: {
        fontSize: 14,
        fontWeight: '600',
        color: '#10B981',
    },
    contractModalOfferButton: {
        borderRadius: 8,
        overflow: 'hidden',
        minWidth: 60,
    },
    contractModalOfferButtonGradient: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    contractModalOfferButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },

    // League Modal Styles - Liquid Glass Design
    leagueModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    leagueModalContainer: {
        width: '90%',
        maxWidth: 400,
        maxHeight: '80%',
        borderRadius: 20,
        overflow: 'hidden',
    },
    leagueModalGlass: {
        flex: 1,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.3)',
        padding: 20,
    },
    leagueModalContent: {
        flex: 1,
    },
    leagueModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    leagueModalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#FFFFFF',
        flex: 1,
    },
    leagueModalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        overflow: 'hidden',
    },
    leagueModalCloseGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    leagueModalDivisionTabs: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 20,
    },
    leagueModalDivisionTab: {
        flex: 1,
        borderRadius: 12,
        overflow: 'hidden',
    },
    leagueModalDivisionTabGradient: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    leagueModalDivisionTabText: {
        fontSize: 14,
        fontWeight: '600',
        color: 'rgba(255,255,255,0.7)',
    },
    leagueModalDivisionTabTextActive: {
        color: '#FFFFFF',
    },
    leagueModalStandings: {
        flex: 1,
    },
    leagueModalStandingItem: {
        marginBottom: 8,
        borderRadius: 12,
        overflow: 'hidden',
    },
    leagueModalStandingGlass: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    leagueModalStandingPosition: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    leagueModalStandingPositionText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    leagueModalStandingPositionTextActive: {
        color: '#10B981',
    },
    leagueModalStandingInfo: {
        flex: 1,
    },
    leagueModalStandingTeam: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 2,
    },
    leagueModalStandingTeamActive: {
        color: '#10B981',
    },
    leagueModalStandingStats: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
    },
    leagueModalStandingStatsActive: {
        color: 'rgba(16, 185, 129, 0.9)',
    },
    leagueModalStandingBadge: {
        backgroundColor: 'rgba(16, 185, 129, 0.8)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.6)',
    },
    leagueModalStandingBadgeText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FFFFFF',
    },

    // Sponsors Modal Styles - Liquid Glass Design
    sponsorsModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 15,
    },
    sponsorsModalContainer: {
        width: '92%',
        height: '80%',
        maxWidth: 450,
        borderRadius: 20,
        overflow: 'hidden',
        boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)',
        elevation: 15,
        ...Platform.select({
          web: { boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)' } as any,
          default: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.4,
            shadowRadius: 12,
          },
        }),
    },
    sponsorsModalGlass: {
        flex: 1,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.2)',
        padding: 24,
        minHeight: 400,
    },
    sponsorsModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 30,
    },
    sponsorsModalIconContainer: {
        width: 70,
        height: 70,
        borderRadius: 35,
        marginRight: 20,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    sponsorsModalHobbyImage: {
        width: 60,
        height: 60,
        resizeMode: 'contain',
    },
    sponsorsModalIconGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 35,
    },
    sponsorsModalTitleContainer: {
        flex: 1,
    },
    sponsorsModalTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 6,
    },
    sponsorsModalSubtitle: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.8)',
    },
    sponsorsModalCloseButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        overflow: 'hidden',
    },
    sponsorsModalCloseGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 25,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
    },
    sponsorsModalContent: {
        flex: 1,
        marginBottom: 20,
        maxHeight: 300,
    },
    sponsorsModalSponsorsList: {
        gap: 15,
    },
    sponsorsModalSponsorItem: {
        marginBottom: 15,
        borderRadius: 15,
        overflow: 'hidden',
    },
    sponsorsModalSponsorGlass: {
        padding: 18,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sponsorsModalSponsorInfo: {
        flex: 1,
    },
    sponsorsModalSponsorName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 5,
    },
    sponsorsModalSponsorDetails: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.7)',
    },
    sponsorsModalSponsorButton: {
        borderRadius: 12,
        overflow: 'hidden',
    },
    sponsorsModalSponsorButtonGradient: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
    },
    sponsorsModalSponsorButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    sponsorsModalEmptyState: {
        alignItems: 'center',
        padding: 40,
    },
    sponsorsModalEmptyText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 8,
        textAlign: 'center',
    },
    sponsorsModalEmptySubtext: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.7)',
        textAlign: 'center',
    },
    sponsorsModalFooter: {
        borderRadius: 15,
        overflow: 'hidden',
    },
    sponsorsModalFooterGlass: {
        padding: 18,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        alignItems: 'center',
    },
    sponsorsModalFooterText: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        textAlign: 'center',
        fontStyle: 'italic',
    },

    // Artworks Modal Styles - Liquid Glass Design
    artworksModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 15,
    },
    artworksModalContainer: {
        width: '92%',
        height: '80%',
        maxWidth: 450,
        borderRadius: 20,
        overflow: 'hidden',
        boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)',
        elevation: 15,
        ...Platform.select({
          web: { boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)' } as any,
          default: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.4,
            shadowRadius: 12,
          },
        }),
    },
    artworksModalGlass: {
        flex: 1,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.2)',
        padding: 24,
        minHeight: 400,
    },
    artworksModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 30,
    },
    artworksModalIconContainer: {
        width: 70,
        height: 70,
        borderRadius: 35,
        marginRight: 20,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    artworksModalHobbyImage: {
        width: 60,
        height: 60,
        resizeMode: 'contain',
    },
    artworksModalTitleContainer: {
        flex: 1,
    },
    artworksModalTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 6,
    },
    artworksModalSubtitle: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.8)',
    },
    artworksModalCloseButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        overflow: 'hidden',
    },
    artworksModalCloseGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 25,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
    },
    artworksModalContent: {
        flex: 1,
        marginBottom: 20,
        maxHeight: 300,
    },
    artworksModalArtworksList: {
        gap: 15,
    },
    artworksModalArtworkItem: {
        marginBottom: 15,
        borderRadius: 15,
        overflow: 'hidden',
    },
    artworksModalArtworkGlass: {
        padding: 18,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    artworksModalArtworkInfo: {
        flex: 1,
    },
    artworksModalArtworkGrade: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 5,
    },
    artworksModalArtworkIncome: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.7)',
    },
    artworksModalArtworkRank: {
        backgroundColor: 'rgba(139, 92, 246, 0.3)',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.5)',
    },
    artworksModalArtworkRankText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    artworksModalEmptyState: {
        alignItems: 'center',
        padding: 40,
    },
    artworksModalEmptyText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 8,
        textAlign: 'center',
    },
    artworksModalEmptySubtext: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.7)',
        textAlign: 'center',
    },
    artworksModalFooter: {
        borderRadius: 15,
        overflow: 'hidden',
    },
    artworksModalFooterGlass: {
        padding: 18,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        alignItems: 'center',
    },
    artworksModalFooterText: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        textAlign: 'center',
        fontStyle: 'italic',
    },

    // Songs Modal Styles - Liquid Glass Design
    songsModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 15,
    },
    songsModalContainer: {
        width: '92%',
        height: '80%',
        maxWidth: 450,
        borderRadius: 20,
        overflow: 'hidden',
        boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)',
        elevation: 15,
        ...Platform.select({
          web: { boxShadow: '0px 8px 12px rgba(0, 0, 0, 0.4)' } as any,
          default: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.4,
            shadowRadius: 12,
          },
        }),
    },
    songsModalGlass: {
        flex: 1,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.2)',
        padding: 24,
        minHeight: 400,
    },
    songsModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 30,
    },
    songsModalIconContainer: {
        width: 70,
        height: 70,
        borderRadius: 35,
        marginRight: 20,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    songsModalHobbyImage: {
        width: 60,
        height: 60,
        resizeMode: 'contain',
    },
    songsModalTitleContainer: {
        flex: 1,
    },
    songsModalTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 6,
    },
    songsModalSubtitle: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.8)',
    },
    songsModalCloseButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        overflow: 'hidden',
    },
    songsModalCloseGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 25,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
    },
    songsModalContent: {
        flex: 1,
        marginBottom: 20,
        maxHeight: 300,
    },
    songsModalSongsList: {
        gap: 15,
    },
    songsModalSongItem: {
        marginBottom: 15,
        borderRadius: 15,
        overflow: 'hidden',
    },
    songsModalSongGlass: {
        padding: 18,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    songsModalSongInfo: {
        flex: 1,
    },
    songsModalSongGrade: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 5,
    },
    songsModalSongIncome: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.7)',
    },
    songsModalSongRank: {
        backgroundColor: 'rgba(239, 68, 68, 0.3)',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.5)',
    },
    songsModalSongRankText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    songsModalEmptyState: {
        alignItems: 'center',
        padding: 40,
    },
    songsModalEmptyText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 8,
        textAlign: 'center',
    },
    songsModalEmptySubtext: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.7)',
        textAlign: 'center',
    },
    songsModalFooter: {
        borderRadius: 15,
        overflow: 'hidden',
    },
    songsModalFooterGlass: {
        padding: 18,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        alignItems: 'center',
    },
    songsModalFooterText: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        textAlign: 'center',
        fontStyle: 'italic',
    },

    // Play Modal Styles - Simple & Reliable
    playModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    playModalContainer: {
        width: '100%',
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingTop: 24,
        paddingBottom: 40,
        paddingHorizontal: 24,
        height: '92%',
        minHeight: 560,
    },
    playModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 24,
    },
    playModalIconContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
    },
    playModalHobbyImage: {
        width: 70,
        height: 70,
        resizeMode: 'contain',
    },
    playModalIconGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FEF3C7',
    },
    playModalTitleSection: {
        marginBottom: 32,
    },
    playModalTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 8,
    },
    playModalSubtitle: {
        fontSize: 18,
        color: '#6B7280',
        fontWeight: '500',
    },
    playModalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    playModalContent: {
        flex: 1,
    },
    playModalInfoBox: {
        backgroundColor: '#F9FAFB',
        borderRadius: 16,
        padding: 20,
        marginBottom: 32,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    playModalInfoText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        textAlign: 'center',
        marginBottom: 12,
        lineHeight: 24,
    },
    playModalInfoSubtext: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 20,
    },
    playModalActions: {
        gap: 12,
    },
    playModalActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#10B981',
        paddingVertical: 18,
        paddingHorizontal: 24,
        borderRadius: 16,
        gap: 12,
        boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
        elevation: 2,
        ...Platform.select({
          web: { boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)' } as any,
          default: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
          },
        }),
    },
    playModalActionButtonSecondary: {
        backgroundColor: '#3B82F6',
    },
    playModalActionButtonText: {
        fontSize: 17,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    playModalFooter: {
        marginTop: 24,
        backgroundColor: '#EFF6FF',
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#DBEAFE',
    },
    playModalFooterText: {
        fontSize: 14,
        color: '#1E40AF',
        textAlign: 'center',
        fontWeight: '500',
    },
});
