/* Review prototype only. No storage, network, simulation or rewards. */
const root='../../../../assets/images/';
const paths={career:{label:'Build a career',art:'scenes/work-office-modern.webp',headline:'Your first opportunity',detail:'Find your footing. Work toward the next promotion.',tag:'CAREER',week:'Work',verb:'Apply for a job',stages:[['Application sent','Requirements and timing shape your next opportunity.'],['An answer arrives','Applications can take up to two weeks. This example moves ahead to a successful reply.'],['Your first payday','Once hired, weekly wages join your income. Living costs still matter.']]},business:{label:'Create a business',art:'scenes/work-office-modern.webp',headline:'An idea becomes a plan',detail:'Start small. Turn your ideas into something of your own.',tag:'BUSINESS',week:'Build',verb:'Explore a business',stages:[['Compare the possibilities','Different businesses have different startup costs.'],['Make your first move','Found a company when you meet its requirements and can afford it.'],['Build it week by week','Manage the company as revenue, costs and opportunities change.']]},people:{label:'Find your people',art:'scenes/contacts-modern.webp',headline:'Someone worth knowing',detail:'Make time for connections. Build a life together.',tag:'RELATIONSHIPS',week:'Connect',verb:'Make a connection',stages:[['Meet someone new','Explore dating and get to know someone.'],['Make time for each other','Call, spend time together and deepen the relationship.'],['Life gets a little bigger','Friendships, partnerships and family become part of your story.']]}};
const icons={career:'M4 7h16v13H4zM9 7V4h6v3M4 12h16M10 12v3h4v-3',business:'M4 20V9h16v11M3 9l2-5h14l2 5M8 20v-7h8v7',people:'M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M2 21v-3a7 7 0 0 1 14 0v3M17 4a4 4 0 0 1 0 8M19 15c2 1 3 3 3 6'};
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
let step=0,path='career',beat=0,legacy='family';
const chapter=document.querySelector('#chapter'),next=document.querySelector('#next'),back=document.querySelector('#back'),skip=document.querySelector('#skip');
const announce=text=>document.querySelector('#announcer').textContent=text;
function artStage(){return `<div class="stage" aria-hidden="true"><div class="orbit"></div><img class="prop" src="${root+paths[path].art}" alt=""><div class="note note-top"><small>YOUR NEXT CHAPTER</small><strong>${paths[path].headline}</strong></div><div class="note note-bottom"><small>WEEK BY WEEK</small><strong>Your choices shape the story ↗</strong></div></div>`}
function render(focus=true){
 document.querySelectorAll('[data-step]').forEach((b,i)=>{b.toggleAttribute('aria-current',i===step);if(i===step)b.setAttribute('aria-current','step');b.classList.toggle('past',i<step)});
 back.disabled=step===0;back.style.visibility=step===0?'hidden':'visible';skip.hidden=step===3;
 const data=paths[path];
 if(step===0){chapter.innerHTML=`<p class="eyebrow">01 / Make it yours</p><h1>A whole life.<br><em>Yours to shape.</em></h1><p class="intro">The career. The people. The risks you take.<br>Where would you begin?</p>${artStage()}<p class="choice-title">What draws you in?</p><div class="choices" role="group" aria-label="Explore a direction">${Object.entries(paths).map(([id,p])=>`<button class="choice" aria-label="${p.label}" data-path="${id}" aria-pressed="${path===id}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[id]}"/></svg>${p.label}</button>`).join('')}</div><p class="selection-copy" id="selection-copy">${data.detail}</p>`;next.innerHTML='See your life unfold'+arrow;chapter.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>{path=b.dataset.path;beat=0;const chosen=paths[path];chapter.querySelectorAll('[data-path]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));chapter.querySelector('.prop').src=root+chosen.art;chapter.querySelector('.note-top strong').textContent=chosen.headline;chapter.querySelector('#selection-copy').textContent=chosen.detail;announce(chosen.label+'. '+chosen.detail)});}
 if(step===1){chapter.innerHTML=`<p class="eyebrow">02 / One week changes things</p><h1>Small moves.<br><em>A different future.</em></h1><p class="intro">Make a choice. Live a week.<br>See what life brings back.</p><div class="week-stage"><div class="mini-head"><span>ILLUSTRATIVE ${data.tag} STORY</span><strong id="moment-label"></strong></div><div class="week-art" aria-hidden="true"><img src="${root+data.art}" alt=""><div class="week-caption"><small>Your next move</small>${data.week}.<br>Grow.</div></div><div class="timeline" aria-hidden="true"><span></span><span></span><span></span></div><div class="event" id="event" aria-live="polite"></div><button class="demo-action" id="demo"></button></div><p class="context-line"><b>A life has trade-offs.</b> Money, health, time and relationships all need your attention.</p>`;updateWeek();next.innerHTML='Look beyond one lifetime'+arrow;}
 if(step===2){chapter.innerHTML=`<p class="eyebrow">03 / More than one lifetime</p><h1>Make a life.<br><em>Leave a legacy.</em></h1><p class="intro">Your story can carry on through an heir.<br>What would you want to leave behind?</p><div class="family-stage" aria-hidden="true"><svg class="family-link" viewBox="0 0 380 240"><path d="M120 105C130 210 260 25 270 142"/></svg><div class="person person-one"><img src="${root}portraits/river.webp" alt=""><small>GENERATION 01</small><strong>A life you build</strong></div><div class="person person-two"><img src="${root}portraits/dawn.webp" alt=""><small>THE NEXT CHAPTER</small><strong>A new beginning</strong></div><span class="generation">ONE STORY. MANY CHAPTERS.</span></div><div class="legacy-options" role="group" aria-label="Explore your legacy"><button data-legacy="family" aria-pressed="${legacy==='family'}">The people in your life</button><button data-legacy="future" aria-pressed="${legacy==='future'}">A foundation for the future</button></div><p class="legacy-description" id="legacy-copy"></p>`;updateLegacy();chapter.querySelectorAll('[data-legacy]').forEach(b=>b.onclick=()=>{legacy=b.dataset.legacy;updateLegacy();announce(document.querySelector('#legacy-copy').textContent)});next.innerHTML='Make this story yours'+arrow;}
 if(step===3){chapter.innerHTML=`<p class="eyebrow">Your story starts next</p><h1>Who will<br><em>you become?</em></h1><p class="intro">Choose your starting life, create your character and find out.</p><div class="final-card"><span class="choice-title">Your curiosity, not a commitment</span><p>You explored <strong>${data.label.toLowerCase()}</strong>. In the game, you can pursue more than one direction.</p><p>This is the end of the interactive design preview. The real scenario picker and character creator follow here in the proposed flow.</p></div><button class="replay" id="restart">Try another direction</button>`;next.innerHTML='Review the opening again'+arrow;document.querySelector('#restart').onclick=()=>go(0);}
 chapter.classList.remove('enter');void chapter.offsetWidth;chapter.classList.add('enter');if(focus){chapter.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}
}
function updateWeek(){const p=paths[path],event=document.querySelector('#event');document.querySelector('#moment-label').textContent=['FIRST MOVE','WHAT HAPPENS NEXT','A NEW ROUTINE'][beat];document.querySelectorAll('.timeline span').forEach((x,i)=>x.classList.toggle('done',i<=beat));event.innerHTML=`<span class="event-symbol" aria-hidden="true">${beat===2?'✓':beat+1}</span><div><strong>${p.stages[beat][0]}</strong><p>${p.stages[beat][1]}</p></div>`;event.classList.remove('update');void event.offsetWidth;event.classList.add('update');const b=document.querySelector('#demo');b.textContent=['See what happens next','See the next chapter','Replay this glimpse'][beat];b.onclick=()=>{beat=(beat+1)%3;updateWeek();announce(p.stages[beat].join('. '))};}
function updateLegacy(){document.querySelectorAll('[data-legacy]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.legacy===legacy)));document.querySelector('#legacy-copy').textContent=legacy==='family'?'The people you meet become part of your life. Build relationships, start a family and discover the next generation.':'The home, wealth and opportunities you build can shape what comes next. Continue as an heir and begin another life.';}
function go(n){step=n;render()}
next.onclick=()=>go(step<3?step+1:0);back.onclick=()=>go(Math.max(0,step-1));skip.onclick=()=>go(3);document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>go(Number(b.dataset.step)));render(false);
