/**
 * A feed row must not subscribe to the whole game state.
 *
 * `PostCard` is rendered ~60 times in the Pulse FlatList (`recentPosts` is
 * capped at 50 in `composePost`, plus ~11 ambient posts generated by
 * `FeedScreen`). It used `useGame()`, which composes `useGameState()` — a plain
 * `useContext` on the provider carrying `gameState` — so EVERY mutation
 * anywhere in the game re-rendered every mounted row, each one also rebuilding
 * the merged 9-context object inside `useGame`'s memo. It was unmemoized too,
 * so a parent render re-rendered all of them regardless.
 *
 * The component only needs the setter and `saveGame`. `useSetGameState` exists
 * precisely to give write access WITHOUT a state subscription — CLAUDE.md §4.1
 * documents pulling `setGameState` out of `useGameState()` as a known perf
 * regression, and `tasks/lessons.md` records it dated 2026-06-09.
 * 2026-07-30 audit PERF-2.
 *
 * Static assertions rather than a render harness: mounting a FlatList row needs
 * the full 9-provider tree, and what actually matters here is which hook the
 * component reaches for. That is exactly what regressed, and it is what a
 * future edit would change.
 */
import fs from 'fs';
import path from 'path';

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const POST_CARD = path.join(REPO_ROOT, 'components/mobile/Pulse/components/PostCard.tsx');
const source = fs.readFileSync(POST_CARD, 'utf8');

/**
 * Comments stripped. The docblocks in PostCard NAME the hooks it must not use
 * (explaining why), so asserting against the raw text matched the explanation
 * rather than the code — these assertions failed on their own comments.
 */
const code = source
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/(^|[^:])\/\/.*$/gm, '$1');

describe('PostCard takes no full-state subscription', () => {
  it('does not call useGame()', () => {
    // `useGame()` is the combined hook — it re-renders on every mutation.
    expect(code).not.toMatch(/\buseGame\s*\(/);
  });

  it('gets write access through useSetGameState', () => {
    expect(code).toMatch(/useSetGameState\s*\(/);
  });

  it('gets saveGame from the actions context, which carries no state', () => {
    expect(code).toMatch(/useGameActions\s*\(/);
  });

  it('does not reach for gameState at all', () => {
    // Reading any slice would reintroduce a subscription; the row renders
    // entirely from its props.
    expect(code).not.toMatch(/\bgameState\b/);
  });
});

describe('PostCard is memoized', () => {
  it('exports through React.memo', () => {
    // Without this a parent re-render walks all ~60 rows even when every row's
    // props are unchanged.
    expect(code).toMatch(/export default React\.memo\(PostCard\)/);
  });

  it('does not also export the raw component as default', () => {
    expect(code).not.toMatch(/export default function PostCard/);
  });
});

describe('its writes persist after the commit, not before it', () => {
  it('defers saveGame past the state update', () => {
    // `saveGame` reads `gameStateRef.current`, which a POST-COMMIT effect
    // syncs — a synchronous call persists the PRE-like snapshot. Same
    // convention as BrandDealsScreen and DeathPopup.
    const likeBlock = source.slice(source.indexOf('const handleLike'), source.indexOf('const handleRepost'));

    expect(likeBlock).toMatch(/likePost\(setGameState, post\.id\)/);
    expect(likeBlock).toMatch(/setTimeout\(\(\) => \{ void saveGame\?\.\(\); \}, 0\)/);
  });

  it('does the same for repost', () => {
    const repostBlock = source.slice(source.indexOf('const handleRepost'));

    expect(repostBlock).toMatch(/repostPost\(setGameState, post\.id\)/);
    expect(repostBlock.slice(0, 600)).toMatch(/setTimeout\(\(\) => \{ void saveGame\?\.\(\); \}, 0\)/);
  });
});
