import { Career } from '@/contexts/game/types';

export const INITIAL_CAREERS: Career[] = [
    {
        id: 'fast_food',
        levels: [
            { name: 'Fast Food Worker', salary: 50 },
            { name: 'Crew Member', salary: 60 },
            { name: 'Shift Leader', salary: 55 },
            { name: 'Assistant Manager', salary: 70 },
            { name: 'Restaurant Manager', salary: 85 },
            { name: 'District Manager', salary: 110 },
        ],
        level: 0,
        description: 'Flip burgers in a fast-food restaurant',
        requirements: {},
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'retail',
        levels: [
            { name: 'Retail Associate', salary: 65 },
            { name: 'Senior Associate', salary: 70 },
            { name: 'Floor Supervisor', salary: 85 },
            { name: 'Assistant Manager', salary: 100 },
            { name: 'Store Manager', salary: 125 },
            { name: 'Regional Manager', salary: 155 },
        ],
        level: 0,
        description: 'Assist customers and manage inventory in retail',
        requirements: {},
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'janitor',
        levels: [
            { name: 'Janitor', salary: 55 },
            { name: 'Senior Janitor', salary: 65 },
            { name: 'Maintenance Lead', salary: 55 },
            { name: 'Maintenance Supervisor', salary: 70 },
            { name: 'Facility Manager', salary: 85 },
            { name: 'Facilities Director', salary: 105 },
        ],
        level: 0,
        description: 'Keep buildings clean and operational',
        requirements: {},
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'teacher',
        levels: [
            { name: 'Teaching Assistant', salary: 220 },
            { name: 'Substitute Teacher', salary: 280 },
            { name: 'School Teacher', salary: 340 },
            { name: 'Senior Teacher', salary: 400 },
            { name: 'Department Head', salary: 480 },
            { name: 'Principal', salary: 600 },
        ],
        level: 0,
        description: 'Educate the next generation',
        requirements: { education: ['business_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'nurse',
        levels: [
            { name: 'Nursing Assistant', salary: 300 },
            { name: 'LPN', salary: 360 },
            { name: 'Registered Nurse', salary: 420 },
            { name: 'Senior Nurse', salary: 480 },
            { name: 'Nurse Practitioner', salary: 580 },
            { name: 'Nurse Manager', salary: 700 },
        ],
        level: 0,
        description: 'Provide healthcare services',
        requirements: { fitness: 40, education: ['business_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'software',
        levels: [
            { name: 'Junior Developer', salary: 1100 },
            { name: 'Developer', salary: 1400 },
            { name: 'Software Engineer', salary: 1700 },
            { name: 'Senior Engineer', salary: 2000 },
            { name: 'Lead Engineer', salary: 2400 },
            { name: 'Engineering Manager', salary: 3000 },
        ],
        level: 0,
        description: 'Develop software applications',
        requirements: { items: ['computer'], education: ['masters_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'doctor',
        levels: [
            { name: 'Medical Intern', salary: 1700 },
            { name: 'Resident Doctor', salary: 2200 },
            { name: 'Senior Resident', salary: 2700 },
            { name: 'Medical Doctor', salary: 3200 },
            { name: 'Senior Doctor', salary: 3800 },
            { name: 'Chief of Medicine', salary: 4800 },
        ],
        level: 0,
        description: 'Practice medicine and heal patients',
        requirements: { education: ['phd'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'lawyer',
        levels: [
            { name: 'Paralegal', salary: 1400 },
            { name: 'Junior Associate', salary: 1750 },
            { name: 'Associate Lawyer', salary: 2100 },
            { name: 'Senior Associate', salary: 2600 },
            { name: 'Senior Lawyer', salary: 3100 },
            { name: 'Partner', salary: 4000 },
        ],
        level: 0,
        description: 'Practice law and represent clients',
        requirements: { items: ['suit'], education: ['legal_studies', 'masters_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'corporate',
        levels: [
            { name: 'Business Intern', salary: 1750 },
            { name: 'Analyst', salary: 2400 },
            { name: 'Senior Analyst', salary: 3000 },
            { name: 'Manager', salary: 3600 },
            { name: 'Senior Manager', salary: 4800 },
            { name: 'CEO', salary: 6000 },
        ],
        level: 0,
        description: 'Climb the corporate ladder',
        requirements: { items: ['suit', 'computer'], education: ['mba'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'police',
        levels: [
            { name: 'Police Cadet', salary: 150 },
            { name: 'Police Officer', salary: 230 },
            { name: 'Senior Officer', salary: 290 },
            { name: 'Sergeant', salary: 350 },
            { name: 'Lieutenant', salary: 430 },
            { name: 'Captain', salary: 550 },
        ],
        level: 0,
        description: 'Protect and serve the community',
        requirements: { fitness: 50, education: ['police_academy'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'legal',
        levels: [
            { name: 'Junior Legal Assistant', salary: 130 },
            { name: 'Legal Assistant', salary: 190 },
            { name: 'Senior Legal Assistant', salary: 270 },
        ],
        level: 0,
        description: 'Support legal professionals',
        requirements: { items: ['smartphone', 'computer'], education: ['legal_studies'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'bank',
        levels: [
            { name: 'Bank Teller', salary: 230 },
            { name: 'Loan Officer', salary: 350 },
            { name: 'Bank Manager', salary: 510 },
        ],
        level: 0,
        description: 'Manage banking operations',
        requirements: { items: ['smartphone', 'computer', 'suit'], education: ['business_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'accountant',
        levels: [
            { name: 'Accounting Clerk', salary: 155 },
            { name: 'Accountant', salary: 270 },
            { name: 'Senior Accountant', salary: 390 },
        ],
        level: 0,
        description: 'Handle financial records',
        requirements: { items: ['computer'], education: ['business_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'politician',
        levels: [
            { name: 'Campaign Volunteer', salary: 190 },
            { name: 'City Council Member', salary: 470 },
            { name: 'Mayor', salary: 980 },
        ],
        level: 0,
        description: 'Serve the public through politics',
        requirements: { reputation: 20 },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'celebrity',
        levels: [
            { name: 'Influencer', salary: 310 },
            { name: 'TV Star', salary: 700 },
            { name: 'Movie Icon', salary: 1370 },
        ],
        level: 0,
        description: 'Live in the spotlight',
        requirements: { reputation: 30 },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'athlete',
        levels: [
            { name: 'Rookie', salary: 270 },
            { name: 'Pro', salary: 620 },
            { name: 'Champion', salary: 1170 },
        ],
        level: 0,
        description: 'Compete at the highest level',
        requirements: { fitness: 60 },
        progress: 0,
        applied: false,
        accepted: false,
    },
    // ─── New careers added in Phase 3 ───────────────────────────────
    {
        id: 'chef',
        levels: [
            { name: 'Line Cook', salary: 40 },
            { name: 'Sous Chef', salary: 65 },
            { name: 'Head Chef', salary: 95 },
            { name: 'Executive Chef', salary: 140 },
            { name: 'Restaurant Owner-Chef', salary: 200 },
            { name: 'Celebrity Chef', salary: 350 },
        ],
        level: 0,
        description: 'Create culinary masterpieces',
        requirements: {},
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'military',
        levels: [
            { name: 'Private', salary: 120 },
            { name: 'Corporal', salary: 160 },
            { name: 'Sergeant', salary: 210 },
            { name: 'Lieutenant', salary: 280 },
            { name: 'Captain', salary: 370 },
            { name: 'Colonel', salary: 500 },
        ],
        level: 0,
        description: 'Serve your country in the armed forces',
        requirements: { fitness: 50 },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'pilot',
        levels: [
            { name: 'Flight Student', salary: 80 },
            { name: 'Co-Pilot', salary: 300 },
            { name: 'Commercial Pilot', salary: 500 },
            { name: 'Senior Pilot', salary: 700 },
            { name: 'Captain', salary: 950 },
            { name: 'Chief Pilot', salary: 1200 },
        ],
        level: 0,
        description: 'Fly commercial aircraft around the world',
        requirements: { education: ['business_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'journalist',
        levels: [
            { name: 'Intern Reporter', salary: 60 },
            { name: 'Staff Writer', salary: 110 },
            { name: 'Senior Reporter', salary: 180 },
            { name: 'Editor', salary: 280 },
            { name: 'Managing Editor', salary: 400 },
            { name: 'Editor-in-Chief', salary: 550 },
        ],
        level: 0,
        description: 'Report the news and uncover stories',
        requirements: { education: ['business_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'architect',
        levels: [
            { name: 'Draftsperson', salary: 200 },
            { name: 'Junior Architect', salary: 350 },
            { name: 'Architect', salary: 500 },
            { name: 'Senior Architect', salary: 700 },
            { name: 'Principal Architect', salary: 950 },
            { name: 'Firm Partner', salary: 1300 },
        ],
        level: 0,
        description: 'Design buildings and structures',
        requirements: { items: ['computer'], education: ['masters_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'veterinarian',
        levels: [
            { name: 'Vet Assistant', salary: 100 },
            { name: 'Vet Technician', salary: 180 },
            { name: 'Veterinarian', salary: 350 },
            { name: 'Senior Vet', salary: 500 },
            { name: 'Specialist Vet', salary: 650 },
            { name: 'Clinic Owner', salary: 850 },
        ],
        level: 0,
        description: 'Care for animals and treat their illnesses',
        requirements: { education: ['masters_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'musician',
        levels: [
            { name: 'Street Performer', salary: 25 },
            { name: 'Session Musician', salary: 60 },
            { name: 'Band Member', salary: 120 },
            { name: 'Solo Artist', salary: 250 },
            { name: 'Recording Artist', salary: 500 },
            { name: 'Rock Star', salary: 1000 },
        ],
        level: 0,
        description: 'Make music and perform for audiences',
        requirements: {},
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'electrician',
        levels: [
            { name: 'Apprentice', salary: 80 },
            { name: 'Journeyman', salary: 150 },
            { name: 'Electrician', salary: 220 },
            { name: 'Master Electrician', salary: 320 },
            { name: 'Electrical Contractor', salary: 450 },
            { name: 'Business Owner', salary: 600 },
        ],
        level: 0,
        description: 'Install and repair electrical systems',
        requirements: {},
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'truck_driver',
        levels: [
            { name: 'Delivery Driver', salary: 55 },
            { name: 'Local Hauler', salary: 85 },
            { name: 'Long-Haul Trucker', salary: 130 },
            { name: 'Specialized Hauler', salary: 180 },
            { name: 'Fleet Supervisor', salary: 240 },
            { name: 'Fleet Manager', salary: 320 },
        ],
        level: 0,
        description: 'Transport goods across the country',
        requirements: {},
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'farmer',
        levels: [
            { name: 'Farm Hand', salary: 35 },
            { name: 'Farm Worker', salary: 55 },
            { name: 'Senior Farm Hand', salary: 80 },
            { name: 'Farm Foreman', salary: 120 },
            { name: 'Farm Manager', salary: 180 },
            { name: 'Farm Owner', salary: 300 },
        ],
        level: 0,
        description: 'Work the land and grow crops',
        requirements: {},
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'real_estate_agent',
        levels: [
            { name: 'Trainee Agent', salary: 80 },
            { name: 'Junior Agent', salary: 150 },
            { name: 'Real Estate Agent', salary: 280 },
            { name: 'Senior Agent', salary: 450 },
            { name: 'Broker', salary: 650 },
            { name: 'Agency Owner', salary: 900 },
        ],
        level: 0,
        description: 'Buy and sell properties for clients',
        requirements: { items: ['smartphone'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'therapist',
        levels: [
            { name: 'Counseling Intern', salary: 100 },
            { name: 'Licensed Counselor', salary: 200 },
            { name: 'Therapist', salary: 350 },
            { name: 'Senior Therapist', salary: 500 },
            { name: 'Clinical Director', salary: 650 },
            { name: 'Private Practice Owner', salary: 850 },
        ],
        level: 0,
        description: 'Help people with their mental health',
        requirements: { education: ['masters_degree'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'firefighter',
        levels: [
            { name: 'Probationary Firefighter', salary: 130 },
            { name: 'Firefighter', salary: 190 },
            { name: 'Senior Firefighter', salary: 250 },
            { name: 'Lieutenant', salary: 330 },
            { name: 'Captain', salary: 420 },
            { name: 'Fire Chief', salary: 550 },
        ],
        level: 0,
        description: 'Fight fires and save lives',
        requirements: { fitness: 55 },
        progress: 0,
        applied: false,
        accepted: false,
    },
    {
        id: 'graphic_designer',
        levels: [
            { name: 'Junior Designer', salary: 80 },
            { name: 'Graphic Designer', salary: 150 },
            { name: 'Senior Designer', salary: 250 },
            { name: 'Art Director', salary: 400 },
            { name: 'Creative Director', salary: 600 },
            { name: 'Design Studio Owner', salary: 800 },
        ],
        level: 0,
        description: 'Create visual designs and brand identities',
        requirements: { items: ['computer'] },
        progress: 0,
        applied: false,
        accepted: false,
    },
];
