import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  Alert,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { useRouter } from 'expo-router';
import { useHardwareBack } from '@/hooks/useHardwareBack';
import { Dices, Play, Shuffle } from 'lucide-react-native';
import BlurViewFallback from '@/components/fallbacks/BlurViewFallback';
import Gradient from '@/components/ui/Gradient';
import OnboardingScreenShellV2 from '@/components/onboarding/OnboardingScreenShellV2';
import OnboardingGlassHeader from '@/components/onboarding/OnboardingGlassHeader';
import OnboardingFloatingButton from '@/components/onboarding/OnboardingFloatingButton';
import OnboardingStepBar from '@/components/onboarding/OnboardingStepBar';
import VectorAvatar from '@/components/avatar/VectorAvatar';
import { generateRandomName } from '@/src/features/onboarding/nameData';
import {
  applyIdentityDraftToOnboardingState,
  canContinueFromIdentityDraft,
  IdentitySexuality,
  shouldGenerateInitialIdentityName,
  shouldRegenerateIdentityNameForSexChange,
} from '@/src/features/onboarding/customizeIdentity';
import { useOnboarding } from '@/src/features/onboarding/OnboardingContext';
import { logOnboardingStepView } from '@/src/features/onboarding/onboardingAnalytics';
import { useOnboardingFlowGuard } from '@/hooks/useOnboardingFlowGuard';
import { haptic } from '@/utils/haptics';
import { decodeAvatar, encodeAvatar } from '@/lib/avatar/encode';
import { pickersFor } from '@/lib/avatar/pickers';
import { randomAvatar } from '@/lib/avatar/random';
import type { AvatarConfig, AvatarSex } from '@/lib/avatar/types';
import {
  fontScale,
  responsiveBorderRadius,
  responsiveFontSize,
  responsivePadding,
  responsiveSpacing,
  scale,
  verticalScale,
} from '@/utils/scaling';

const BlurView = BlurViewFallback;
const LinearGradient = Gradient;

type SexualityOption = IdentitySexuality;

const SEX_OPTIONS: { value: AvatarSex; label: string }[] = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
];

const SEXUALITY_OPTIONS: { value: SexualityOption; label: string }[] = [
  { value: 'straight', label: 'Straight' },
  { value: 'gay', label: 'Gay' },
  { value: 'bi', label: 'Bisexual' },
];

/**
 * "Random" is an ACTION here, not a stored value.
 *
 * The old screen persisted `sex: 'random'` and resolved it later from whichever
 * portrait the player happened to tap, which meant appearance and gameplay sex
 * could disagree and the name generator had to chase the face. A vector face
 * has to be drawn for a concrete sex anyway, so an unresolved sex has nowhere
 * to live — it is resolved once, on mount, and the Randomize button re-rolls
 * appearance WITHOUT flipping it. Sex changing under the player mid-edit reads
 * as a bug, however random they asked the rest to be.
 */
function resolveInitialSex(stored: 'male' | 'female' | 'random' | undefined): AvatarSex {
  if (stored === 'male' || stored === 'female') return stored;
  return Math.random() < 0.5 ? 'male' : 'female';
}

export default function Customize() {
  const router = useRouter();
  const navigation = useNavigation();
  const { state, setState } = useOnboarding();
  useOnboardingFlowGuard('Customize');

  useEffect(() => {
    logOnboardingStepView('Customize');
  }, []);

  const [firstName, setFirstName] = useState(state.firstName || '');
  const [lastName, setLastName] = useState(state.lastName || '');
  const [sex, setSex] = useState<AvatarSex>(() => resolveInitialSex(state.sex));
  const [sexuality, setSexuality] = useState<SexualityOption>(state.sexuality || 'straight');
  const [avatar, setAvatar] = useState<AvatarConfig>(
    () => decodeAvatar(state.avatar) ?? randomAvatar(resolveInitialSex(state.sex))
  );
  const [activeCategory, setActiveCategory] = useState(0);
  const lastAutoGeneratedSex = useRef<AvatarSex | null>(null);

  const categories = useMemo(() => pickersFor(sex), [sex]);
  // Facial hair drops out of the list on a feminine face, so an index held from
  // the previous sex can point past the end.
  const category = categories[Math.min(activeCategory, categories.length - 1)];

  const scenarioAge = state.scenario?.start?.age ?? 18;

  // Three checkpoints across a life, always ascending and always distinct — a
  // scenario starting at 60 must not render "60, 45, 75".
  const agePreview = useMemo(() => {
    const start = Math.max(1, Math.round(scenarioAge));
    return [start, Math.max(start + 12, 45), Math.max(start + 24, 75)];
  }, [scenarioAge]);

  useEffect(() => {
    if (!shouldGenerateInitialIdentityName(firstName, lastName)) return;
    const randomName = generateRandomName(sex);
    setFirstName(randomName.firstName);
    setLastName(randomName.lastName);
    lastAutoGeneratedSex.current = sex;
  }, [firstName, lastName, sex]);

  useEffect(() => {
    if (
      !shouldRegenerateIdentityNameForSexChange({
        sex,
        firstName,
        lastName,
        lastAutoGeneratedSex: lastAutoGeneratedSex.current,
      })
    ) {
      return;
    }
    const randomName = generateRandomName(sex);
    setFirstName(randomName.firstName);
    setLastName(randomName.lastName);
    lastAutoGeneratedSex.current = sex;
  }, [firstName, lastName, sex]);

  const handleBack = useCallback(() => {
    if (navigation.canGoBack()) {
      router.back();
      return;
    }
    router.replace('/(onboarding)/MainMenu');
  }, [navigation, router]);

  // R3-C: the Android hardware back button shares the handler so a system
  // gesture doesn't drop the player onto a blank screen.
  useHardwareBack(() => {
    handleBack();
    return true;
  });

  const handleShuffleName = useCallback(() => {
    haptic.light();
    const randomName = generateRandomName(sex);
    setFirstName(randomName.firstName);
    setLastName(randomName.lastName);
    lastAutoGeneratedSex.current = sex;
  }, [sex]);

  const handleRandomizeFace = useCallback(() => {
    haptic.medium();
    setAvatar(randomAvatar(sex));
  }, [sex]);

  const handleSelectOption = useCallback(
    (index: number) => {
      haptic.selection();
      setAvatar((prev) => ({ ...prev, [category.field]: index }));
    },
    [category.field]
  );

  const handleSexChange = useCallback((next: AvatarSex) => {
    haptic.selection();
    setSex(next);
    // Facial hair is never drawn on a feminine face; clearing it here stops a
    // beard chosen as male from lingering invisibly in the saved config.
    setAvatar((prev) => (next === 'female' ? { ...prev, facialHair: 0 } : prev));
  }, []);

  const handleFirstNameChange = useCallback((value: string) => {
    lastAutoGeneratedSex.current = null;
    setFirstName(value);
  }, []);

  const handleLastNameChange = useCallback((value: string) => {
    lastAutoGeneratedSex.current = null;
    setLastName(value);
  }, []);

  const handleContinue = useCallback(() => {
    if (!state.scenario) {
      haptic.error();
      Alert.alert('Missing Scenario', 'Choose a scenario before customizing identity.');
      router.replace('/(onboarding)/Scenarios');
      return;
    }

    if (!canContinueFromIdentityDraft({ firstName, lastName })) {
      haptic.error();
      Alert.alert('Missing Name', 'Enter both first and last name to continue.');
      return;
    }

    haptic.medium();
    setState((prev) =>
      applyIdentityDraftToOnboardingState(prev, {
        firstName: firstName.trim(),
        lastName: lastName.trim(),
        sex,
        sexuality,
        // The legacy pool id is deliberately dropped for a new life: the face
        // is now fully described by `avatar`, and leaving a stale id behind
        // would seed the derived-face fallback with a portrait nobody chose.
        avatarId: undefined,
        avatar: encodeAvatar(avatar),
      })
    );
    router.push('/(onboarding)/Ambitions');
  }, [avatar, firstName, lastName, router, setState, sex, sexuality, state.scenario]);

  const fullName = `${firstName || 'Unnamed'} ${lastName || ''}`.trim();

  return (
    <OnboardingScreenShellV2
      floatingButton={
        <OnboardingFloatingButton
          title="Continue To Ambitions"
          onPress={handleContinue}
          icon={<Play size={24} color="#FFFFFF" />}
        />
      }
    >
      <OnboardingGlassHeader
        title="Create Character"
        onBack={handleBack}
        onInfo={() =>
          Alert.alert(
            'Create Your Character',
            'Build a face that is yours — it ages with you across the whole life, and your children will inherit it. Name, sex and sexuality shape your story and relationships, not difficulty.'
          )
        }
      />

      <OnboardingStepBar currentStep={2} totalSteps={4} />

      <ScrollView
        style={styles.scrollContainer}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator
        keyboardShouldPersistTaps="handled"
      >
        {/* ── Hero: the live face ──────────────────────────────────────── */}
        <View style={styles.sectionContainer}>
          <BlurView intensity={20} style={styles.sectionBlur}>
            <LinearGradient
              colors={['rgba(30, 41, 59, 0.9)', 'rgba(15, 23, 42, 0.8)']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={styles.heroCard}
            >
              <View style={styles.avatarRing}>
                <VectorAvatar config={avatar} sex={sex} age={scenarioAge} size={scale(168)} circular />
              </View>

              <Text style={styles.heroName} numberOfLines={1}>
                {fullName}
              </Text>
              <Text style={styles.heroSub}>Ages with you · passed to your children</Text>

              {/* The claim above, made checkable. The same config rendered at
                  three ages — this is the whole reason the face is parameters
                  rather than a picked portrait, so showing it beats saying it. */}
              <View style={styles.ageStrip}>
                {agePreview.map((previewAge) => (
                  <View key={previewAge} style={styles.agePreview}>
                    <VectorAvatar
                      config={avatar}
                      sex={sex}
                      age={previewAge}
                      size={scale(44)}
                      circular
                    />
                    <Text style={styles.ageLabel}>{previewAge}</Text>
                  </View>
                ))}
              </View>

              <View style={styles.heroActions}>
                <TouchableOpacity
                  accessibilityRole="button"
                  accessibilityLabel="Randomize appearance"
                  onPress={handleRandomizeFace}
                  style={[styles.pill, styles.pillPrimary]}
                >
                  <Dices size={scale(16)} color="#FFFFFF" />
                  <Text style={styles.pillPrimaryLabel}>Randomize</Text>
                </TouchableOpacity>

                <TouchableOpacity
                  accessibilityRole="button"
                  accessibilityLabel="Shuffle name"
                  onPress={handleShuffleName}
                  style={styles.pill}
                >
                  <Shuffle size={scale(16)} color="#60A5FA" />
                  <Text style={styles.pillLabel}>New name</Text>
                </TouchableOpacity>
              </View>
            </LinearGradient>
          </BlurView>
        </View>

        {/* ── Appearance editor ────────────────────────────────────────── */}
        <View style={styles.sectionContainer}>
          <BlurView intensity={20} style={styles.sectionBlur}>
            <LinearGradient
              colors={['rgba(30, 41, 59, 0.9)', 'rgba(15, 23, 42, 0.8)']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={styles.sectionCard}
            >
              <Text style={styles.sectionTitle}>Appearance</Text>

              <ScrollView
                horizontal
                showsHorizontalScrollIndicator={false}
                contentContainerStyle={styles.categoryStrip}
              >
                {categories.map((entry, index) => {
                  const isSelected = entry.field === category.field;
                  return (
                    <TouchableOpacity
                      key={entry.field}
                      accessibilityRole="button"
                      accessibilityLabel={`${entry.label} options`}
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => {
                        haptic.selection();
                        setActiveCategory(index);
                      }}
                      style={[styles.categoryChip, isSelected && styles.categoryChipSelected]}
                    >
                      <Text
                        style={[styles.categoryLabel, isSelected && styles.categoryLabelSelected]}
                      >
                        {entry.label}
                      </Text>
                    </TouchableOpacity>
                  );
                })}
              </ScrollView>

              <View style={styles.optionGrid}>
                {category.options.map((option, index) => {
                  const isSelected = avatar[category.field] === index;
                  const label = `${category.label} ${option.label}`;

                  if (category.kind === 'color') {
                    return (
                      <TouchableOpacity
                        key={`${category.field}-${index}`}
                        accessibilityRole="button"
                        accessibilityLabel={label}
                        accessibilityState={{ selected: isSelected }}
                        onPress={() => handleSelectOption(index)}
                        style={[styles.swatch, isSelected && styles.swatchSelected]}
                      >
                        <View style={[styles.swatchFill, { backgroundColor: option.color }]} />
                      </TouchableOpacity>
                    );
                  }

                  return (
                    <TouchableOpacity
                      key={`${category.field}-${index}`}
                      accessibilityRole="button"
                      accessibilityLabel={label}
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => handleSelectOption(index)}
                      style={[styles.optionChip, isSelected && styles.optionChipSelected]}
                    >
                      <Text
                        style={[styles.optionLabel, isSelected && styles.optionLabelSelected]}
                        numberOfLines={1}
                      >
                        {option.label}
                      </Text>
                    </TouchableOpacity>
                  );
                })}
              </View>
            </LinearGradient>
          </BlurView>
        </View>

        {/* ── Identity ─────────────────────────────────────────────────── */}
        <View style={styles.sectionContainer}>
          <BlurView intensity={20} style={styles.sectionBlur}>
            <LinearGradient
              colors={['rgba(30, 41, 59, 0.9)', 'rgba(15, 23, 42, 0.8)']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={styles.sectionCard}
            >
              <Text style={styles.sectionTitle}>Identity</Text>

              <View style={styles.nameRow}>
                <View style={styles.nameField}>
                  <Text style={styles.inputLabel}>First Name</Text>
                  <View style={styles.inputWrap}>
                    <TextInput
                      placeholder="Enter first name"
                      placeholderTextColor="#94A3B8"
                      style={styles.inputText}
                      value={firstName}
                      onChangeText={handleFirstNameChange}
                    />
                  </View>
                </View>

                <View style={styles.nameField}>
                  <Text style={styles.inputLabel}>Last Name</Text>
                  <View style={styles.inputWrap}>
                    <TextInput
                      placeholder="Enter last name"
                      placeholderTextColor="#94A3B8"
                      style={styles.inputText}
                      value={lastName}
                      onChangeText={handleLastNameChange}
                    />
                  </View>
                </View>
              </View>

              <Text style={styles.fieldLabel}>Sex</Text>
              <View style={styles.segmentRow}>
                {SEX_OPTIONS.map((option) => {
                  const isSelected = sex === option.value;
                  return (
                    <TouchableOpacity
                      key={option.value}
                      accessibilityRole="button"
                      accessibilityLabel={`${option.label} sex`}
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => handleSexChange(option.value)}
                      style={[styles.segment, isSelected && styles.segmentSelected]}
                    >
                      <Text style={[styles.segmentLabel, isSelected && styles.segmentLabelSelected]}>
                        {option.label}
                      </Text>
                    </TouchableOpacity>
                  );
                })}
              </View>

              <Text style={styles.fieldLabel}>Sexuality</Text>
              <View style={styles.segmentRow}>
                {SEXUALITY_OPTIONS.map((option) => {
                  const isSelected = sexuality === option.value;
                  return (
                    <TouchableOpacity
                      key={option.value}
                      accessibilityRole="button"
                      accessibilityLabel={`${option.label} sexuality`}
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => {
                        haptic.selection();
                        setSexuality(option.value);
                      }}
                      style={[styles.segment, isSelected && styles.segmentSelected]}
                    >
                      <Text style={[styles.segmentLabel, isSelected && styles.segmentLabelSelected]}>
                        {option.label}
                      </Text>
                    </TouchableOpacity>
                  );
                })}
              </View>

              <Text style={styles.helperText}>
                Sex and sexuality shape your story and relationships — not difficulty.
              </Text>
            </LinearGradient>
          </BlurView>
        </View>

        <View style={{ height: verticalScale(140) }} />
      </ScrollView>
    </OnboardingScreenShellV2>
  );
}

const styles = StyleSheet.create({
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    gap: responsiveSpacing.lg,
    paddingHorizontal: responsivePadding.large,
    paddingTop: responsiveSpacing.sm,
    paddingBottom: responsiveSpacing.lg,
  },
  sectionContainer: {
    borderRadius: 16,
    overflow: 'hidden',
    ...Platform.select({
      web: { boxShadow: '0px 8px 16px rgba(0, 0, 0, 0.3)' } as any,
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
      },
    }),
    elevation: 12,
  },
  sectionBlur: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  sectionCard: {
    padding: 20,
    // Match the parent's rounded clip so the border isn't sliced at the corners.
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    gap: responsiveSpacing.md,
  },
  heroCard: {
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    gap: responsiveSpacing.xs,
  },
  avatarRing: {
    borderRadius: scale(96),
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.35)',
    padding: scale(5),
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
  },
  heroName: {
    fontSize: responsiveFontSize.xl,
    fontWeight: '800',
    color: '#FFFFFF',
    marginTop: responsiveSpacing.xs,
    textAlign: 'center',
  },
  heroSub: {
    fontSize: fontScale(11),
    fontWeight: '600',
    color: '#94A3B8',
    textAlign: 'center',
  },
  ageStrip: {
    flexDirection: 'row',
    gap: responsiveSpacing.md,
    marginTop: responsiveSpacing.sm,
  },
  agePreview: {
    alignItems: 'center',
    gap: verticalScale(3),
  },
  ageLabel: {
    fontSize: fontScale(10),
    fontWeight: '700',
    color: '#64748B',
  },
  heroActions: {
    flexDirection: 'row',
    gap: responsiveSpacing.sm,
    marginTop: responsiveSpacing.sm,
  },
  pill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: responsiveBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    flexDirection: 'row',
    gap: responsiveSpacing.xs,
    paddingHorizontal: responsiveSpacing.md,
    paddingVertical: verticalScale(9),
  },
  pillPrimary: {
    backgroundColor: 'rgba(59, 130, 246, 0.28)',
    borderColor: 'rgba(96, 165, 250, 0.85)',
  },
  pillLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    color: '#60A5FA',
  },
  pillPrimaryLabel: {
    fontSize: fontScale(12),
    fontWeight: '800',
    color: '#FFFFFF',
  },
  sectionTitle: {
    fontSize: responsiveFontSize.xl,
    fontWeight: '800',
    color: '#FFFFFF',
    ...Platform.select({
      web: { textShadow: '1px 1px 3px rgba(0, 0, 0, 0.5)' } as any,
      default: {
        textShadowColor: 'rgba(0, 0, 0, 0.5)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
      },
    }),
  },
  categoryStrip: {
    gap: responsiveSpacing.xs,
    paddingRight: responsiveSpacing.sm,
    paddingVertical: verticalScale(2),
  },
  categoryChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: responsiveSpacing.md,
    paddingVertical: verticalScale(8),
  },
  categoryChipSelected: {
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    borderColor: 'rgba(96, 165, 250, 0.85)',
  },
  categoryLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    color: '#CBD5E1',
  },
  categoryLabelSelected: {
    color: '#FFFFFF',
  },
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: responsiveSpacing.sm,
  },
  swatch: {
    width: scale(42),
    height: scale(42),
    borderRadius: scale(21),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    padding: scale(3),
  },
  swatchSelected: {
    borderColor: '#60A5FA',
    borderWidth: 2,
  },
  swatchFill: {
    flex: 1,
    borderRadius: scale(18),
  },
  optionChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    minWidth: scale(84),
    paddingHorizontal: responsiveSpacing.sm,
    paddingVertical: verticalScale(10),
  },
  optionChipSelected: {
    backgroundColor: 'rgba(59, 130, 246, 0.18)',
    borderColor: 'rgba(96, 165, 250, 0.85)',
  },
  optionLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    color: '#CBD5E1',
    textAlign: 'center',
  },
  optionLabelSelected: {
    color: '#FFFFFF',
  },
  nameRow: {
    gap: responsiveSpacing.sm,
  },
  nameField: {
    gap: responsiveSpacing.xs,
  },
  inputLabel: {
    fontSize: fontScale(11),
    fontWeight: '600',
    color: '#94A3B8',
  },
  inputWrap: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    minHeight: verticalScale(44),
    justifyContent: 'center',
    paddingHorizontal: responsiveSpacing.sm,
  },
  inputText: {
    fontSize: fontScale(14),
    fontWeight: '600',
    color: '#FFFFFF',
  },
  segmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: responsiveSpacing.sm,
  },
  segment: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    flexGrow: 1,
    minWidth: scale(92),
    paddingHorizontal: responsiveSpacing.md,
    paddingVertical: verticalScale(11),
  },
  segmentSelected: {
    backgroundColor: 'rgba(59, 130, 246, 0.18)',
    borderColor: 'rgba(96, 165, 250, 0.85)',
  },
  segmentLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    textAlign: 'center',
    color: '#CBD5E1',
  },
  segmentLabelSelected: {
    color: '#FFFFFF',
  },
  fieldLabel: {
    fontSize: fontScale(11),
    fontWeight: '700',
    color: '#94A3B8',
    marginTop: responsiveSpacing.xs,
    marginBottom: verticalScale(2),
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  helperText: {
    fontSize: fontScale(11),
    fontWeight: '500',
    color: '#94A3B8',
    marginTop: responsiveSpacing.xs,
  },
});
