import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Image, ImageSourcePropType, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { useRouter } from 'expo-router';
import { useHardwareBack } from '@/hooks/useHardwareBack';
import { Play, Shuffle } from 'lucide-react-native';
import BlurViewFallback from '@/components/fallbacks/BlurViewFallback';
import LinearGradientFallback from '@/components/fallbacks/LinearGradientFallback';
import OnboardingScreenShellV2 from '@/components/onboarding/OnboardingScreenShellV2';
import OnboardingGlassHeader from '@/components/onboarding/OnboardingGlassHeader';
import OnboardingFloatingButton from '@/components/onboarding/OnboardingFloatingButton';
import OnboardingStepBar from '@/components/onboarding/OnboardingStepBar';
import { generateRandomName } from '@/src/features/onboarding/nameData';
import {
  applyIdentityDraftToOnboardingState,
  canContinueFromIdentityDraft,
  IdentitySex,
  IdentitySexuality,
  shouldGenerateInitialIdentityName,
  shouldRegenerateIdentityNameForSexChange,
} from '@/src/features/onboarding/customizeIdentity';
import { useOnboarding } from '@/src/features/onboarding/OnboardingContext';
import { logOnboardingStepView } from '@/src/features/onboarding/onboardingAnalytics';
import { listStarterAvatars, avatarSexFromId } from '@/utils/facePool';
import FaceCreatorModal from '@/components/identity/FaceCreatorModal';
import { randomizeFace, type FaceGenome } from '@/lib/identity';
import { useOnboardingFlowGuard } from '@/hooks/useOnboardingFlowGuard';
import { haptic } from '@/utils/haptics';
import {
  fontScale,
  responsiveBorderRadius,
  responsiveFontSize,
  responsivePadding,
  responsiveSpacing,
  scale,
  verticalScale,
} from '@/utils/scaling';
const BlurView = BlurViewFallback;
const LinearGradient = LinearGradientFallback;

type SexOption = IdentitySex;
type SexualityOption = IdentitySexuality;

interface SexOptionConfig {
  value: SexOption;
  label: string;
  icon: ImageSourcePropType;
}

interface SexualityOptionConfig {
  value: SexualityOption;
  label: string;
}

const SEX_OPTIONS: SexOptionConfig[] = [
  { value: 'male', label: 'Male', icon: require('@/assets/images/Sex/Male.png') },
  { value: 'female', label: 'Female', icon: require('@/assets/images/Sex/Female.png') },
  { value: 'random', label: 'Random', icon: require('@/assets/images/Sex/Dice.png') },
];

const SEXUALITY_OPTIONS: SexualityOptionConfig[] = [
  { value: 'straight', label: 'Straight' },
  { value: 'gay', label: 'Gay' },
  { value: 'bi', label: 'Bisexual' },
];

export default function Customize() {
  const router = useRouter();
  const navigation = useNavigation();
  const { state, setState } = useOnboarding();
  useOnboardingFlowGuard('Customize');

  useEffect(() => {
    logOnboardingStepView('Customize');
  }, []);

  const [firstName, setFirstName] = useState(state.firstName || '');
  const [lastName, setLastName] = useState(state.lastName || '');
  const [sex, setSex] = useState<SexOption>(state.sex || 'random');
  const [sexuality, setSexuality] = useState<SexualityOption>(state.sexuality || 'straight');
  const [avatarId, setAvatarId] = useState<string | undefined>(state.avatarId);
  // The 3D-creator face. Undefined until the player opens the creator — the
  // starter-portrait strip above stays the fast default path.
  const [faceGenome, setFaceGenome] = useState<FaceGenome | undefined>(state.faceGenome);
  const [facePortraitUri, setFacePortraitUri] = useState<string | undefined>(state.facePortraitUri);
  const [creatorOpen, setCreatorOpen] = useState(false);
  const lastAutoGeneratedSex = useRef<SexOption | null>(null);

  // Starter faces matched to the chosen sex AND the scenario's starting age band.
  // Keep the selection valid as either changes.
  const scenarioAge = state.scenario?.start?.age ?? 18;
  const avatarOptions = useMemo(() => listStarterAvatars(sex, scenarioAge), [sex, scenarioAge]);
  useEffect(() => {
    if (avatarOptions.length === 0) return;
    if (!avatarId || !avatarOptions.some((option) => option.id === avatarId)) {
      // For an explicit Male/Female pick the first face is fine, but the Random
      // list is female-first — always defaulting to index 0 would make "Random"
      // resolve female every single time (the chosen face's sex wins at build).
      // Pick a random face so Random is genuinely random.
      const defaultIndex =
        sex === 'random' ? Math.floor(Math.random() * avatarOptions.length) : 0;
      setAvatarId(avatarOptions[defaultIndex].id);
    }
  }, [avatarOptions, avatarId, sex]);

  // The character's real sex is the chosen face's sex (that's what wins in the
  // builder), so drive the name from that — a Random pick showing a male face
  // should get a male name, not an independent 50/50 flip that can mismatch it.
  const nameSex: SexOption =
    sex === 'random' ? (avatarSexFromId(avatarId) ?? 'random') : sex;

  useEffect(() => {
    if (!shouldGenerateInitialIdentityName(firstName, lastName)) {
      return;
    }

    const randomName = generateRandomName(nameSex);
    setFirstName(randomName.firstName);
    setLastName(randomName.lastName);
    lastAutoGeneratedSex.current = nameSex;
  }, [firstName, lastName, nameSex]);

  useEffect(() => {
    if (
      !shouldRegenerateIdentityNameForSexChange({
        sex: nameSex,
        firstName,
        lastName,
        lastAutoGeneratedSex: lastAutoGeneratedSex.current,
      })
    ) {
      return;
    }

    const randomName = generateRandomName(nameSex);
    setFirstName(randomName.firstName);
    setLastName(randomName.lastName);
    lastAutoGeneratedSex.current = nameSex;
  }, [firstName, lastName, nameSex]);

  const handleBack = useCallback(() => {
    if (navigation.canGoBack()) {
      router.back();
      return;
    }
    router.replace('/(onboarding)/MainMenu');
  }, [navigation, router]);

  // R3-C: wire the Android hardware back button to the same handler so a
  // system gesture / nav-bar back doesn't drop the player into a blank screen.
  useHardwareBack(() => {
    handleBack();
    return true;
  });

  const handleShuffle = useCallback(() => {
    haptic.light();
    const randomName = generateRandomName(nameSex);
    setFirstName(randomName.firstName);
    setLastName(randomName.lastName);
    lastAutoGeneratedSex.current = nameSex;
  }, [nameSex]);

  const handleFirstNameChange = useCallback((value: string) => {
    lastAutoGeneratedSex.current = null;
    setFirstName(value);
  }, []);

  const handleLastNameChange = useCallback((value: string) => {
    lastAutoGeneratedSex.current = null;
    setLastName(value);
  }, []);

  const handleContinue = useCallback(() => {
    if (!state.scenario) {
      haptic.error();
      Alert.alert('Missing Scenario', 'Choose a scenario before customizing identity.');
      router.replace('/(onboarding)/Scenarios');
      return;
    }

    if (!canContinueFromIdentityDraft({ firstName, lastName })) {
      haptic.error();
      Alert.alert('Missing Name', 'Enter both first and last name to continue.');
      return;
    }

    haptic.medium();
    const trimmedFirstName = firstName.trim();
    const trimmedLastName = lastName.trim();

    setState((prev) =>
      applyIdentityDraftToOnboardingState(prev, {
        firstName: trimmedFirstName,
        lastName: trimmedLastName,
        sex,
        sexuality,
        avatarId,
      })
    );
    // `applyIdentityDraftToOnboardingState` owns the legacy identity fields; the
    // 3D face is additive, so it is merged separately rather than widening that
    // helper's contract (and its tests) for two optional keys.
    setState((prev) => ({ ...prev, faceGenome, facePortraitUri }));
    router.push('/(onboarding)/Ambitions');
  }, [avatarId, faceGenome, facePortraitUri, firstName, lastName, router, setState, sex, sexuality, state.scenario]);

  // The chosen starter portrait, used as the creator's no-GL fallback so a
  // device that cannot open a GL context still shows a face rather than a hole.
  const selectedAvatarSource = useMemo(
    () => avatarOptions.find((option) => option.id === avatarId)?.source,
    [avatarOptions, avatarId],
  );

  const selectedSexLabel = useMemo(() => {
    return SEX_OPTIONS.find((option) => option.value === sex)?.label ?? sex;
  }, [sex]);

  const selectedSexualityLabel = useMemo(() => {
    return SEXUALITY_OPTIONS.find((option) => option.value === sexuality)?.label ?? sexuality;
  }, [sexuality]);

  return (
    <OnboardingScreenShellV2
      floatingButton={
        <OnboardingFloatingButton
          title="Continue To Ambitions"
          onPress={handleContinue}
          icon={<Play size={24} color="#FFFFFF" />}
        />
      }
    >
      <OnboardingGlassHeader
        title="Create Identity"
        onBack={handleBack}
        onInfo={() =>
          Alert.alert(
            'Create Your Identity',
            'Customize your character by choosing their name, sex, and sexuality. Use Shuffle to generate names instantly.'
          )
        }
      />

      <OnboardingStepBar currentStep={2} totalSteps={4} />

      <Text style={styles.guidanceText}>
        Name, sex, and sexuality only shape your story and relationships — not difficulty. Tap Shuffle for a random name.
      </Text>

      <ScrollView
        style={styles.scrollContainer}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={true}
      >
        {/* Appearance Section */}
        <View style={styles.sectionContainer}>
          <BlurView intensity={20} style={styles.sectionBlur}>
            <LinearGradient
              colors={['rgba(30, 41, 59, 0.9)', 'rgba(15, 23, 42, 0.8)']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={styles.sectionCard}
            >
              <Text style={styles.sectionTitle}>Appearance</Text>

              {/* Sex first — it drives which faces are offered below. */}
              <Text style={styles.fieldLabel}>Sex</Text>
              <View style={styles.sexRow}>
                {SEX_OPTIONS.map((option) => {
                  const isSelected = sex === option.value;
                  return (
                    <TouchableOpacity
                      key={option.value}
                      accessibilityRole="button"
                      accessibilityLabel={`${option.label} sex`}
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => {
                        haptic.selection();
                        setSex(option.value);
                      }}
                      style={[styles.sexCard, isSelected && styles.sexCardSelected]}
                    >
                      <Image source={option.icon} style={styles.sexIcon} />
                      <Text style={styles.sexLabel}>{option.label}</Text>
                    </TouchableOpacity>
                  );
                })}
              </View>

              {/* Face row — only faces for the chosen sex and the scenario's age. */}
              <Text style={styles.fieldLabel}>Choose your face — it ages with you</Text>
              <ScrollView
                horizontal
                showsHorizontalScrollIndicator={false}
                contentContainerStyle={styles.avatarStrip}
              >
                {avatarOptions.map((option) => {
                  const isSelected = avatarId === option.id;
                  return (
                    <TouchableOpacity
                      key={option.id}
                      accessibilityRole="button"
                      accessibilityLabel={`Choose avatar ${option.id}`}
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => {
                        haptic.selection();
                        setAvatarId(option.id);
                      }}
                      style={[styles.avatarChoice, isSelected && styles.avatarChoiceSelected]}
                    >
                      <Image source={option.source} style={styles.avatarChoiceImg} resizeMode="cover" />
                    </TouchableOpacity>
                  );
                })}
              </ScrollView>

              {/* 3D creator — opt-in depth. The strip above stays the one-tap
                  default so a player who wants to start a life immediately can. */}
              <TouchableOpacity
                accessibilityRole="button"
                accessibilityLabel="Build your face in 3D"
                onPress={() => {
                  haptic.medium();
                  if (!faceGenome) {
                    setFaceGenome(randomizeFace(`onboarding-${Date.now()}`, { sex: nameSex }));
                  }
                  setCreatorOpen(true);
                }}
                style={styles.creatorButton}
              >
                <Text style={styles.creatorButtonText}>
                  {faceGenome ? 'Edit your 3D face' : 'Or build your own face in 3D'}
                </Text>
              </TouchableOpacity>
              {faceGenome ? (
                <Text style={styles.creatorNote}>Using your custom face</Text>
              ) : null}
            </LinearGradient>
          </BlurView>
        </View>

        {/* Name Section */}
        <View style={styles.sectionContainer}>
          <BlurView intensity={20} style={styles.sectionBlur}>
            <LinearGradient
              colors={['rgba(30, 41, 59, 0.9)', 'rgba(15, 23, 42, 0.8)']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={styles.sectionCard}
            >
              <View style={styles.sectionHeader}>
                <Text style={styles.sectionTitle}>Name</Text>
                <TouchableOpacity
                  accessibilityLabel="Shuffle name"
                  onPress={handleShuffle}
                  style={styles.shuffleButton}
                >
                  <Shuffle size={scale(16)} color="#60A5FA" />
                  <Text style={styles.shuffleLabel}>Shuffle</Text>
                </TouchableOpacity>
              </View>

              <View style={styles.nameRow}>
                <View style={styles.nameField}>
                  <Text style={styles.inputLabel}>First Name</Text>
                  <View style={styles.inputWrap}>
                    <TextInput
                      placeholder="Enter first name"
                      placeholderTextColor="#94A3B8"
                      style={styles.inputText}
                      value={firstName}
                      onChangeText={handleFirstNameChange}
                    />
                  </View>
                </View>

                <View style={styles.nameField}>
                  <Text style={styles.inputLabel}>Last Name</Text>
                  <View style={styles.inputWrap}>
                    <TextInput
                      placeholder="Enter last name"
                      placeholderTextColor="#94A3B8"
                      style={styles.inputText}
                      value={lastName}
                      onChangeText={handleLastNameChange}
                    />
                  </View>
                </View>
              </View>
            </LinearGradient>
          </BlurView>
        </View>

        {/* Sexuality Section */}
        <View style={styles.sectionContainer}>
          <BlurView intensity={20} style={styles.sectionBlur}>
            <LinearGradient
              colors={['rgba(30, 41, 59, 0.9)', 'rgba(15, 23, 42, 0.8)']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={styles.sectionCard}
            >
              <Text style={styles.sectionTitle}>Sexuality</Text>
              <View style={styles.sexualityRow}>
                {SEXUALITY_OPTIONS.map((option) => {
                  const isSelected = sexuality === option.value;
                  return (
                    <TouchableOpacity
                      key={option.value}
                      accessibilityRole="button"
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => { haptic.selection(); setSexuality(option.value); }}
                      style={[
                        styles.sexualityChip,
                        isSelected && styles.sexualityChipSelected,
                      ]}
                    >
                      <Text style={[styles.sexualityLabel, isSelected && styles.sexualityLabelSelected]}>
                        {option.label}
                      </Text>
                    </TouchableOpacity>
                  );
                })}
              </View>
            </LinearGradient>
          </BlurView>
        </View>

        <View style={{ height: 140 }} />
      </ScrollView>

      {/* Mounted at the screen root so the modal is not clipped by the
          ScrollView, and only opens a GL context while the player is in it. */}
      {faceGenome ? (
        <FaceCreatorModal
          visible={creatorOpen}
          genome={faceGenome}
          onChange={setFaceGenome}
          onClose={() => setCreatorOpen(false)}
          onDone={(portraitUri) => setFacePortraitUri(portraitUri ?? undefined)}
          age={scenarioAge}
          sex={nameSex}
          fallback={
            selectedAvatarSource ? (
              <Image source={selectedAvatarSource} style={styles.creatorFallbackImg} resizeMode="cover" />
            ) : null
          }
        />
      ) : null}
    </OnboardingScreenShellV2>
  );
}

const styles = StyleSheet.create({
  guidanceText: {
    fontSize: fontScale(13),
    fontWeight: '500',
    color: '#94A3B8',
    textAlign: 'center',
    paddingHorizontal: responsivePadding.large,
    paddingBottom: responsiveSpacing.xs,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    gap: responsiveSpacing.lg,
    paddingHorizontal: responsivePadding.large,
    paddingTop: responsiveSpacing.sm,
    paddingBottom: responsiveSpacing.lg,
  },
  sectionContainer: {
    borderRadius: 16,
    overflow: 'hidden',
    ...Platform.select({
      web: { boxShadow: '0px 8px 16px rgba(0, 0, 0, 0.3)' } as any,
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
      },
    }),
    elevation: 12,
  },
  sectionBlur: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  sectionCard: {
    padding: 20,
    // Match the parent's rounded clip so the white border doesn't get sliced
    // off at the corners (square border inside an overflow:hidden rounded box).
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    gap: responsiveSpacing.md,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  creatorButton: {
    marginTop: responsiveSpacing.md,
    alignItems: 'center',
    paddingVertical: responsivePadding.small,
    borderRadius: responsiveBorderRadius.md,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.6)',
    backgroundColor: 'rgba(96, 165, 250, 0.10)',
  },
  creatorButtonText: {
    color: '#93C5FD',
    fontSize: responsiveFontSize.md,
    fontWeight: '600',
  },
  creatorFallbackImg: {
    width: '100%',
    height: '100%',
  },
  creatorNote: {
    marginTop: responsiveSpacing.xs,
    textAlign: 'center',
    color: '#94A3B8',
    fontSize: responsiveFontSize.xs,
  },
  sectionTitle: {
    fontSize: responsiveFontSize.xl,
    fontWeight: '800',
    color: '#FFFFFF',
    ...Platform.select({
      web: { textShadow: '1px 1px 3px rgba(0, 0, 0, 0.5)' } as any,
      default: {
        textShadowColor: 'rgba(0, 0, 0, 0.5)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
      },
    }),
  },
  shuffleButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: responsiveBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    flexDirection: 'row',
    gap: responsiveSpacing.xs,
    paddingHorizontal: responsiveSpacing.sm,
    paddingVertical: verticalScale(7),
  },
  shuffleLabel: {
    fontSize: fontScale(11),
    fontWeight: '700',
    color: '#60A5FA',
  },
  nameRow: {
    gap: responsiveSpacing.sm,
  },
  nameField: {
    gap: responsiveSpacing.xs,
  },
  inputLabel: {
    fontSize: fontScale(11),
    fontWeight: '600',
    color: '#94A3B8',
  },
  inputWrap: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    minHeight: verticalScale(44),
    justifyContent: 'center',
    paddingHorizontal: responsiveSpacing.sm,
  },
  inputText: {
    fontSize: fontScale(14),
    fontWeight: '600',
    color: '#FFFFFF',
  },
  sexRow: {
    flexDirection: 'row',
    gap: responsiveSpacing.sm,
  },
  sexCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    flex: 1,
    gap: responsiveSpacing.xs,
    justifyContent: 'center',
    minHeight: verticalScale(108),
    paddingHorizontal: responsiveSpacing.xs,
    paddingVertical: verticalScale(12),
  },
  sexCardSelected: {
    borderColor: 'rgba(96, 165, 250, 0.85)',
    borderWidth: 2,
    backgroundColor: 'rgba(59, 130, 246,0.15)',
  },
  sexIcon: {
    borderRadius: responsiveBorderRadius.md,
    height: scale(30),
    width: scale(30),
  },
  sexLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    color: '#FFFFFF',
  },
  sexualityRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: responsiveSpacing.sm,
  },
  sexualityChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    minWidth: scale(92),
    paddingHorizontal: responsiveSpacing.md,
    paddingVertical: verticalScale(10),
  },
  sexualityChipSelected: {
    borderColor: 'rgba(96, 165, 250, 0.85)',
    borderWidth: 2,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  sexualityLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    textAlign: 'center',
    color: '#CBD5E1',
  },
  sexualityLabelSelected: {
    color: '#FFFFFF',
  },
  fieldLabel: {
    fontSize: fontScale(11),
    fontWeight: '700',
    color: '#94A3B8',
    marginTop: responsiveSpacing.xs,
    marginBottom: verticalScale(6),
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  avatarStrip: {
    gap: responsiveSpacing.sm,
    paddingVertical: responsiveSpacing.xs,
    paddingRight: responsiveSpacing.sm,
  },
  avatarChoice: {
    width: scale(60),
    height: scale(60),
    borderRadius: scale(30),
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  avatarChoiceSelected: {
    borderColor: '#60A5FA',
    borderWidth: 3,
  },
  avatarChoiceImg: {
    width: '100%',
    height: '100%',
  },
});
