import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Image, ImageSourcePropType, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { useRouter } from 'expo-router';
import { useHardwareBack } from '@/hooks/useHardwareBack';
import { ChevronLeft, ChevronRight, Dices, Glasses, Play, Shuffle } from 'lucide-react-native';
import BlurViewFallback from '@/components/fallbacks/BlurViewFallback';
import LinearGradientFallback from '@/components/fallbacks/LinearGradientFallback';
import OnboardingScreenShellV2 from '@/components/onboarding/OnboardingScreenShellV2';
import OnboardingGlassHeader from '@/components/onboarding/OnboardingGlassHeader';
import OnboardingFloatingButton from '@/components/onboarding/OnboardingFloatingButton';
import OnboardingStepBar from '@/components/onboarding/OnboardingStepBar';
import { generateRandomName } from '@/src/features/onboarding/nameData';
import {
  applyIdentityDraftToOnboardingState,
  canContinueFromIdentityDraft,
  IdentitySex,
  IdentitySexuality,
  shouldGenerateInitialIdentityName,
  shouldRegenerateIdentityNameForSexChange,
} from '@/src/features/onboarding/customizeIdentity';
import { useOnboarding } from '@/src/features/onboarding/OnboardingContext';
import { logOnboardingStepView } from '@/src/features/onboarding/onboardingAnalytics';
import {
  AVATAR_HAIRS,
  AVATAR_HAIR_COLORS,
  AVATAR_SKIN_TONES,
  decodePlayerAvatarConfig,
  encodePlayerAvatarConfig,
  randomPlayerAvatarConfig,
  type PlayerAvatarConfig,
} from '@/utils/playerAvatar';
import PlayerAvatarView from '@/components/avatar/PlayerAvatarView';
import { useOnboardingFlowGuard } from '@/hooks/useOnboardingFlowGuard';
import { haptic } from '@/utils/haptics';
import {
  fontScale,
  responsiveBorderRadius,
  responsiveFontSize,
  responsivePadding,
  responsiveSpacing,
  scale,
  verticalScale,
} from '@/utils/scaling';
const BlurView = BlurViewFallback;
const LinearGradient = LinearGradientFallback;

type SexOption = IdentitySex;
type SexualityOption = IdentitySexuality;

interface SexOptionConfig {
  value: SexOption;
  label: string;
  icon: ImageSourcePropType;
}

interface SexualityOptionConfig {
  value: SexualityOption;
  label: string;
}

const SEX_OPTIONS: SexOptionConfig[] = [
  { value: 'male', label: 'Male', icon: require('@/assets/images/Sex/Male.png') },
  { value: 'female', label: 'Female', icon: require('@/assets/images/Sex/Female.png') },
  { value: 'random', label: 'Random', icon: require('@/assets/images/Sex/Dice.png') },
];

const SEXUALITY_OPTIONS: SexualityOptionConfig[] = [
  { value: 'straight', label: 'Straight' },
  { value: 'gay', label: 'Gay' },
  { value: 'bi', label: 'Bisexual' },
];

export default function Customize() {
  const router = useRouter();
  const navigation = useNavigation();
  const { state, setState } = useOnboarding();
  useOnboardingFlowGuard('Customize');

  useEffect(() => {
    logOnboardingStepView('Customize');
  }, []);

  const [firstName, setFirstName] = useState(state.firstName || '');
  const [lastName, setLastName] = useState(state.lastName || '');
  const [sex, setSex] = useState<SexOption>(state.sex || 'random');
  const [sexuality, setSexuality] = useState<SexualityOption>(state.sexuality || 'straight');
  // Layered avatar config — restore a saved draft or roll a fresh random one.
  const [avatarCfg, setAvatarCfg] = useState<PlayerAvatarConfig>(
    () => decodePlayerAvatarConfig(state.avatarId) ?? randomPlayerAvatarConfig(state.sex || 'random')
  );
  const lastAutoGeneratedSex = useRef<SexOption | null>(null);

  // Preview the avatar at the scenario's starting age so what you build is
  // what you'll see on day one (it still ages from there).
  const scenarioAge = state.scenario?.start?.age ?? 18;
  const avatarId = useMemo(() => encodePlayerAvatarConfig(avatarCfg), [avatarCfg]);

  // An explicit Male/Female pick must be reflected in the config (it carries
  // the resolved sex the rest of the game uses).
  useEffect(() => {
    if (sex !== 'random' && avatarCfg.sex !== sex) {
      setAvatarCfg(randomPlayerAvatarConfig(sex));
    }
  }, [sex, avatarCfg.sex]);

  // For "Random" the config's resolved sex wins — the name should follow the
  // character actually being created, not an independent coin flip.
  const nameSex: SexOption = sex === 'random' ? avatarCfg.sex : sex;

  const handleRandomizeAvatar = useCallback(() => {
    haptic.light();
    setAvatarCfg(randomPlayerAvatarConfig(sex));
  }, [sex]);

  const stepHairStyle = useCallback((direction: 1 | -1) => {
    haptic.selection();
    setAvatarCfg((prev) => {
      const index = Math.max(0, AVATAR_HAIRS.indexOf(prev.hair));
      const next = (index + direction + AVATAR_HAIRS.length) % AVATAR_HAIRS.length;
      return { ...prev, hair: AVATAR_HAIRS[next] };
    });
  }, []);

  useEffect(() => {
    if (!shouldGenerateInitialIdentityName(firstName, lastName)) {
      return;
    }

    const randomName = generateRandomName(nameSex);
    setFirstName(randomName.firstName);
    setLastName(randomName.lastName);
    lastAutoGeneratedSex.current = nameSex;
  }, [firstName, lastName, nameSex]);

  useEffect(() => {
    if (
      !shouldRegenerateIdentityNameForSexChange({
        sex: nameSex,
        firstName,
        lastName,
        lastAutoGeneratedSex: lastAutoGeneratedSex.current,
      })
    ) {
      return;
    }

    const randomName = generateRandomName(nameSex);
    setFirstName(randomName.firstName);
    setLastName(randomName.lastName);
    lastAutoGeneratedSex.current = nameSex;
  }, [firstName, lastName, nameSex]);

  const handleBack = useCallback(() => {
    if (navigation.canGoBack()) {
      router.back();
      return;
    }
    router.replace('/(onboarding)/MainMenu');
  }, [navigation, router]);

  // R3-C: wire the Android hardware back button to the same handler so a
  // system gesture / nav-bar back doesn't drop the player into a blank screen.
  useHardwareBack(() => {
    handleBack();
    return true;
  });

  const handleShuffle = useCallback(() => {
    haptic.light();
    const randomName = generateRandomName(nameSex);
    setFirstName(randomName.firstName);
    setLastName(randomName.lastName);
    lastAutoGeneratedSex.current = nameSex;
  }, [nameSex]);

  const handleFirstNameChange = useCallback((value: string) => {
    lastAutoGeneratedSex.current = null;
    setFirstName(value);
  }, []);

  const handleLastNameChange = useCallback((value: string) => {
    lastAutoGeneratedSex.current = null;
    setLastName(value);
  }, []);

  const handleContinue = useCallback(() => {
    if (!state.scenario) {
      haptic.error();
      Alert.alert('Missing Scenario', 'Choose a scenario before customizing identity.');
      router.replace('/(onboarding)/Scenarios');
      return;
    }

    if (!canContinueFromIdentityDraft({ firstName, lastName })) {
      haptic.error();
      Alert.alert('Missing Name', 'Enter both first and last name to continue.');
      return;
    }

    haptic.medium();
    const trimmedFirstName = firstName.trim();
    const trimmedLastName = lastName.trim();

    setState((prev) =>
      applyIdentityDraftToOnboardingState(prev, {
        firstName: trimmedFirstName,
        lastName: trimmedLastName,
        sex,
        sexuality,
        avatarId,
      })
    );
    router.push('/(onboarding)/Ambitions');
  }, [avatarId, firstName, lastName, router, setState, sex, sexuality, state.scenario]);

  const selectedSexLabel = useMemo(() => {
    return SEX_OPTIONS.find((option) => option.value === sex)?.label ?? sex;
  }, [sex]);

  const selectedSexualityLabel = useMemo(() => {
    return SEXUALITY_OPTIONS.find((option) => option.value === sexuality)?.label ?? sexuality;
  }, [sexuality]);

  return (
    <OnboardingScreenShellV2
      floatingButton={
        <OnboardingFloatingButton
          title="Continue To Ambitions"
          onPress={handleContinue}
          icon={<Play size={24} color="#FFFFFF" />}
        />
      }
    >
      <OnboardingGlassHeader
        title="Create Identity"
        onBack={handleBack}
        onInfo={() =>
          Alert.alert(
            'Create Your Identity',
            'Customize your character by choosing their name, sex, and sexuality. Use Shuffle to generate names instantly.'
          )
        }
      />

      <OnboardingStepBar currentStep={2} totalSteps={4} />

      <Text style={styles.guidanceText}>
        Name, sex, and sexuality only shape your story and relationships — not difficulty. Tap Shuffle for a random name.
      </Text>

      <ScrollView
        style={styles.scrollContainer}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={true}
      >
        {/* Appearance Section */}
        <View style={styles.sectionContainer}>
          <BlurView intensity={20} style={styles.sectionBlur}>
            <LinearGradient
              colors={['rgba(30, 41, 59, 0.9)', 'rgba(15, 23, 42, 0.8)']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={styles.sectionCard}
            >
              <Text style={styles.sectionTitle}>Appearance</Text>

              {/* Sex first — it drives which faces are offered below. */}
              <Text style={styles.fieldLabel}>Sex</Text>
              <View style={styles.sexRow}>
                {SEX_OPTIONS.map((option) => {
                  const isSelected = sex === option.value;
                  return (
                    <TouchableOpacity
                      key={option.value}
                      accessibilityRole="button"
                      accessibilityLabel={`${option.label} sex`}
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => {
                        haptic.selection();
                        setSex(option.value);
                      }}
                      style={[styles.sexCard, isSelected && styles.sexCardSelected]}
                    >
                      <Image source={option.icon} style={styles.sexIcon} />
                      <Text style={styles.sexLabel}>{option.label}</Text>
                    </TouchableOpacity>
                  );
                })}
              </View>

              {/* Avatar builder — build your face; it ages with you (hair greys
                  at 50, glasses at 65) while your choices persist. */}
              <Text style={styles.fieldLabel}>Build your face — it ages with you</Text>

              <View style={styles.avatarPreviewRow}>
                <PlayerAvatarView
                  avatarId={avatarId}
                  age={scenarioAge}
                  sex={avatarCfg.sex}
                  size={scale(104)}
                  style={styles.avatarPreview}
                />
                <TouchableOpacity
                  accessibilityRole="button"
                  accessibilityLabel="Randomize avatar"
                  onPress={handleRandomizeAvatar}
                  style={styles.randomizeButton}
                >
                  <Dices size={scale(16)} color="#60A5FA" />
                  <Text style={styles.randomizeLabel}>Randomize</Text>
                </TouchableOpacity>
              </View>

              {/* Skin tone */}
              <Text style={styles.builderLabel}>Skin Tone</Text>
              <View style={styles.swatchRow}>
                {AVATAR_SKIN_TONES.map((tone) => {
                  const isSelected = avatarCfg.skin === tone;
                  return (
                    <TouchableOpacity
                      key={tone}
                      accessibilityRole="button"
                      accessibilityLabel={`Skin tone ${tone}`}
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => {
                        haptic.selection();
                        setAvatarCfg((prev) => ({ ...prev, skin: tone }));
                      }}
                      style={[
                        styles.swatch,
                        { backgroundColor: `#${tone}` },
                        isSelected && styles.swatchSelected,
                      ]}
                    />
                  );
                })}
              </View>

              {/* Hair style stepper */}
              <Text style={styles.builderLabel}>Hair Style</Text>
              <View style={styles.stepperRow}>
                <TouchableOpacity
                  accessibilityRole="button"
                  accessibilityLabel="Previous hair style"
                  onPress={() => stepHairStyle(-1)}
                  style={styles.stepperButton}
                >
                  <ChevronLeft size={scale(18)} color="#60A5FA" />
                </TouchableOpacity>
                <Text style={styles.stepperLabel}>
                  Style {Math.max(0, AVATAR_HAIRS.indexOf(avatarCfg.hair)) + 1} / {AVATAR_HAIRS.length}
                </Text>
                <TouchableOpacity
                  accessibilityRole="button"
                  accessibilityLabel="Next hair style"
                  onPress={() => stepHairStyle(1)}
                  style={styles.stepperButton}
                >
                  <ChevronRight size={scale(18)} color="#60A5FA" />
                </TouchableOpacity>
              </View>

              {/* Hair color */}
              <Text style={styles.builderLabel}>Hair Color</Text>
              <View style={styles.swatchRow}>
                {AVATAR_HAIR_COLORS.map((color) => {
                  const isSelected = avatarCfg.hairColor === color;
                  return (
                    <TouchableOpacity
                      key={color}
                      accessibilityRole="button"
                      accessibilityLabel={`Hair color ${color}`}
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => {
                        haptic.selection();
                        setAvatarCfg((prev) => ({ ...prev, hairColor: color }));
                      }}
                      style={[
                        styles.swatch,
                        { backgroundColor: `#${color}` },
                        isSelected && styles.swatchSelected,
                      ]}
                    />
                  );
                })}
              </View>

              {/* Glasses */}
              <TouchableOpacity
                accessibilityRole="button"
                accessibilityLabel="Toggle glasses"
                accessibilityState={{ selected: avatarCfg.glasses === true }}
                onPress={() => {
                  haptic.selection();
                  setAvatarCfg((prev) => ({ ...prev, glasses: !prev.glasses }));
                }}
                style={[styles.glassesChip, avatarCfg.glasses && styles.glassesChipSelected]}
              >
                <Glasses size={scale(14)} color={avatarCfg.glasses ? '#FFFFFF' : '#94A3B8'} />
                <Text style={[styles.glassesLabel, avatarCfg.glasses && styles.glassesLabelSelected]}>
                  Glasses
                </Text>
              </TouchableOpacity>
            </LinearGradient>
          </BlurView>
        </View>

        {/* Name Section */}
        <View style={styles.sectionContainer}>
          <BlurView intensity={20} style={styles.sectionBlur}>
            <LinearGradient
              colors={['rgba(30, 41, 59, 0.9)', 'rgba(15, 23, 42, 0.8)']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={styles.sectionCard}
            >
              <View style={styles.sectionHeader}>
                <Text style={styles.sectionTitle}>Name</Text>
                <TouchableOpacity
                  accessibilityLabel="Shuffle name"
                  onPress={handleShuffle}
                  style={styles.shuffleButton}
                >
                  <Shuffle size={scale(16)} color="#60A5FA" />
                  <Text style={styles.shuffleLabel}>Shuffle</Text>
                </TouchableOpacity>
              </View>

              <View style={styles.nameRow}>
                <View style={styles.nameField}>
                  <Text style={styles.inputLabel}>First Name</Text>
                  <View style={styles.inputWrap}>
                    <TextInput
                      placeholder="Enter first name"
                      placeholderTextColor="#94A3B8"
                      style={styles.inputText}
                      value={firstName}
                      onChangeText={handleFirstNameChange}
                    />
                  </View>
                </View>

                <View style={styles.nameField}>
                  <Text style={styles.inputLabel}>Last Name</Text>
                  <View style={styles.inputWrap}>
                    <TextInput
                      placeholder="Enter last name"
                      placeholderTextColor="#94A3B8"
                      style={styles.inputText}
                      value={lastName}
                      onChangeText={handleLastNameChange}
                    />
                  </View>
                </View>
              </View>
            </LinearGradient>
          </BlurView>
        </View>

        {/* Sexuality Section */}
        <View style={styles.sectionContainer}>
          <BlurView intensity={20} style={styles.sectionBlur}>
            <LinearGradient
              colors={['rgba(30, 41, 59, 0.9)', 'rgba(15, 23, 42, 0.8)']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={styles.sectionCard}
            >
              <Text style={styles.sectionTitle}>Sexuality</Text>
              <View style={styles.sexualityRow}>
                {SEXUALITY_OPTIONS.map((option) => {
                  const isSelected = sexuality === option.value;
                  return (
                    <TouchableOpacity
                      key={option.value}
                      accessibilityRole="button"
                      accessibilityState={{ selected: isSelected }}
                      onPress={() => { haptic.selection(); setSexuality(option.value); }}
                      style={[
                        styles.sexualityChip,
                        isSelected && styles.sexualityChipSelected,
                      ]}
                    >
                      <Text style={[styles.sexualityLabel, isSelected && styles.sexualityLabelSelected]}>
                        {option.label}
                      </Text>
                    </TouchableOpacity>
                  );
                })}
              </View>
            </LinearGradient>
          </BlurView>
        </View>

        <View style={{ height: 140 }} />
      </ScrollView>
    </OnboardingScreenShellV2>
  );
}

const styles = StyleSheet.create({
  guidanceText: {
    fontSize: fontScale(13),
    fontWeight: '500',
    color: '#94A3B8',
    textAlign: 'center',
    paddingHorizontal: responsivePadding.large,
    paddingBottom: responsiveSpacing.xs,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    gap: responsiveSpacing.lg,
    paddingHorizontal: responsivePadding.large,
    paddingTop: responsiveSpacing.sm,
    paddingBottom: responsiveSpacing.lg,
  },
  sectionContainer: {
    borderRadius: 16,
    overflow: 'hidden',
    ...Platform.select({
      web: { boxShadow: '0px 8px 16px rgba(0, 0, 0, 0.3)' } as any,
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
      },
    }),
    elevation: 12,
  },
  sectionBlur: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  sectionCard: {
    padding: 20,
    // Match the parent's rounded clip so the white border doesn't get sliced
    // off at the corners (square border inside an overflow:hidden rounded box).
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    gap: responsiveSpacing.md,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: responsiveFontSize.xl,
    fontWeight: '800',
    color: '#FFFFFF',
    ...Platform.select({
      web: { textShadow: '1px 1px 3px rgba(0, 0, 0, 0.5)' } as any,
      default: {
        textShadowColor: 'rgba(0, 0, 0, 0.5)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
      },
    }),
  },
  shuffleButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: responsiveBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    flexDirection: 'row',
    gap: responsiveSpacing.xs,
    paddingHorizontal: responsiveSpacing.sm,
    paddingVertical: verticalScale(7),
  },
  shuffleLabel: {
    fontSize: fontScale(11),
    fontWeight: '700',
    color: '#60A5FA',
  },
  nameRow: {
    gap: responsiveSpacing.sm,
  },
  nameField: {
    gap: responsiveSpacing.xs,
  },
  inputLabel: {
    fontSize: fontScale(11),
    fontWeight: '600',
    color: '#94A3B8',
  },
  inputWrap: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    minHeight: verticalScale(44),
    justifyContent: 'center',
    paddingHorizontal: responsiveSpacing.sm,
  },
  inputText: {
    fontSize: fontScale(14),
    fontWeight: '600',
    color: '#FFFFFF',
  },
  sexRow: {
    flexDirection: 'row',
    gap: responsiveSpacing.sm,
  },
  sexCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    flex: 1,
    gap: responsiveSpacing.xs,
    justifyContent: 'center',
    minHeight: verticalScale(108),
    paddingHorizontal: responsiveSpacing.xs,
    paddingVertical: verticalScale(12),
  },
  sexCardSelected: {
    borderColor: 'rgba(96, 165, 250, 0.85)',
    borderWidth: 2,
    backgroundColor: 'rgba(59, 130, 246,0.15)',
  },
  sexIcon: {
    borderRadius: responsiveBorderRadius.md,
    height: scale(30),
    width: scale(30),
  },
  sexLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    color: '#FFFFFF',
  },
  sexualityRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: responsiveSpacing.sm,
  },
  sexualityChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    minWidth: scale(92),
    paddingHorizontal: responsiveSpacing.md,
    paddingVertical: verticalScale(10),
  },
  sexualityChipSelected: {
    borderColor: 'rgba(96, 165, 250, 0.85)',
    borderWidth: 2,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  sexualityLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    textAlign: 'center',
    color: '#CBD5E1',
  },
  sexualityLabelSelected: {
    color: '#FFFFFF',
  },
  fieldLabel: {
    fontSize: fontScale(11),
    fontWeight: '700',
    color: '#94A3B8',
    marginTop: responsiveSpacing.xs,
    marginBottom: verticalScale(6),
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  avatarPreviewRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: responsiveSpacing.md,
    paddingVertical: responsiveSpacing.xs,
  },
  avatarPreview: {
    borderWidth: 2,
    borderColor: 'rgba(96, 165, 250, 0.5)',
  },
  randomizeButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: responsiveBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    flexDirection: 'row',
    gap: responsiveSpacing.xs,
    paddingHorizontal: responsiveSpacing.md,
    paddingVertical: verticalScale(9),
  },
  randomizeLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    color: '#60A5FA',
  },
  builderLabel: {
    fontSize: fontScale(10),
    fontWeight: '700',
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginTop: responsiveSpacing.xs,
  },
  swatchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: responsiveSpacing.sm,
  },
  swatch: {
    width: scale(30),
    height: scale(30),
    borderRadius: scale(15),
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  swatchSelected: {
    borderColor: '#60A5FA',
    borderWidth: 3,
  },
  stepperRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: responsiveSpacing.sm,
  },
  stepperButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: responsiveBorderRadius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    height: verticalScale(36),
    width: scale(44),
  },
  stepperLabel: {
    flex: 1,
    fontSize: fontScale(12),
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  glassesChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: responsiveBorderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    flexDirection: 'row',
    gap: responsiveSpacing.xs,
    paddingHorizontal: responsiveSpacing.md,
    paddingVertical: verticalScale(8),
  },
  glassesChipSelected: {
    borderColor: 'rgba(96, 165, 250, 0.85)',
    borderWidth: 2,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  glassesLabel: {
    fontSize: fontScale(12),
    fontWeight: '700',
    color: '#94A3B8',
  },
  glassesLabelSelected: {
    color: '#FFFFFF',
  },
});
