import { CompanyUpgrade } from './types';

/**
 * Canonical company-upgrade catalog — the single source of truth for every
 * company type's upgrades (id, name, description, cost, weeklyIncomeBonus,
 * maxLevel). Previously this table was copy-pasted into createCompany,
 * buyCompanyUpgrade (twice), sellCompany, and the simulator; the duplicates
 * had already drifted into different field projections, so a cost/bonus change
 * had to be made in five places to stay consistent. Import this instead.
 */
export const COMPANY_UPGRADES: Record<string, CompanyUpgrade[]> = {
    factory: [
      {
        id: 'machinery',
        name: 'Better Machinery',
        description: 'Increase production efficiency',
        cost: 10000,
        weeklyIncomeBonus: 500,
        level: 0,
        maxLevel: 5,
      },
      {
        id: 'workers',
        name: 'More Workers',
        description: 'Hire additional staff',
        cost: 15000,
        weeklyIncomeBonus: 800,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'automation',
        name: 'Assembly Line',
        description: 'Automated production line',
        cost: 25000,
        weeklyIncomeBonus: 1200,
        level: 0,
        maxLevel: 4,
      },
      {
        id: 'quality_control',
        name: 'Quality Control',
        description: 'Advanced quality assurance',
        cost: 20000,
        weeklyIncomeBonus: 1000,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'warehouse',
        name: 'Smart Warehouse',
        description: 'Automated inventory management',
        cost: 30000,
        weeklyIncomeBonus: 1500,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'safety',
        name: 'Safety Systems',
        description: 'Workplace safety improvements',
        cost: 18000,
        weeklyIncomeBonus: 800,
        level: 0,
        maxLevel: 4,
      },
    ],
    ai: [
      {
        id: 'servers',
        name: 'Better Servers',
        description: 'Upgrade computing power',
        cost: 25000,
        weeklyIncomeBonus: 1200,
        level: 0,
        maxLevel: 4,
      },
      {
        id: 'algorithms',
        name: 'Advanced Algorithms',
        description: 'Improve AI capabilities',
        cost: 30000,
        weeklyIncomeBonus: 1500,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'gpu_cluster',
        name: 'GPU Cluster',
        description: 'Faster AI training',
        cost: 50000,
        weeklyIncomeBonus: 2500,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'data_center',
        name: 'Data Center',
        description: 'Scale operations',
        cost: 75000,
        weeklyIncomeBonus: 3500,
        level: 0,
        maxLevel: 2,
      },
      {
        id: 'ai_researchers',
        name: 'AI Researchers',
        description: 'Cutting-edge research team',
        cost: 40000,
        weeklyIncomeBonus: 2000,
        level: 0,
        maxLevel: 4,
      },
      {
        id: 'machine_learning',
        name: 'ML Platform',
        description: 'Machine learning infrastructure',
        cost: 60000,
        weeklyIncomeBonus: 3000,
        level: 0,
        maxLevel: 3,
      },
    ],
    restaurant: [
      {
        id: 'kitchen',
        name: 'Kitchen Upgrade',
        description: 'Modernize kitchen equipment',
        cost: 20000,
        weeklyIncomeBonus: 1000,
        level: 0,
        maxLevel: 4,
      },
      {
        id: 'staff',
        name: 'Professional Staff',
        description: 'Hire experienced chefs',
        cost: 18000,
        weeklyIncomeBonus: 900,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'delivery_service',
        name: 'Delivery Service',
        description: 'Expand customer reach',
        cost: 25000,
        weeklyIncomeBonus: 1200,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'michelin_chef',
        name: 'Michelin Chef',
        description: 'Premium dining experience',
        cost: 40000,
        weeklyIncomeBonus: 2000,
        level: 0,
        maxLevel: 2,
      },
      {
        id: 'interior_design',
        name: 'Interior Design',
        description: 'Upscale dining atmosphere',
        cost: 30000,
        weeklyIncomeBonus: 1500,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'wine_cellar',
        name: 'Wine Cellar',
        description: 'Premium wine selection',
        cost: 35000,
        weeklyIncomeBonus: 1800,
        level: 0,
        maxLevel: 2,
      },
    ],
    realestate: [
      {
        id: 'properties',
        name: 'More Properties',
        description: 'Expand property portfolio',
        cost: 50000,
        weeklyIncomeBonus: 2000,
        level: 0,
        maxLevel: 5,
      },
      {
        id: 'management',
        name: 'Property Management',
        description: 'Improve property management',
        cost: 30000,
        weeklyIncomeBonus: 1500,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'property_portfolio',
        name: 'Property Portfolio',
        description: 'More rental properties',
        cost: 75000,
        weeklyIncomeBonus: 3000,
        level: 0,
        maxLevel: 4,
      },
      {
        id: 'commercial_real_estate',
        name: 'Commercial Properties',
        description: 'Higher value investments',
        cost: 100000,
        weeklyIncomeBonus: 4000,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'property_management',
        name: 'Property Management',
        description: 'Professional management',
        cost: 40000,
        weeklyIncomeBonus: 2000,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'luxury_developments',
        name: 'Luxury Developments',
        description: 'High-end property development',
        cost: 150000,
        weeklyIncomeBonus: 6000,
        level: 0,
        maxLevel: 2,
      },
    ],
    bank: [
      {
        id: 'technology',
        name: 'Banking Technology',
        description: 'Upgrade banking systems',
        cost: 100000,
        weeklyIncomeBonus: 5000,
        level: 0,
        maxLevel: 4,
      },
      {
        id: 'services',
        name: 'Financial Services',
        description: 'Expand financial services',
        cost: 80000,
        weeklyIncomeBonus: 4000,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'investment_division',
        name: 'Investment Division',
        description: 'Wealth management services',
        cost: 200000,
        weeklyIncomeBonus: 10000,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'international_banking',
        name: 'International Banking',
        description: 'Global operations',
        cost: 300000,
        weeklyIncomeBonus: 15000,
        level: 0,
        maxLevel: 2,
      },
      {
        id: 'fintech_integration',
        name: 'FinTech Integration',
        description: 'Digital banking solutions',
        cost: 150000,
        weeklyIncomeBonus: 7500,
        level: 0,
        maxLevel: 3,
      },
      {
        id: 'private_banking',
        name: 'Private Banking',
        description: 'Exclusive client services',
        cost: 250000,
        weeklyIncomeBonus: 12000,
        level: 0,
        maxLevel: 2,
      },
    ],
};

/** Uniform per-level cost growth applied to every company upgrade. */
export const COMPANY_UPGRADE_COST_MULTIPLIER = 1.5;
