import { GameState, LifeStage } from './types';
import { defaultPrestigeData } from '@/lib/prestige/prestigeTypes';

export const STATE_VERSION = 10;

const getLifeStage = (age: number): LifeStage => {
  if (age < 13) return 'child';
  if (age < 20) return 'teen';
  if (age < 65) return 'adult';
  return 'senior';
};

export const initialGameState: GameState = {
  version: STATE_VERSION,
  revivalPack: false,
  stats: {
    health: 100,
    happiness: 100,
    energy: 100,
    fitness: 10,
    money: 200,
    reputation: 0,
    gems: 0,
  },
  bankSavings: 0,
  totalHappiness: 0,
  weeksLived: 0,
  wantedLevel: 0,
  jailWeeks: 0,
  escapedFromJail: false,
  criminalXp: 0,
  weeklyJailActivities: {},
  weeklyStreetJobs: {},
  criminalLevel: 1,
  youthPills: 0,
  petFood: {}, // Pet food inventory: { 'basic': 0, 'premium': 0, 'luxury': 0 }
  vehicles: [], // Player's owned vehicles
  activeVehicleId: undefined, // Currently selected vehicle
  unlockedLifeSkills: [], // Life skills from SkillTreeModal
  dmConversations: [], // DM conversations in Social App
  revealedDMClues: [], // Revealed clues from DM system
  crimeSkills: {
    stealth: { xp: 0, level: 1, upgrades: [] },
    hacking: { xp: 0, level: 1, upgrades: [] },
    lockpicking: { xp: 0, level: 1, upgrades: [] },
  },
  mindset: {
    traits: [],
    activeTraitId: undefined,
  },
  generationNumber: 1,
  lineageId: 'initial-lineage', // will be replaced with a UUID on first load
  ancestors: [],
  activeTraits: [],
  memories: [],
  previousLives: [],
  legacyBonuses: {
    incomeMultiplier: 1,
    learningMultiplier: 1,
    reputationBonus: 0,
  },
  week: 1,
  date: { year: 2025, month: 'January', week: 1, age: 18 },
  streetJobs: [
    {
      id: 'beg',
      name: 'Beg for Money',
      description: '30% chance to get money, small chance to be robbed',
      energyCost: 20,
      baseSuccessRate: 30,
      basePayment: 100,
      rank: 1,
      progress: 0,
      risks: ['robbery'],
    },
    {
      id: 'dumpster',
      name: 'Dumpster Dive',
      description: '20% chance for money, rare chance for items',
      energyCost: 15,
      baseSuccessRate: 20,
      basePayment: 120,
      rank: 1,
      progress: 0,
    },
    {
      id: 'delivery',
      name: 'Delivery Cycle',
      description: '90% success rate, requires bike',
      energyCost: 30,
      baseSuccessRate: 90,
      basePayment: 180,
      rank: 1,
      progress: 0,
      requirements: ['bike'],
    },
    {
      id: 'steal_from_cars',
      name: 'Find Lost Items',
      description: 'Check around for lost or abandoned items. No requirements needed.',
      energyCost: 15,
      baseSuccessRate: 70,
      basePayment: 35,
      rank: 1,
      progress: 0,
      skill: 'stealth',
      illegal: true,
      wantedIncrease: 1,
      jailWeeks: 1,
    },
    {
      id: 'pickpocket_basic',
      name: 'Street Hustle',
      description: 'Use sleight of hand tricks for profit. Requires special gloves.',
      energyCost: 10,
      baseSuccessRate: 70,
      basePayment: 40,
      rank: 1,
      progress: 0,
      skill: 'stealth',
      illegal: true,
      darkWebRequirements: ['gloves'],
      wantedIncrease: 1,
      jailWeeks: 1,
    },
    {
      id: 'hack_public_wifi',
      name: 'Network Testing',
      description: 'Test public WiFi network security. Requires USB tools.',
      energyCost: 20,
      baseSuccessRate: 65,
      basePayment: 60,
      rank: 1,
      progress: 0,
      skill: 'hacking',
      illegal: true,
      darkWebRequirements: ['usb'],
      wantedIncrease: 1,
      jailWeeks: 1,
    },
    {
      id: 'drug_dealing',
      name: 'Street Vending',
      description: 'Sell items on the street without proper permits. Requires vendor supplies.',
      energyCost: 35,
      baseSuccessRate: 65,
      basePayment: 150,
      rank: 1,
      progress: 0,
      skill: 'stealth',
      illegal: true,
      darkWebRequirements: ['drug_supply'],
      wantedIncrease: 2,
      jailWeeks: 2,
    },
    {
      id: 'steal_cars_basic',
      name: 'Vehicle Acquisition',
      description: 'Acquire vehicles through unofficial channels. Requires lockpicking tools.',
      energyCost: 35,
      baseSuccessRate: 60,
      basePayment: 400,
      rank: 1,
      progress: 0,
      skill: 'lockpicking',
      illegal: true,
      criminalLevelReq: 1,
      darkWebRequirements: ['lockpick', 'slim_jim'],
      wantedIncrease: 3,
      jailWeeks: 3,
    },
    {
      id: 'panhandle',
      name: 'Panhandle',
      description: 'Ask strangers for money. Low risk but low reward.',
      energyCost: 5,
      baseSuccessRate: 60,
      basePayment: 60,
      rank: 1,
      progress: 0,
      skill: 'stealth',
      illegal: false,
    },
    {
      id: 'wash_cars',
      name: 'Wash Cars',
      description: 'Offer to wash cars for money. Honest work.',
      energyCost: 20,
      baseSuccessRate: 90,
      basePayment: 140,
      rank: 1,
      progress: 0,
    },
    {
      id: 'sell_water',
      name: 'Sell Water',
      description: 'Buy water bottles and sell them for profit.',
      energyCost: 15,
      baseSuccessRate: 75,
      basePayment: 80,
      rank: 1,
      progress: 0,
    },
    {
      id: 'food_delivery',
      name: 'Food Delivery',
      description: 'Deliver food orders using your bike. Fast and profitable.',
      energyCost: 25,
      baseSuccessRate: 85,
      basePayment: 200,
      rank: 1,
      progress: 0,
      requirements: ['bike'],
    },
    {
      id: 'dog_walking',
      name: 'Dog Walking',
      description: 'Walk dogs in the neighborhood. Relaxing but tiring.',
      energyCost: 30,
      baseSuccessRate: 95,
      basePayment: 150,
      rank: 1,
      progress: 0,
    },
    {
      id: 'lawn_mowing',
      name: 'Lawn Mowing',
      description: 'Mow lawns for money. Hard work in the sun.',
      energyCost: 35,
      baseSuccessRate: 90,
      basePayment: 220,
      rank: 1,
      progress: 0,
    },
    {
      id: 'flyer_distribution',
      name: 'Flyer Distribution',
      description: 'Hand out flyers around town. Easy but time-consuming.',
      energyCost: 20,
      baseSuccessRate: 100,
      basePayment: 110,
      rank: 1,
      progress: 0,
    },
    {
      id: 'tutoring',
      name: 'Street Tutoring',
      description: 'Help kids with homework. Requires good knowledge.',
      energyCost: 25,
      baseSuccessRate: 80,
      basePayment: 190,
      rank: 1,
      progress: 0,
    },
    {
      id: 'recycling',
      name: 'Collect Recyclables',
      description: 'Gather cans and bottles for recycling money.',
      energyCost: 30,
      baseSuccessRate: 70,
      basePayment: 130,
      rank: 1,
      progress: 0,
    },
    {
      id: 'car_theft',
      name: 'Vehicle Relocation',
      description: 'Relocate vehicles for profit. Requires specialized tools.',
      energyCost: 40,
      baseSuccessRate: 50,
      basePayment: 500,
      rank: 1,
      progress: 0,
      skill: 'lockpicking',
      illegal: true,
      criminalLevelReq: 2,
      darkWebRequirements: ['lockpick', 'slim_jim'],
      wantedIncrease: 3,
      jailWeeks: 3,
    },
    {
      id: 'bank_heist',
      name: 'High-Stakes Scheme',
      description: 'Attempt a complex financial scheme. Requires advanced tools and planning.',
      energyCost: 60,
      baseSuccessRate: 20,
      basePayment: 15000,
      rank: 1,
      progress: 0,
      skill: 'stealth',
      illegal: true,
      criminalLevelReq: 3,
      darkWebRequirements: ['drill_kit', 'explosives'],
      wantedIncrease: 3,
      jailWeeks: 4,
    },
    {
      id: 'burglary',
      name: 'Property Acquisition',
      description: 'Acquire items through questionable means. Requires lockpicking skills.',
      energyCost: 35,
      baseSuccessRate: 45,
      basePayment: 300,
      rank: 1,
      progress: 0,
      skill: 'lockpicking',
      illegal: true,
      criminalLevelReq: 2,
      darkWebRequirements: ['lockpick', 'crowbar'],
      wantedIncrease: 3,
      jailWeeks: 3,
    },
    {
      id: 'cyber_attack',
      name: 'Security Testing',
      description: 'Test network security for profit. Requires security tools and VPN.',
      energyCost: 30,
      baseSuccessRate: 50,
      basePayment: 600,
      rank: 1,
      progress: 0,
      skill: 'hacking',
      illegal: true,
      criminalLevelReq: 2,
      darkWebRequirements: ['malware_kit', 'vpn'],
      risks: ['trace'],
      wantedIncrease: 2,
      jailWeeks: 3,
    },
    {
      id: 'identity_theft',
      name: 'Identity Theft',
      description: 'Steal personal data to sell on the dark web. Requires VPN.',
      energyCost: 35,
      baseSuccessRate: 55,
      basePayment: 800,
      rank: 1,
      progress: 0,
      skill: 'hacking',
      illegal: true,
      criminalLevelReq: 3,
      darkWebRequirements: ['vpn'],
      wantedIncrease: 3,
      jailWeeks: 3,
    },
    {
      id: 'steal_phones',
      name: 'Steal Phones',
      description: 'Steal smartphones from people. Requires Stealth Gloves.',
      energyCost: 20,
      baseSuccessRate: 70,
      basePayment: 120,
      rank: 1,
      progress: 0,
      skill: 'stealth',
      illegal: true,
      criminalLevelReq: 1,
      darkWebRequirements: ['gloves'],
      wantedIncrease: 2,
      jailWeeks: 2,
    },
    {
      id: 'smuggling',
      name: 'Smuggling',
      description: 'Transport contraband across town. Requires Bike and Night Vision Goggles.',
      energyCost: 45,
      baseSuccessRate: 40,
      basePayment: 1000,
      rank: 1,
      progress: 0,
      skill: 'stealth',
      illegal: true,
      criminalLevelReq: 3,
      requirements: ['bike'],
      darkWebRequirements: ['night_vision'],
      wantedIncrease: 3,
      jailWeeks: 4,
    },
    {
      id: 'steal_laptops',
      name: 'Steal Laptops',
      description: 'Steal laptops from cafes and libraries. Requires Stealth Gloves.',
      energyCost: 25,
      baseSuccessRate: 65,
      basePayment: 200,
      rank: 1,
      progress: 0,
      skill: 'stealth',
      illegal: true,
      criminalLevelReq: 1,
      darkWebRequirements: ['gloves'],
      wantedIncrease: 2,
      jailWeeks: 2,
    },
    {
      id: 'assassination',
      name: 'Elite Contract',
      description: 'Complete high-risk contracts. Requires Stealth Equipment and Night Vision Goggles.',
      energyCost: 80,
      baseSuccessRate: 25,
      basePayment: 20000,
      rank: 1,
      progress: 0,
      skill: 'stealth',
      illegal: true,
      criminalLevelReq: 5,
      darkWebRequirements: ['silencer', 'night_vision'],
      wantedIncrease: 5,
      jailWeeks: 6,
    },
    {
      id: 'cyber_espionage',
      name: 'Cyber Espionage',
      description: 'Steal corporate secrets. Requires Malware Kit, VPN, and Encryption Suite.',
      energyCost: 50,
      baseSuccessRate: 35,
      basePayment: 6000,
      rank: 1,
      progress: 0,
      skill: 'hacking',
      illegal: true,
      criminalLevelReq: 4,
      darkWebRequirements: ['malware_kit', 'vpn', 'encryption'],
      wantedIncrease: 4,
      jailWeeks: 5,
    },
    {
      id: 'steal_jewelry',
      name: 'Steal Jewelry',
      description: 'Steal jewelry from stores. Requires Lockpick and Crowbar.',
      energyCost: 30,
      baseSuccessRate: 55,
      basePayment: 300,
      rank: 1,
      progress: 0,
      skill: 'lockpicking',
      illegal: true,
      criminalLevelReq: 2,
      darkWebRequirements: ['lockpick', 'crowbar'],
      wantedIncrease: 3,
      jailWeeks: 3,
    },
    {
      id: 'hack_atm',
      name: 'Hack ATM',
      description: 'Hack ATMs for cash. Requires Wireless Hack Device.',
      energyCost: 40,
      baseSuccessRate: 40,
      basePayment: 800,
      rank: 1,
      progress: 0,
      skill: 'hacking',
      illegal: true,
      criminalLevelReq: 2,
      darkWebRequirements: ['wireless_hack'],
      wantedIncrease: 3,
      jailWeeks: 3,
    },
    {
      id: 'steal_safe',
      name: 'Steal Safe',
      description: 'Steal safes from homes. Requires Thermal Vision Goggles.',
      energyCost: 50,
      baseSuccessRate: 35,
      basePayment: 1200,
      rank: 1,
      progress: 0,
      skill: 'lockpicking',
      illegal: true,
      criminalLevelReq: 3,
      darkWebRequirements: ['thermal_vision'],
      wantedIncrease: 3,
      jailWeeks: 3,
    },
    {
      id: 'disable_security',
      name: 'Disable Security',
      description: 'Disable security systems. Requires EMP Device.',
      energyCost: 45,
      baseSuccessRate: 45,
      basePayment: 1000,
      rank: 1,
      progress: 0,
      skill: 'hacking',
      illegal: true,
      criminalLevelReq: 3,
      darkWebRequirements: ['emp_device'],
      wantedIncrease: 3,
      jailWeeks: 3,
    },
  ],
  jailActivities: [
    {
      id: 'prison_job',
      name: 'Prison Job',
      description: 'Work in the prison kitchen or laundry for small pay and reduced sentence.',
      energyCost: 20,
      payment: 25,
      sentenceReduction: 1,
    },
    {
      id: 'library_study',
      name: 'Library Study',
      description: 'Study in the prison library to improve your mind and reduce stress.',
      energyCost: 15,
      happinessGain: 8,
      reputationGain: 2,
    },
    {
      id: 'prison_workshop',
      name: 'Prison Workshop',
      description: 'Learn a trade in the prison workshop for better pay.',
      energyCost: 25,
      payment: 40,
      sentenceReduction: 1,
      skillGain: 'crafting',
    },
    {
      id: 'legal_appeal',
      name: 'Legal Appeal',
      description: 'File a legal appeal for early release. Requires legal knowledge.',
      energyCost: 20,
      cost: 500,
      successRate: 0.4,
      requiresEducation: 'law_degree',
    },
    {
      id: 'good_behavior',
      name: 'Good Behavior',
      description: 'Maintain perfect behavior for sentence reduction.',
      energyCost: 5,
      happinessGain: 10,
      sentenceReduction: 1,
      requiresWeeks: 2,
    },
    {
      id: 'prison_meditation',
      name: 'Prison Meditation',
      description: 'Find inner peace through meditation. Reduces stress and improves mental clarity.',
      energyCost: 5,
      happinessGain: 8,
      healthGain: 3,
    },
    {
      id: 'prison_exercise',
      name: 'Prison Exercise',
      description: 'Work out in the yard to build strength and maintain physical health.',
      energyCost: 20,
      healthGain: 8,
      fitnessGain: 5,
      happinessGain: 5,
    },
    {
      id: 'prison_yoga',
      name: 'Prison Yoga',
      description: 'Practice yoga for flexibility, balance, and mental well-being.',
      energyCost: 10,
      healthGain: 5,
      happinessGain: 10,
      fitnessGain: 2,
    },
  ],
  careers: [
    {
      id: 'fast_food',
      levels: [
        { name: 'Fast Food Worker', salary: 30 },
        { name: 'Crew Member', salary: 40 },
        { name: 'Shift Leader', salary: 55 },
        { name: 'Assistant Manager', salary: 70 },
        { name: 'Restaurant Manager', salary: 85 },
        { name: 'District Manager', salary: 110 },
      ],
      level: 0,
      description: 'Flip burgers in a fast-food restaurant',
      requirements: {},
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'retail',
      levels: [
        { name: 'Retail Associate', salary: 55 },
        { name: 'Senior Associate', salary: 70 },
        { name: 'Floor Supervisor', salary: 85 },
        { name: 'Assistant Manager', salary: 100 },
        { name: 'Store Manager', salary: 125 },
        { name: 'Regional Manager', salary: 155 },
      ],
      level: 0,
      description: 'Assist customers and manage inventory in retail',
      requirements: {},
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'janitor',
      levels: [
        { name: 'Janitor', salary: 35 },
        { name: 'Senior Janitor', salary: 45 },
        { name: 'Maintenance Lead', salary: 55 },
        { name: 'Maintenance Supervisor', salary: 70 },
        { name: 'Facility Manager', salary: 85 },
        { name: 'Facilities Director', salary: 105 },
      ],
      level: 0,
      description: 'Keep buildings clean and operational',
      requirements: {},
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'teacher',
      levels: [
        { name: 'Teaching Assistant', salary: 220 },
        { name: 'Substitute Teacher', salary: 280 },
        { name: 'School Teacher', salary: 340 },
        { name: 'Senior Teacher', salary: 400 },
        { name: 'Department Head', salary: 480 },
        { name: 'Principal', salary: 600 },
      ],
      level: 0,
      description: 'Educate the next generation',
      requirements: { education: ['business_degree'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'nurse',
      levels: [
        { name: 'Nursing Assistant', salary: 300 },
        { name: 'LPN', salary: 360 },
        { name: 'Registered Nurse', salary: 420 },
        { name: 'Senior Nurse', salary: 480 },
        { name: 'Nurse Practitioner', salary: 580 },
        { name: 'Nurse Manager', salary: 700 },
      ],
      level: 0,
      description: 'Provide healthcare services',
      requirements: { fitness: 40, education: ['business_degree'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'software',
      levels: [
        { name: 'Junior Developer', salary: 1100 },
        { name: 'Developer', salary: 1400 },
        { name: 'Software Engineer', salary: 1700 },
        { name: 'Senior Engineer', salary: 2000 },
        { name: 'Lead Engineer', salary: 2400 },
        { name: 'Engineering Manager', salary: 3000 },
      ],
      level: 0,
      description: 'Develop software applications',
      requirements: { items: ['computer'], education: ['masters_degree'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'doctor',
      levels: [
        { name: 'Medical Intern', salary: 1700 },
        { name: 'Resident Doctor', salary: 2200 },
        { name: 'Senior Resident', salary: 2700 },
        { name: 'Medical Doctor', salary: 3200 },
        { name: 'Senior Doctor', salary: 3800 },
        { name: 'Chief of Medicine', salary: 4800 },
      ],
      level: 0,
      description: 'Practice medicine and heal patients',
      requirements: { education: ['phd'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'lawyer',
      levels: [
        { name: 'Paralegal', salary: 1400 },
        { name: 'Junior Associate', salary: 1750 },
        { name: 'Associate Lawyer', salary: 2100 },
        { name: 'Senior Associate', salary: 2600 },
        { name: 'Senior Lawyer', salary: 3100 },
        { name: 'Partner', salary: 4000 },
      ],
      level: 0,
      description: 'Practice law and represent clients',
      requirements: { items: ['suit'], education: ['legal_studies', 'masters_degree'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'corporate',
      levels: [
        { name: 'Business Intern', salary: 1750 },
        { name: 'Analyst', salary: 2400 },
        { name: 'Senior Analyst', salary: 3000 },
        { name: 'Manager', salary: 3600 },
        { name: 'Senior Manager', salary: 4800 },
        { name: 'CEO', salary: 6000 },
      ],
      level: 0,
      description: 'Climb the corporate ladder',
      requirements: { items: ['suit', 'computer'], education: ['mba'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'police',
      levels: [
        { name: 'Police Cadet', salary: 150 },
        { name: 'Police Officer', salary: 230 },
        { name: 'Senior Officer', salary: 290 },
        { name: 'Sergeant', salary: 350 },
        { name: 'Lieutenant', salary: 430 },
        { name: 'Captain', salary: 550 },
      ],
      level: 0,
      description: 'Protect and serve the community',
      requirements: { fitness: 50, education: ['police_academy'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'legal',
      levels: [
        { name: 'Junior Legal Assistant', salary: 130 },
        { name: 'Legal Assistant', salary: 190 },
        { name: 'Senior Legal Assistant', salary: 270 },
      ],
      level: 0,
      description: 'Support legal professionals',
      requirements: { items: ['smartphone', 'computer'], education: ['legal_studies'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'bank',
      levels: [
        { name: 'Bank Teller', salary: 230 },
        { name: 'Loan Officer', salary: 350 },
        { name: 'Bank Manager', salary: 510 },
      ],
      level: 0,
      description: 'Manage banking operations',
      requirements: { items: ['smartphone', 'computer', 'suit'], education: ['business_degree'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'accountant',
      levels: [
        { name: 'Accounting Clerk', salary: 155 },
        { name: 'Accountant', salary: 270 },
        { name: 'Senior Accountant', salary: 390 },
      ],
      level: 0,
      description: 'Handle financial records',
      requirements: { items: ['computer'], education: ['business_degree'] },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'politician',
      levels: [
        { name: 'Campaign Volunteer', salary: 190 },
        { name: 'City Council Member', salary: 470 },
        { name: 'Mayor', salary: 980 },
      ],
      level: 0,
      description: 'Serve the public through politics',
      requirements: { reputation: 20 },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'celebrity',
      levels: [
        { name: 'Influencer', salary: 310 },
        { name: 'TV Star', salary: 700 },
        { name: 'Movie Icon', salary: 1370 },
      ],
      level: 0,
      description: 'Live in the spotlight',
      requirements: { reputation: 30 },
      progress: 0,
      applied: false,
      accepted: false,
    },
    {
      id: 'athlete',
      levels: [
        { name: 'Rookie', salary: 270 },
        { name: 'Pro', salary: 620 },
        { name: 'Champion', salary: 1170 },
      ],
      level: 0,
      description: 'Compete at the highest level',
      requirements: { fitness: 60 },
      progress: 0,
      applied: false,
      accepted: false,
    },
  ],
  hobbies: [
    {
      id: 'music',
      name: 'Music',
      description: 'Practice instruments and perform',
      energyCost: 20,
      skill: 0,
      skillLevel: 1,
      tournamentReward: 100,
      songs: [],
      upgrades: [
        {
          id: 'better_instruments',
          name: 'Better Instruments',
          description: 'Increase song income by 20%',
          cost: 500,
          level: 0,
          maxLevel: 1,
          incomeBonusPerLevel: 0.2,
        },
        {
          id: 'promo_campaign',
          name: 'Promo Campaign',
          description: 'Increase song income by 5% per level',
          cost: 300,
          level: 0,
          maxLevel: 10,
          incomeBonusPerLevel: 0.05,
        },
        {
          id: 'studio_software',
          name: 'Studio Software',
          description: 'Buy a pro music program to boost song income by 5% per level',
          cost: 400,
          level: 0,
          maxLevel: 10,
          incomeBonusPerLevel: 0.05,
        },
        {
          id: 'home_studio',
          name: 'Home Studio',
          description: 'Upgrade your studio to gain +1 skill when training',
          cost: 500,
          level: 0,
          maxLevel: 5,
          skillBonusPerLevel: 1,
        },
      ],
    },
    {
      id: 'art',
      name: 'Art',
      description: 'Create and sell artwork',
      energyCost: 15,
      skill: 0,
      skillLevel: 1,
      tournamentReward: 90,
      artworks: [],
      upgrades: [
        {
          id: 'quality_supplies',
          name: 'Quality Supplies',
          description: 'Increase art income by 20%',
          cost: 400,
          level: 0,
          maxLevel: 1,
          incomeBonusPerLevel: 0.2,
        },
        {
          id: 'gallery_rep',
          name: 'Gallery Representation',
          description: 'Increase art income by 5% per level',
          cost: 300,
          level: 0,
          maxLevel: 10,
          incomeBonusPerLevel: 0.05,
        },
        {
          id: 'digital_tools',
          name: 'Digital Tools',
          description: 'Invest in tablets and software to raise art income by 5% per level',
          cost: 400,
          level: 0,
          maxLevel: 10,
          incomeBonusPerLevel: 0.05,
        },
        {
          id: 'studio_space',
          name: 'Studio Space',
          description: 'Rent a small studio and gain +1 skill when training',
          cost: 500,
          level: 0,
          maxLevel: 5,
          skillBonusPerLevel: 1,
        },
      ],
    },
    {
      id: 'football',
      name: 'Football',
      description: 'Train and play matches',
      energyCost: 25,
      skill: 0,
      skillLevel: 1,
      tournamentReward: 120,
      contracts: [],
      sponsors: [],
      maxSponsors: 1,
      divisions: [
        {
          name: 'Premier Division',
          teams: ['Lions FC', 'Eagles FC', 'Sharks FC', 'Tigers FC', 'Wolves FC', 'Dragons FC', 'Falcons FC', 'Pirates FC', 'Knights FC', 'Rangers FC', 'Comets FC', 'Storm FC'].map((name, i) => ({ name, goal: i + 1 })),
        },
        {
          name: 'Championship Division',
          teams: ['Bulls FC', 'Hurricanes FC', 'Panthers FC', 'Rhinos FC', 'Spartans FC', 'Vikings FC', 'Cobras FC', 'Phoenix FC', 'Raptors FC', 'Giants FC', 'Stallions FC', 'Raiders FC'].map((name, i) => ({ name, goal: i + 1 })),
        },
        {
          name: 'Amateur Division',
          teams: ['Miners FC', 'Sailors FC', 'Titans FC', 'Jets FC', 'Cyclones FC', 'Wildcats FC', 'Monarchs FC', 'Rockets FC', 'Grizzlies FC', 'Cougars FC', 'Tornadoes FC', 'Wizards FC'].map((name, i) => ({ name, goal: i + 1 })),
        },
      ],
      upgrades: [
        {
          id: 'pro_trainer',
          name: 'Pro Trainer',
          description: 'Gain +2 skill when training',
          cost: 350,
          level: 0,
          maxLevel: 1,
          skillBonusPerLevel: 2,
        },
        {
          id: 'sponsorship',
          name: 'Sponsorship Deal',
          description: 'Unlock sponsor offers and increase sponsor pay by 5% per level',
          cost: 400,
          level: 0,
          maxLevel: 10,
          incomeBonusPerLevel: 0.05,
        },
        {
          id: 'sponsor_slots',
          name: 'Sponsor Manager',
          description: 'Increase sponsor slots by 1',
          cost: 500,
          level: 0,
          maxLevel: 3,
          slotIncreasePerLevel: 1,
        },
      ],
    },
    {
      id: 'basketball',
      name: 'Basketball',
      description: 'Shoot hoops and join leagues',
      energyCost: 25,
      skill: 0,
      skillLevel: 1,
      tournamentReward: 120,
      contracts: [],
      sponsors: [],
      maxSponsors: 1,
      divisions: [
        {
          name: 'National League',
          teams: ['Skyhawks', 'Thunder', 'Blaze', 'Titans', 'Storm', 'Bulls', 'Warriors', 'Rockets', 'Panthers', 'Giants', 'Kings', 'Pirates'].map((name, i) => ({ name, goal: i + 1 })),
        },
        {
          name: 'Regional League',
          teams: ['Raptors', 'Comets', 'Falcons', 'Sharks', 'Dragons', 'Cyclones', 'Eagles', 'Wolves', 'Lions', 'Hurricanes', 'Spartans', 'Royals'].map((name, i) => ({ name, goal: i + 1 })),
        },
        {
          name: 'Local League',
          teams: ['Stallions', 'Phoenix', 'Tigers', 'Bisons', 'Vipers', 'Knights', 'Jets', 'Raiders', 'Rams', 'Bulldogs', 'Panthers', 'Stormers'].map((name, i) => ({ name, goal: i + 1 })),
        },
      ],
      upgrades: [
        {
          id: 'training_facility',
          name: 'Training Facility',
          description: 'Gain +2 skill when training',
          cost: 350,
          level: 0,
          maxLevel: 1,
          skillBonusPerLevel: 2,
        },
        {
          id: 'sponsorship',
          name: 'Sponsorship Deal',
          description: 'Unlock sponsor offers and increase sponsor pay by 5% per level',
          cost: 400,
          level: 0,
          maxLevel: 10,
          incomeBonusPerLevel: 0.05,
        },
        {
          id: 'sponsor_slots',
          name: 'Sponsor Manager',
          description: 'Increase sponsor slots by 1',
          cost: 500,
          level: 0,
          maxLevel: 3,
          slotIncreasePerLevel: 1,
        },
      ],
    },
    {
      id: 'tennis',
      name: 'Tennis',
      description: 'Practice your serve and compete',
      energyCost: 20,
      skill: 0,
      skillLevel: 1,
      tournamentReward: 110,
      contracts: [],
      sponsors: [],
      maxSponsors: 1,
      divisions: [
        {
          name: 'World Tour',
          teams: ['Grand Slams', 'Topspinners', 'Baseline Kings', 'Net Chargers', 'Serve Masters', 'Drop Shotters', 'Aces United', 'Spin Doctors', 'Court Warriors', 'Volley Vipers', 'Smash Bros', 'Slice Surge'].map((name, i) => ({ name, goal: i + 1 })),
        },
        {
          name: 'Challenger Tour',
          teams: ['Rally Raiders', 'Topspin Titans', 'Baseline Beasts', 'Net Ninjas', 'Serve Squad', 'Drop Shot Dragons', 'Ace Breakers', 'Spin Sharks', 'Court Crusaders', 'Volley Wolves', 'Smash Squad', 'Slice Strikers'].map((name, i) => ({ name, goal: i + 1 })),
        },
        {
          name: 'Amateur Tour',
          teams: ['Rookie Ralliers', 'Topspin Turtles', 'Baseline Bears', 'Net Knights', 'Serve Savers', 'Drop Shot Dolphins', 'Ace Apprentices', 'Spin Sparrows', 'Court Cadets', 'Volley Vultures', 'Smash Sprinters', 'Slice Swifts'].map((name, i) => ({ name, goal: i + 1 })),
        },
      ],
      upgrades: [
        {
          id: 'tennis_coach',
          name: 'Tennis Coach',
          description: 'Gain +2 skill when training',
          cost: 300,
          level: 0,
          maxLevel: 1,
          skillBonusPerLevel: 2,
        },
        {
          id: 'endorsement',
          name: 'Endorsement Deal',
          description: 'Unlock sponsor offers and increase sponsor pay by 5% per level',
          cost: 350,
          level: 0,
          maxLevel: 10,
          incomeBonusPerLevel: 0.05,
        },
        {
          id: 'sponsor_slots',
          name: 'Sponsor Manager',
          description: 'Increase sponsor slots by 1',
          cost: 500,
          level: 0,
          maxLevel: 3,
          slotIncreasePerLevel: 1,
        },
      ],
    },
  ],
  items: [
    { id: 'guitar', name: 'Guitar', price: 600, owned: false },
    { id: 'bike', name: 'Bike', price: 450, owned: false },
    {
      id: 'smartphone',
      name: 'Smartphone',
      price: 900,
      description: 'Unlocks mobile apps and new ways to earn money',
      owned: false,
    },
    {
      id: 'computer',
      name: 'Computer',
      price: 5000,
      description: 'Unlock desktop apps: Travel booking, Political Office, R&D Labs, Crypto Mining, Real Estate, Stocks, Banking, Social Media, Education, Gaming, and more. Essential for modern life opportunities.',
      owned: false,
    },
    { id: 'suit', name: 'Business Suit', price: 1200, owned: false },
    {
      id: 'basic_bed',
      name: 'Basic Bed',
      price: 1500,
      owned: false,
      dailyBonus: { energy: 10, happiness: 5 },
    },
    {
      id: 'gym_membership',
      name: 'Gym Membership',
      price: 300,
      owned: false,
      dailyBonus: { fitness: 2, health: 3 },
    },
    {
      id: 'passport',
      name: 'Passport',
      price: 500,
      description: 'Required for international travel destinations',
      owned: false,
    },
  ],
  darkWebItems: [
    {
      id: 'usb',
      name: 'Special USB',
      description: 'Essential hardware for exploits',
      costBtc: 0.012,
      rewardBonus: 0.1,
      owned: false,
    },
    {
      id: 'vpn',
      name: 'VPN',
      description: 'Mask your identity to reduce risk',
      costBtc: 0.007,
      riskReduction: 0.1,
      owned: false,
    },
    {
      id: 'proxy',
      name: 'Proxy Chain',
      description: 'Route traffic through multiple nodes',
      costBtc: 0.009,
      riskReduction: 0.05,
      owned: false,
    },
    {
      id: 'exploit',
      name: 'Exploit Kit',
      description: 'Advanced tools to find vulnerabilities',
      costBtc: 0.019,
      rewardBonus: 0.3,
      owned: false,
    },
    {
      id: 'encryption',
      name: 'Encryption Suite',
      description: 'Hide your tracks with strong encryption',
      costBtc: 0.016,
      riskReduction: 0.1,
      rewardBonus: 0.2,
      owned: false,
    },
    {
      id: 'lockpick',
      name: 'Lockpick Set',
      description: 'Essential for shoplifting and car theft',
      costBtc: 0.005,
      owned: false,
    },
    {
      id: 'slim_jim',
      name: 'Slim Jim',
      description: 'Tool for silently opening car doors',
      costBtc: 0.008,
      owned: false,
    },
    {
      id: 'drill_kit',
      name: 'Power Tool Kit',
      description: 'Heavy-duty tools for complex tasks',
      costBtc: 0.03,
      owned: false,
    },
    {
      id: 'explosives',
      name: 'Security Bypass Kit',
      description: 'Advanced tools for complex operations',
      costBtc: 0.05,
      owned: false,
    },
    {
      id: 'gloves',
      name: 'Stealth Gloves',
      description: 'Reduce chance of getting caught while pickpocketing',
      costBtc: 0.004,
      riskReduction: 0.05,
      owned: false,
    },
    {
      id: 'crowbar',
      name: 'Crowbar',
      description: 'Pry open doors and windows during burglaries',
      costBtc: 0.012,
      owned: false,
    },
    {
      id: 'malware_kit',
      name: 'Security Testing Kit',
      description: 'Toolkit for network security analysis',
      costBtc: 0.02,
      rewardBonus: 0.2,
      owned: false,
    },
    {
      id: 'spray_paint',
      name: 'Art Supplies',
      description: 'Street art materials for creative expression',
      costBtc: 0.003,
      owned: false,
    },
    {
      id: 'baseball_bat',
      name: 'Sports Equipment',
      description: 'Athletic gear for recreational activities',
      costBtc: 0.006,
      owned: false,
    },
    {
      id: 'drug_supply',
      name: 'Vendor Supplies',
      description: 'Inventory for street vending operations',
      costBtc: 0.015,
      owned: false,
    },
    {
      id: 'night_vision',
      name: 'Night Vision Goggles',
      description: 'See in the dark for stealth operations',
      costBtc: 0.025,
      riskReduction: 0.15,
      owned: false,
    },
    {
      id: 'silencer',
      name: 'Stealth Equipment',
      description: 'Reduce noise during operations',
      costBtc: 0.018,
      riskReduction: 0.1,
      owned: false,
    },
    {
      id: 'wireless_hack',
      name: 'Wireless Security Scanner',
      description: 'Advanced device for wireless network analysis',
      costBtc: 0.022,
      rewardBonus: 0.25,
      owned: false,
    },
    {
      id: 'thermal_vision',
      name: 'Thermal Vision Goggles',
      description: 'See through walls and detect heat signatures',
      costBtc: 0.035,
      riskReduction: 0.2,
      owned: false,
    },
    {
      id: 'emp_device',
      name: 'EMP Device',
      description: 'Electromagnetic pulse device to disable electronics',
      costBtc: 0.040,
      rewardBonus: 0.3,
      owned: false,
    },
  ],
  hacks: [
    {
      id: 'phishing',
      name: 'Social Engineering Test',
      description: 'Test email security systems',
      costBtc: 0.01,
      risk: 0.3,
      reward: 400,
      purchased: false,
      energyCost: 10,
    },
    {
      id: 'ransomware',
      name: 'Encryption Challenge',
      description: 'Test file encryption systems',
      costBtc: 0.02,
      risk: 0.5,
      reward: 1600,
      purchased: false,
      energyCost: 20,
    },
    {
      id: 'sql_injection',
      name: 'SQL Injection',
      description: 'Exploit database vulnerabilities',
      costBtc: 0.015,
      risk: 0.35,
      reward: 800,
      purchased: false,
      energyCost: 15,
    },
    {
      id: 'ddos',
      name: 'DDoS Attack',
      description: 'Overwhelm servers to extort payments',
      costBtc: 0.02,
      risk: 0.4,
      reward: 1200,
      purchased: false,
      energyCost: 25,
    },
    {
      id: 'zero_day',
      name: 'Zero-Day Exploit',
      description: 'Leverage unknown vulnerabilities',
      costBtc: 0.05,
      risk: 0.6,
      reward: 3000,
      purchased: false,
      energyCost: 30,
    },
    {
      id: 'mitm',
      name: 'Man-in-the-Middle',
      description: 'Intercept traffic for sensitive data',
      costBtc: 0.025,
      risk: 0.45,
      reward: 1000,
      purchased: false,
      energyCost: 18,
    },
    {
      id: 'keylogger',
      name: 'Keylogger Deployment',
      description: 'Capture keystrokes covertly',
      costBtc: 0.012,
      risk: 0.25,
      reward: 400,
      purchased: false,
      energyCost: 12,
    },
    {
      id: 'bruteforce',
      name: 'Brute Force Attack',
      description: 'Crack passwords through sheer power',
      costBtc: 0.018,
      risk: 0.4,
      reward: 900,
      purchased: false,
      energyCost: 22,
    },
  ],
  relationships: [
    {
      id: 'parent1',
      name: 'Mom',
      type: 'parent',
      relationshipScore: 50,
      personality: 'caring',
      gender: 'female',
      age: 45,
    },
    {
      id: 'parent2',
      name: 'Dad',
      type: 'parent',
      relationshipScore: 50,
      personality: 'strict',
      gender: 'male',
      age: 47,
    },
  ],
  pets: [],
  social: { relations: [] },
  family: { children: [] },
  lifeStage: getLifeStage(18),
  foods: [
    { id: 'apple', name: 'Apple', price: 5, healthRestore: 3, energyRestore: 2 },
    { id: 'sandwich', name: 'Sandwich', price: 15, healthRestore: 8, energyRestore: 12 },
    { id: 'salad', name: 'Healthy Salad', price: 18, healthRestore: 10, energyRestore: 6 },
    { id: 'pizza', name: 'Pizza Slice', price: 12, healthRestore: 5, energyRestore: 15 },
    { id: 'burger', name: 'Burger', price: 18, healthRestore: 8, energyRestore: 18 },
    { id: 'sushi', name: 'Sushi Roll', price: 25, healthRestore: 15, energyRestore: 8 },
    { id: 'smoothie', name: 'Green Smoothie', price: 14, healthRestore: 12, energyRestore: 7 },
    { id: 'steak', name: 'Steak Dinner', price: 40, healthRestore: 20, energyRestore: 25 },
    { id: 'ramen', name: 'Instant Ramen', price: 8, healthRestore: 4, energyRestore: 8 },
    { id: 'protein_bar', name: 'Protein Bar', price: 10, healthRestore: 5, energyRestore: 12 },
  ],
  healthActivities: [
    { id: 'walk', name: 'Walk in Park', description: 'Peaceful walk to clear your mind', price: 0, happinessGain: 3, healthGain: 1, energyCost: 12 },
    // STABILITY FIX: Make meditation free to provide low-cost happiness recovery option
    // This prevents death spiral for players with low money who can't afford health activities
    { id: 'meditation', name: 'Meditation Session', description: 'Find inner peace and reduce stress', price: 0, happinessGain: 6, energyCost: 8 },
    { id: 'yoga', name: 'Yoga Class', description: 'Improve flexibility and mental clarity', price: 100, happinessGain: 6, healthGain: 3, energyCost: 12 },
    { id: 'massage', name: 'Spa Massage', description: 'Relax and rejuvenate your body', price: 300, happinessGain: 10, healthGain: 5, energyCost: 12 },
    {
      id: 'doctor',
      name: 'Doctor Visit',
      description: 'Regular checkup (50% chance to cure health issues)',
      price: 500,
      happinessGain: 0,
      healthGain: 18,
      energyCost: 12
    },
    { id: 'therapy', name: 'Therapy Session', description: 'Professional mental health support', price: 400, happinessGain: 15, energyCost: 10 },
    {
      id: 'hospital',
      name: 'Hospital Stay',
      description: 'Cures all health issues except cancer',
      price: 2000,
      happinessGain: -10,
      healthGain: 35,
      energyCost: 18
    },
    { id: 'experimental', name: 'Experimental Treatment', description: 'Cutting-edge medical procedure', price: 12000, happinessGain: 12, healthGain: 25, energyCost: 15 },
    { id: 'vacation', name: 'Weekend Getaway', description: 'Short vacation to recharge', price: 16000, happinessGain: 30, healthGain: 5, energyCost: -20 },
    { id: 'retreat', name: 'Wellness Retreat', description: 'Multi-day wellness experience', price: 30000, happinessGain: 35, healthGain: 15, energyCost: 12 },
  ],
  dietPlans: [
    { id: 'basic', name: 'Basic Diet', description: 'Simple, healthy meals', dailyCost: 2500, healthGain: 3, energyGain: 2, active: false },
    { id: 'premium', name: 'Premium Diet', description: 'Organic, high-quality ingredients', dailyCost: 6000, healthGain: 8, energyGain: 5, happinessGain: 3, active: false },
    { id: 'athlete', name: 'Athlete Diet', description: 'High-protein, performance-focused', dailyCost: 10000, healthGain: 12, energyGain: 8, happinessGain: 5, active: false },
  ],
  educations: [],
  userProfile: {
    name: 'Player',
    handle: '@player',
    bio: 'Living my best life!',
    followers: 0,
    following: 0,
    gender: 'male',
    seekingGender: 'female',
    firstName: '',
    lastName: '',
    sex: 'male',
    sexuality: 'straight',
    // Enhanced profile fields for X.com-style social
    profilePhoto: undefined,
    headerPhoto: undefined,
    displayName: 'Player',
    username: 'player',
    location: undefined,
    website: undefined,
    joinedDate: new Date().toISOString(),
    verified: false,
    bookmarkedPosts: [],
  },
  settings: {
    lifetimePremium: false,
    darkMode: true,
    soundEnabled: true,
    hapticFeedback: false,
    notificationsEnabled: true,
    autoSave: true,
    language: 'English',
    maxStats: false,
    weeklySummaryEnabled: true,
    showDecimalsInStats: false, // Default to false - no decimals for savings and gems
    autoProgression: true, // Auto-progression for progressive disclosure (enabled by default)
  },
  diseases: [],
  realEstate: [],
  economy: { inflationRateAnnual: 0.03, priceIndex: 1 },
  cryptos: [
    { id: 'btc', symbol: 'BTC', name: 'Bitcoin', price: 42150.0, change: 0, changePercent: 0, owned: 0 },
    { id: 'eth', symbol: 'ETH', name: 'Ethereum', price: 2580.5, change: 0, changePercent: 0, owned: 0 },
    { id: 'xrp', symbol: 'XRP', name: 'Ripple', price: 0.52, change: 0, changePercent: 0, owned: 0 },
    { id: 'ada', symbol: 'ADA', name: 'Cardano', price: 0.38, change: 0, changePercent: 0, owned: 0 },
    { id: 'sol', symbol: 'SOL', name: 'Solana', price: 98.45, change: 0, changePercent: 0, owned: 0 },
    { id: 'dot', symbol: 'DOT', name: 'Polkadot', price: 5.23, change: 0, changePercent: 0, owned: 0 },
    { id: 'matic', symbol: 'MATIC', name: 'Polygon', price: 0.85, change: 0, changePercent: 0, owned: 0 },
    { id: 'link', symbol: 'LINK', name: 'Chainlink', price: 14.2, change: 0, changePercent: 0, owned: 0 },
  ],
  companies: [],
  company: undefined,
  showWelcomePopup: true,
  hasSeenJobTutorial: false,
  hasSeenInvestmentTutorial: false,
  hasSeenDatingTutorial: false,
  hasSeenHealthWarning: false,
  hasSeenEnergyWarning: false,
  hasSeenMoneyManagementTutorial: false,
  hasSeenSocialMediaTutorial: false,
  hasSeenRealEstateTutorial: false,
  achievements: [
    // Money
    { id: 'first_dollar', name: 'First Payday', description: 'Earn your first hard-earned dollar', category: 'money', completed: false },
    { id: 'hundred_dollars', name: 'Hundredaire', description: 'Reach $100 in savings', category: 'money', completed: false },
    { id: 'thousand_dollars', name: 'Thousandaire', description: 'Save up $1,000', category: 'money', completed: false },
    { id: 'ten_thousand', name: 'Five Figures', description: 'Accumulate $10,000 in wealth', category: 'money', completed: false },
    { id: 'hundred_thousand', name: 'Six Figures', description: 'Hit $100,000 net worth', category: 'money', completed: false },
    { id: 'millionaire', name: 'Millionaire', description: 'Become a millionaire', category: 'money', completed: false },
    {
      id: 'deca_millionaire',
      name: 'Deca-Millionaire',
      description: 'Save $10,000,000',
      category: 'money',
      completed: false,
      reward: 50,
    },

    // Career
    { id: 'first_job', name: 'First Job', description: 'Get your first job', category: 'career', completed: false },
    { id: 'street_worker', name: 'Street Smart', description: 'Complete 10 street gigs', category: 'career', completed: false },
    { id: 'career_starter', name: 'Career Starter', description: 'Land a career job', category: 'career', completed: false },
    { id: 'promotion', name: 'Moving Up', description: 'Earn a promotion', category: 'career', completed: false },
    { id: 'entrepreneur', name: 'Entrepreneur', description: 'Start your own company', category: 'career', completed: false },
    { id: 'first_upgrade', name: 'Upgrade Complete', description: 'Purchase your first company upgrade', category: 'career', completed: false },
    { id: 'all_upgrades', name: 'Fully Equipped', description: 'Buy every company upgrade', category: 'career', completed: false },
    { id: 'first_worker', name: 'First Hire', description: 'Hire your first worker', category: 'career', completed: false },
    { id: 'team_builder', name: 'Team Builder', description: 'Hire 5 company workers', category: 'career', completed: false },
    {
      id: 'industry_mogul',
      name: 'Industry Mogul',
      description: 'Reach $50,000 weekly company income',
      category: 'career',
      completed: false,
      reward: 40,
    },
    { id: 'politician_legend', name: 'Political Legend', description: 'Reach the highest level in the politician career', category: 'career', completed: false },
    { id: 'celebrity_icon', name: 'Celebrity Icon', description: 'Reach the highest level in the celebrity career', category: 'career', completed: false },
    { id: 'athletic_champion', name: 'Athletic Champion', description: 'Reach the highest level in the athlete career', category: 'career', completed: false },

    // Education
    { id: 'graduate', name: 'Graduate', description: 'Complete high school', category: 'education', completed: false },
    { id: 'college_grad', name: 'College Graduate', description: 'Finish university', category: 'education', completed: false },
    { id: 'specialist', name: 'Specialist', description: 'Complete a specialized degree', category: 'education', completed: false },
    { id: 'lifelong_learner', name: 'Lifelong Learner', description: 'Complete 3 different educations', category: 'education', completed: false },

    // Relationships
    { id: 'first_friend', name: 'Social Butterfly', description: 'Make your first friend', category: 'relationships', completed: false },
    { id: 'popular', name: 'Popular', description: 'Have 5 relationships', category: 'relationships', completed: false },
    { id: 'lover', name: 'Lover', description: 'Find a romantic partner', category: 'relationships', completed: false },
    { id: 'married', name: 'Married', description: 'Get married', category: 'relationships', completed: false },
    { id: 'parent', name: 'Parent', description: 'Have a child', category: 'relationships', completed: false },
    { id: 'best_friend', name: 'Best Friend', description: 'Reach 100 relationship with a friend', category: 'relationships', completed: false },

    // Health
    { id: 'fitness_buff', name: 'Fitness Buff', description: 'Reach 50 fitness', category: 'health', completed: false },
    { id: 'athlete', name: 'Athlete', description: 'Reach 100 fitness', category: 'health', completed: false },
    { id: 'healthy_lifestyle', name: 'Healthy Lifestyle', description: 'Use a diet plan for 4 weeks', category: 'health', completed: false },
    { id: 'wellness_guru', name: 'Wellness Guru', description: 'Complete 20 health activities', category: 'health', completed: false },

    // Items
    { id: 'first_purchase', name: 'First Purchase', description: 'Buy your first item', category: 'items', completed: false },
    { id: 'tech_savvy', name: 'Tech Savvy', description: 'Own smartphone and computer', category: 'items', completed: false },
    { id: 'luxury_life', name: 'Luxury Life', description: 'Own car, house, and yacht', category: 'items', completed: false },
    { id: 'collector', name: 'Collector', description: 'Own all available items', category: 'items', completed: false },

    // Special
    { id: 'survivor', name: 'Survivor', description: 'Live to age 65', category: 'special', completed: false },
    { id: 'centenarian', name: 'Centenarian', description: 'Live to age 100', category: 'special', completed: false },
    { id: 'crypto_investor', name: 'Crypto Investor', description: 'Own $10,000 worth of cryptocurrency', category: 'special', completed: false },
    {
      id: 'gold_hoarder',
      name: 'Gold Hoarder',
      description: 'Collect 100 Gems',
      category: 'special',
      completed: false,
      reward: 100,
    },

    // Secret achievements - Remain hidden until unlocked
    {
      id: 'secret_1',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'The Centenarian',
      secretDescription: 'Die at exactly age 100',
      reward: 100
    },
    {
      id: 'secret_2',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'Billion Dollar Baby',
      secretDescription: 'Earn $1 billion in net worth in a single life',
      reward: 500
    },
    {
      id: 'secret_3',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'Jack of All Trades',
      secretDescription: 'Reach level 3 in all crime skills',
      reward: 150
    },
    {
      id: 'secret_4',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'Perfect Life',
      secretDescription: 'Survive 10 years (520 weeks) with all stats above 90',
      reward: 300
    },
    {
      id: 'secret_5',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'Real Estate Mogul',
      secretDescription: 'Own 10 or more properties simultaneously',
      reward: 200
    },
    {
      id: 'secret_6',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'Started From the Bottom',
      secretDescription: 'Reach $1M net worth starting from $0',
      reward: 150
    },
    {
      id: 'secret_7',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'True Love',
      secretDescription: 'Get married with a relationship score of 100',
      reward: 100
    },
    {
      id: 'secret_8',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'Criminal Mastermind',
      secretDescription: 'Complete 100 underground jobs',
      reward: 200
    },
    {
      id: 'secret_9',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'The Immortal',
      secretDescription: 'Survive to age 150 or beyond',
      reward: 1000
    },
    {
      id: 'secret_10',
      name: '???',
      description: 'Hidden achievement',
      category: 'secret',
      completed: false,
      secretName: 'Easter Egg Hunter',
      secretDescription: 'Unlock all 9 other secret achievements',
      reward: 500
    },
  ],
  claimedProgressAchievements: [],
  lastLogin: Date.now(),
  updatedAt: Date.now(),
  streetJobsCompleted: 0,
  happinessZeroWeeks: 0,
  healthZeroWeeks: 0,
  healthWeeks: 0,
  showZeroStatPopup: false,
  zeroStatType: undefined,
  showDeathPopup: false,
  deathReason: undefined,
  showSicknessModal: false,
  showCureSuccessModal: false,
  curedDiseases: [],
  // Goal System
  goals: [],
  goalProgress: {},
  completedGoals: [],
  // Enhanced Social System
  socialEvents: [],
  socialGroups: [],
  socialInteractions: [],
  lastEventTimes: {},
  hasPhone: false,
  computerPreviouslyOwned: false,
  day: 1,
  dailySummary: undefined,
  gamingStreaming: {
    followers: 0,
    subscribers: 0,
    totalViews: 0,
    totalEarnings: 0,
    totalDonations: 0,
    totalSubEarnings: 0,
    level: 1,
    experience: 0,
    gamesPlayed: [],
    streamHours: 0,
    averageViewers: 0,
    bestStream: null,
    currentStream: null,
    equipment: {
      microphone: false,
      webcam: false,
      gamingChair: false,
      greenScreen: false,
      lighting: false,
    },
    pcComponents: {
      cpu: false,
      gpu: false,
      ram: false,
      ssd: false,
      motherboard: false,
      cooling: false,
      psu: false,
      case: false,
      network: false,
    },
    pcUpgradeLevels: {
      cpu: 0,
      gpu: 0,
      ram: 0,
      ssd: 0,
      motherboard: 0,
      cooling: 0,
      psu: 0,
      case: 0,
      network: 0,
    },
    paidMembers: 0,
    membershipRate: 4,
    unlockedGames: [],
    ownedGames: [],
    streamHistory: [],
    videos: [],
    videoTitleCounters: {},
    videoRecordingState: {
      isRecording: false,
      recordProgress: 0,
      renderProgress: 0,
      uploadProgress: 0,
      currentPhase: 'idle',
      videoTitle: '',
      videoGame: '',
      isRendering: false,
      isUploading: false,
    },
    streamingState: {
      isStreaming: false,
      streamProgress: 0,
      totalDonations: 0,
      streamDuration: 0,
      selectedGame: '',
      currentViewers: 0,
      currentSubsGained: 0,
      upgrades: {},
    },
    upgrades: {},
  },
  pendingEvents: [],
  eventLog: [],
  progress: { achievements: [], adsRemoved: false, hasBeenInDebt: false },
  journal: [],
  scenarioId: undefined,
  challengeScenarioId: undefined, // CRITICAL FIX: Track challenge scenario ID for completion tracking
  stocks: {
    holdings: [],
    watchlist: [],
  },
  prestige: defaultPrestigeData,
  prestigeAvailable: false,
  seasonalEvents: {
    lastSeason: '',
    completedEvents: [],
  },
  socialMedia: {
    followers: 0,
    influenceLevel: 'novice',
    totalPosts: 0,
    viralPosts: 0,
    brandPartnerships: 0,
    engagementRate: 0,
    lastPostTime: undefined,
    lastPostDay: undefined,
    lastPostTimes: undefined,
    lastPostWeeks: undefined,
    totalLiveStreams: 0,
    totalLiveViewers: 0,
    totalLiveDuration: 0,
    peakLiveViewers: 0,
    totalEarnings: 0,
    activeBrandDeals: [],
    recentPosts: [],
  },
  travel: {
    visitedDestinations: [],
    passportOwned: false,
    businessOpportunities: {},
    travelHistory: [],
  },
  politics: {
    activePolicyEffects: undefined,
    careerLevel: 0,
    approvalRating: 50,
    policyInfluence: 0,
    electionsWon: 0,
    policiesEnacted: [],
    lobbyists: [],
    alliances: [],
    campaignFunds: 0,
  },
  // Statistics & Analytics Dashboard
  lifetimeStatistics: {
    totalMoneyEarned: 0,
    totalMoneySpent: 0,
    peakNetWorth: 0,
    peakNetWorthWeek: 0,
    totalWeeksWorked: 0,
    totalRelationships: 0,
    totalChildren: 0,
    totalCompaniesOwned: 0,
    totalPropertiesOwned: 0,
    totalCrimesCommitted: 0,
    totalJailTime: 0,
    totalTravelDestinations: 0,
    totalPostsMade: 0,
    totalViralPosts: 0,
    careerHistory: [],
    netWorthHistory: [],
    weeklyEarningsHistory: [],
    highestSalary: 0,
    totalHobbiesLearned: 0,
    totalAchievementsUnlocked: 0,
  },
  // Dynasty System
  dynastyStats: {
    totalGenerations: 1,
    totalWealth: 0,
    familyReputation: 0,
    heirlooms: [],
    familyAchievements: [],
    longestLivingMember: { name: '', age: 0 },
    wealthiestMember: { name: '', netWorth: 0 },
    totalChildrenAllGenerations: 0,
    dynastyFoundedYear: 2025,
    familyMotto: undefined,
  },
  // Event Chaining
  pendingChainedEvents: [],
  // Enhanced Social Posts
  socialPosts: [],
  // Life Milestones (wedding, engagement, etc.)
  lifeMilestones: [],
  // Activity Commitment System
  activityCommitments: {
    primary: undefined,
    secondary: undefined,
    lastChangedWeek: undefined,
    commitmentLevels: {
      career: 0,
      hobbies: 0,
      relationships: 0,
      health: 0,
    },
  },
  // Depth Enhancement System
  discoveredSystems: [],
  depthMetrics: {
    depthScore: 0,
    systemsEngaged: 0,
    lastCalculated: Date.now(),
  },
  progressiveDisclosureLevel: 'standard',
  systemStatistics: {},
};






