const { withGradleProperties } = require('@expo/config-plugins');

/**
 * Raise Android AsyncStorage's database cap.
 *
 * @react-native-async-storage/async-storage caps its SQLite database at 6 MB
 * on Android unless `AsyncStorage_db_size_in_MB` is set in gradle.properties
 * (node_modules/@react-native-async-storage/async-storage/android/config.gradle,
 * `getDatabaseSize`). A single late-game save slot holds the A/B double
 * buffer, up to five full backups, the checkpoint sidecar and, while a save is
 * in flight, the queue journal - about 3 MB - so two slots reach SQLITE_FULL
 * while the device still has free space, and the save fails. iOS has no such
 * cap. See tasks/home-freeze-and-audits-2026-09-25.md.
 *
 * The same property is also committed in android/gradle.properties; this plugin
 * keeps it there if the native project is ever regenerated by prebuild.
 */
const ASYNC_STORAGE_DB_SIZE_MB = '64';

const withAsyncStorageSize = (config) =>
  withGradleProperties(config, (cfg) => {
    const key = 'AsyncStorage_db_size_in_MB';
    cfg.modResults = cfg.modResults.filter(
      (item) => !(item.type === 'property' && item.key === key)
    );
    cfg.modResults.push({ type: 'property', key, value: ASYNC_STORAGE_DB_SIZE_MB });
    return cfg;
  });

module.exports = withAsyncStorageSize;
module.exports.ASYNC_STORAGE_DB_SIZE_MB = ASYNC_STORAGE_DB_SIZE_MB;
