/**
 * Dating Profiles
 * 
 * Shared dating profiles that can be used across the app
 * for social media posts and other features
 */

/**
 * Get the appropriate Face image based on gender
 * @param gender - Profile's gender ('male' or 'female')
 * @returns Image source for the profile
 */
export function getDatingProfileImage(gender: 'male' | 'female') {
  return gender === 'female'
    ? require('@/assets/images/Face/Female.png')
    : require('@/assets/images/Face/Male.png');
}

export interface DatingProfile {
  id: string;
  name: string;
  age: number;
  bio: string;
  interests: string[];
  image?: string; // Optional, will use Face images instead
  distance: number;
  wealth: 'poor' | 'average' | 'wealthy' | 'millionaire';
  income: number;
  personality: string;
  gender: 'male' | 'female';
  seekingGender: 'male' | 'female';
  photos?: string[]; // Optional, will use Face images instead
  job: string;
  education: string;
}

export const DATING_PROFILES: DatingProfile[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    age: 24,
    bio: 'Love hiking and coffee ☕️ Looking for someone who shares my passion for adventure and good conversation.',
    interests: ['Hiking', 'Coffee', 'Travel', 'Photography'],
    distance: 2,
    wealth: 'average',
    income: 45000,
    personality: 'adventurous',
    gender: 'female',
    seekingGender: 'male',
    job: 'Marketing Manager',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '2',
    name: 'Emma Davis',
    age: 26,
    bio: 'Artist by day, dreamer by night 🎨 I create beauty and seek someone who appreciates the finer things in life.',
    interests: ['Art', 'Music', 'Photography', 'Wine'],
    distance: 5,
    wealth: 'wealthy',
    income: 85000,
    personality: 'creative',
    gender: 'female',
    seekingGender: 'male',
    job: 'Art Director',
    education: 'Master\'s Degree',
  },
  {
    id: '3',
    name: 'Jessica Kim',
    age: 23,
    bio: 'Fitness enthusiast and foodie 💪 Looking for someone who values health and can cook a mean pasta!',
    interests: ['Fitness', 'Cooking', 'Yoga', 'Healthy Living'],
    distance: 3,
    wealth: 'average',
    income: 38000,
    personality: 'active',
    gender: 'female',
    seekingGender: 'male',
    job: 'Personal Trainer',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '4',
    name: 'Sophia Rodriguez',
    age: 28,
    bio: 'Tech entrepreneur and coffee addict ☕️ Building the future while looking for someone to share it with.',
    interests: ['Technology', 'Coffee', 'Startups', 'Travel'],
    distance: 1,
    wealth: 'millionaire',
    income: 250000,
    personality: 'ambitious',
    gender: 'female',
    seekingGender: 'male',
    job: 'CEO & Founder',
    education: 'MBA',
  },
  {
    id: '5',
    name: 'Isabella Chen',
    age: 25,
    bio: 'Doctor by profession, foodie by passion 🏥 Looking for someone who can keep up with my busy schedule.',
    interests: ['Medicine', 'Cooking', 'Travel', 'Reading'],
    distance: 4,
    wealth: 'wealthy',
    income: 120000,
    personality: 'intelligent',
    gender: 'female',
    seekingGender: 'male',
    job: 'Medical Doctor',
    education: 'Medical Degree',
  },
  {
    id: '6',
    name: 'Olivia Thompson',
    age: 22,
    bio: 'Student and part-time barista ☕️ Love books, music, and deep conversations.',
    interests: ['Reading', 'Music', 'Coffee', 'Philosophy'],
    distance: 1,
    wealth: 'poor',
    income: 15000,
    personality: 'intellectual',
    gender: 'female',
    seekingGender: 'male',
    job: 'Student',
    education: 'Bachelor\'s Degree (In Progress)',
  },
  {
    id: '7',
    name: 'Michael Chen',
    age: 27,
    bio: 'Software engineer who loves gaming and tech 🎮 Always up for a good conversation about the latest innovations.',
    interests: ['Gaming', 'Technology', 'Coding', 'Anime'],
    distance: 3,
    wealth: 'average',
    income: 75000,
    personality: 'tech-savvy',
    gender: 'male',
    seekingGender: 'female',
    job: 'Software Engineer',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '8',
    name: 'David Martinez',
    age: 29,
    bio: 'Fitness coach and nutritionist 💪 Helping people transform their lives, one workout at a time.',
    interests: ['Fitness', 'Nutrition', 'Health', 'Motivation'],
    distance: 4,
    wealth: 'average',
    income: 55000,
    personality: 'motivational',
    gender: 'male',
    seekingGender: 'female',
    job: 'Fitness Coach',
    education: 'Certification',
  },
  {
    id: '9',
    name: 'James Wilson',
    age: 31,
    bio: 'Investment banker with a passion for travel and fine dining 🍷 Looking for someone to share adventures with.',
    interests: ['Finance', 'Travel', 'Fine Dining', 'Wine'],
    distance: 2,
    wealth: 'wealthy',
    income: 150000,
    personality: 'sophisticated',
    gender: 'male',
    seekingGender: 'female',
    job: 'Investment Banker',
    education: 'MBA',
  },
  {
    id: '10',
    name: 'Ryan Taylor',
    age: 26,
    bio: 'Musician and music producer 🎵 Creating beats and looking for someone who appreciates good vibes.',
    interests: ['Music', 'Production', 'Concerts', 'Art'],
    distance: 5,
    wealth: 'average',
    income: 40000,
    personality: 'artistic',
    gender: 'male',
    seekingGender: 'female',
    job: 'Music Producer',
    education: 'Music Degree',
  },
  // Additional Female Profiles
  {
    id: '11',
    name: 'Amanda Foster',
    age: 29,
    bio: 'Lawyer by day, bookworm by night 📚 Looking for someone who enjoys deep conversations and intellectual debates.',
    interests: ['Reading', 'Law', 'Debate', 'Theater'],
    distance: 3,
    wealth: 'wealthy',
    income: 110000,
    personality: 'intellectual',
    gender: 'female',
    seekingGender: 'male',
    job: 'Attorney',
    education: 'Law Degree',
  },
  {
    id: '12',
    name: 'Rachel Green',
    age: 27,
    bio: 'Graphic designer with a love for minimalism and clean aesthetics 🎨 Seeking someone who appreciates good design.',
    interests: ['Design', 'Art', 'Photography', 'Minimalism'],
    distance: 2,
    wealth: 'average',
    income: 52000,
    personality: 'creative',
    gender: 'female',
    seekingGender: 'male',
    job: 'Graphic Designer',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '13',
    name: 'Maya Patel',
    age: 24,
    bio: 'Yoga instructor and wellness coach 🧘‍♀️ Passionate about mindfulness and living a balanced life.',
    interests: ['Yoga', 'Meditation', 'Wellness', 'Nature'],
    distance: 4,
    wealth: 'average',
    income: 42000,
    personality: 'zen',
    gender: 'female',
    seekingGender: 'male',
    job: 'Yoga Instructor',
    education: 'Certification',
  },
  {
    id: '14',
    name: 'Chloe Anderson',
    age: 25,
    bio: 'Event planner who loves bringing people together 🎉 Looking for someone who enjoys celebrations and good times.',
    interests: ['Events', 'Planning', 'Socializing', 'Travel'],
    distance: 1,
    wealth: 'average',
    income: 48000,
    personality: 'social',
    gender: 'female',
    seekingGender: 'male',
    job: 'Event Planner',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '15',
    name: 'Lily Chen',
    age: 26,
    bio: 'Data scientist and AI enthusiast 🤖 Fascinated by technology and looking for someone who shares my curiosity.',
    interests: ['Technology', 'AI', 'Data Science', 'Gaming'],
    distance: 2,
    wealth: 'wealthy',
    income: 95000,
    personality: 'analytical',
    gender: 'female',
    seekingGender: 'male',
    job: 'Data Scientist',
    education: 'Master\'s Degree',
  },
  {
    id: '16',
    name: 'Zoe Williams',
    age: 23,
    bio: 'Nurse with a big heart ❤️ Love helping others and looking for someone kind and compassionate.',
    interests: ['Healthcare', 'Volunteering', 'Reading', 'Cooking'],
    distance: 3,
    wealth: 'average',
    income: 58000,
    personality: 'caring',
    gender: 'female',
    seekingGender: 'male',
    job: 'Registered Nurse',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '17',
    name: 'Ava Mitchell',
    age: 28,
    bio: 'Real estate agent who loves architecture and interior design 🏠 Looking for someone who appreciates beautiful spaces.',
    interests: ['Real Estate', 'Architecture', 'Interior Design', 'Travel'],
    distance: 5,
    wealth: 'wealthy',
    income: 88000,
    personality: 'ambitious',
    gender: 'female',
    seekingGender: 'male',
    job: 'Real Estate Agent',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '18',
    name: 'Grace Lee',
    age: 24,
    bio: 'Teacher and education advocate 📖 Passionate about learning and making a difference in young lives.',
    interests: ['Education', 'Reading', 'Volunteering', 'Music'],
    distance: 2,
    wealth: 'average',
    income: 45000,
    personality: 'passionate',
    gender: 'female',
    seekingGender: 'male',
    job: 'Elementary Teacher',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '19',
    name: 'Natalie Brown',
    age: 27,
    bio: 'Chef specializing in fusion cuisine 🍜 Love experimenting with flavors and creating memorable dining experiences.',
    interests: ['Cooking', 'Food', 'Travel', 'Culture'],
    distance: 4,
    wealth: 'average',
    income: 62000,
    personality: 'creative',
    gender: 'female',
    seekingGender: 'male',
    job: 'Head Chef',
    education: 'Culinary Arts Degree',
  },
  // Additional Male Profiles
  {
    id: '20',
    name: 'Alex Thompson',
    age: 28,
    bio: 'Architect with a passion for sustainable design 🏗️ Looking for someone who values creativity and environmental consciousness.',
    interests: ['Architecture', 'Design', 'Sustainability', 'Travel'],
    distance: 3,
    wealth: 'wealthy',
    income: 92000,
    personality: 'creative',
    gender: 'male',
    seekingGender: 'female',
    job: 'Architect',
    education: 'Master\'s Degree',
  },
  {
    id: '21',
    name: 'Chris Anderson',
    age: 25,
    bio: 'Photographer capturing life\'s beautiful moments 📸 Seeking someone who appreciates art and adventure.',
    interests: ['Photography', 'Travel', 'Art', 'Nature'],
    distance: 2,
    wealth: 'average',
    income: 48000,
    personality: 'artistic',
    gender: 'male',
    seekingGender: 'female',
    job: 'Photographer',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '22',
    name: 'Jordan Lee',
    age: 26,
    bio: 'Physical therapist helping people recover and stay active 🏃‍♂️ Love fitness and looking for someone active.',
    interests: ['Fitness', 'Health', 'Sports', 'Outdoors'],
    distance: 4,
    wealth: 'average',
    income: 68000,
    personality: 'active',
    gender: 'male',
    seekingGender: 'female',
    job: 'Physical Therapist',
    education: 'Doctorate Degree',
  },
  {
    id: '23',
    name: 'Tyler Johnson',
    age: 24,
    bio: 'Mechanical engineer who loves building and fixing things 🔧 Looking for someone who appreciates problem-solving.',
    interests: ['Engineering', 'DIY', 'Technology', 'Cars'],
    distance: 1,
    wealth: 'average',
    income: 72000,
    personality: 'analytical',
    gender: 'male',
    seekingGender: 'female',
    job: 'Mechanical Engineer',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '24',
    name: 'Noah Martinez',
    age: 29,
    bio: 'Psychologist helping people understand themselves better 🧠 Interested in deep conversations and emotional intelligence.',
    interests: ['Psychology', 'Reading', 'Meditation', 'Philosophy'],
    distance: 3,
    wealth: 'wealthy',
    income: 105000,
    personality: 'thoughtful',
    gender: 'male',
    seekingGender: 'female',
    job: 'Clinical Psychologist',
    education: 'Doctorate Degree',
  },
  {
    id: '25',
    name: 'Ethan Davis',
    age: 27,
    bio: 'Marketing director with a creative edge 📱 Love storytelling and connecting brands with people.',
    interests: ['Marketing', 'Advertising', 'Social Media', 'Networking'],
    distance: 2,
    wealth: 'wealthy',
    income: 88000,
    personality: 'creative',
    gender: 'male',
    seekingGender: 'female',
    job: 'Marketing Director',
    education: 'MBA',
  },
  {
    id: '26',
    name: 'Lucas Wilson',
    age: 30,
    bio: 'Firefighter and community hero 🚒 Looking for someone who values service and has a big heart.',
    interests: ['Firefighting', 'Fitness', 'Community Service', 'Outdoors'],
    distance: 5,
    wealth: 'average',
    income: 65000,
    personality: 'heroic',
    gender: 'male',
    seekingGender: 'female',
    job: 'Firefighter',
    education: 'Certification',
  },
  {
    id: '27',
    name: 'Mason Brown',
    age: 25,
    bio: 'Chef at a fine dining restaurant 🍽️ Passionate about culinary arts and creating unforgettable experiences.',
    interests: ['Cooking', 'Fine Dining', 'Wine', 'Travel'],
    distance: 4,
    wealth: 'average',
    income: 55000,
    personality: 'passionate',
    gender: 'male',
    seekingGender: 'female',
    job: 'Sous Chef',
    education: 'Culinary Arts Degree',
  },
  {
    id: '28',
    name: 'Owen Garcia',
    age: 28,
    bio: 'Environmental scientist working on climate solutions 🌱 Looking for someone who cares about the planet.',
    interests: ['Environment', 'Science', 'Hiking', 'Sustainability'],
    distance: 3,
    wealth: 'average',
    income: 75000,
    personality: 'environmentalist',
    gender: 'male',
    seekingGender: 'female',
    job: 'Environmental Scientist',
    education: 'Master\'s Degree',
  },
  {
    id: '29',
    name: 'Carter White',
    age: 26,
    bio: 'Veterinarian who loves animals 🐾 Looking for someone who shares my love for pets and nature.',
    interests: ['Animals', 'Veterinary Medicine', 'Nature', 'Hiking'],
    distance: 2,
    wealth: 'wealthy',
    income: 95000,
    personality: 'compassionate',
    gender: 'male',
    seekingGender: 'female',
    job: 'Veterinarian',
    education: 'Doctorate Degree',
  },
  {
    id: '30',
    name: 'Logan Harris',
    age: 24,
    bio: 'Electrician and DIY enthusiast ⚡ Love fixing things and working with my hands.',
    interests: ['DIY', 'Electronics', 'Home Improvement', 'Gaming'],
    distance: 1,
    wealth: 'average',
    income: 58000,
    personality: 'handy',
    gender: 'male',
    seekingGender: 'female',
    job: 'Electrician',
    education: 'Trade School',
  },
  {
    id: '31',
    name: 'Hunter Scott',
    age: 29,
    bio: 'Pilot who loves traveling the world ✈️ Seeking someone adventurous to explore new places together.',
    interests: ['Aviation', 'Travel', 'Adventure', 'Photography'],
    distance: 6,
    wealth: 'wealthy',
    income: 120000,
    personality: 'adventurous',
    gender: 'male',
    seekingGender: 'female',
    job: 'Commercial Pilot',
    education: 'Bachelor\'s Degree',
  },
  // 10 More Female Profiles
  {
    id: '32',
    name: 'Hannah Taylor',
    age: 25,
    bio: 'Marine biologist exploring ocean life 🌊 Love the ocean and looking for someone who shares my passion for marine conservation.',
    interests: ['Marine Biology', 'Scuba Diving', 'Conservation', 'Nature'],
    distance: 5,
    wealth: 'average',
    income: 65000,
    personality: 'curious',
    gender: 'female',
    seekingGender: 'male',
    job: 'Marine Biologist',
    education: 'Master\'s Degree',
  },
  {
    id: '33',
    name: 'Samantha Reed',
    age: 27,
    bio: 'Financial analyst who loves numbers and strategy 📊 Looking for someone who appreciates both logic and fun.',
    interests: ['Finance', 'Investing', 'Strategy Games', 'Travel'],
    distance: 2,
    wealth: 'wealthy',
    income: 98000,
    personality: 'analytical',
    gender: 'female',
    seekingGender: 'male',
    job: 'Financial Analyst',
    education: 'MBA',
  },
  {
    id: '34',
    name: 'Victoria King',
    age: 26,
    bio: 'Fashion stylist with an eye for trends 👗 Love helping people look their best and express themselves.',
    interests: ['Fashion', 'Styling', 'Shopping', 'Photography'],
    distance: 3,
    wealth: 'average',
    income: 54000,
    personality: 'stylish',
    gender: 'female',
    seekingGender: 'male',
    job: 'Fashion Stylist',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '35',
    name: 'Madison Cooper',
    age: 24,
    bio: 'Social worker making a difference in people\'s lives 💙 Looking for someone with a big heart and compassion.',
    interests: ['Social Work', 'Volunteering', 'Community', 'Reading'],
    distance: 4,
    wealth: 'poor',
    income: 42000,
    personality: 'compassionate',
    gender: 'female',
    seekingGender: 'male',
    job: 'Social Worker',
    education: 'Master\'s Degree',
  },
  {
    id: '36',
    name: 'Aubrey Rivera',
    age: 28,
    bio: 'Dental hygienist who values health and wellness 😊 Love helping people smile and feel confident.',
    interests: ['Health', 'Wellness', 'Fitness', 'Cooking'],
    distance: 2,
    wealth: 'average',
    income: 68000,
    personality: 'cheerful',
    gender: 'female',
    seekingGender: 'male',
    job: 'Dental Hygienist',
    education: 'Associate\'s Degree',
  },
  {
    id: '37',
    name: 'Brooklyn Adams',
    age: 23,
    bio: 'Journalist telling important stories 📰 Passionate about truth and looking for someone who values honesty.',
    interests: ['Journalism', 'Writing', 'Current Events', 'Reading'],
    distance: 1,
    wealth: 'average',
    income: 46000,
    personality: 'curious',
    gender: 'female',
    seekingGender: 'male',
    job: 'Journalist',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '38',
    name: 'Skylar Bennett',
    age: 29,
    bio: 'Interior designer creating beautiful living spaces 🏡 Love transforming spaces and making homes feel special.',
    interests: ['Interior Design', 'Home Decor', 'Architecture', 'Art'],
    distance: 3,
    wealth: 'wealthy',
    income: 87000,
    personality: 'creative',
    gender: 'female',
    seekingGender: 'male',
    job: 'Interior Designer',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '39',
    name: 'Piper Collins',
    age: 25,
    bio: 'Veterinary technician who adores animals 🐾 Looking for someone who loves pets as much as I do.',
    interests: ['Animals', 'Veterinary Medicine', 'Nature', 'Hiking'],
    distance: 5,
    wealth: 'average',
    income: 38000,
    personality: 'caring',
    gender: 'female',
    seekingGender: 'male',
    job: 'Veterinary Technician',
    education: 'Associate\'s Degree',
  },
  {
    id: '40',
    name: 'Quinn Parker',
    age: 27,
    bio: 'Software developer building the future 💻 Love coding and looking for someone who shares my tech enthusiasm.',
    interests: ['Coding', 'Technology', 'Gaming', 'Startups'],
    distance: 2,
    wealth: 'wealthy',
    income: 102000,
    personality: 'tech-savvy',
    gender: 'female',
    seekingGender: 'male',
    job: 'Software Developer',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '41',
    name: 'Riley Morgan',
    age: 26,
    bio: 'Dance instructor spreading joy through movement 💃 Love expressing myself through dance and music.',
    interests: ['Dance', 'Music', 'Fitness', 'Performing Arts'],
    distance: 4,
    wealth: 'average',
    income: 45000,
    personality: 'expressive',
    gender: 'female',
    seekingGender: 'male',
    job: 'Dance Instructor',
    education: 'Bachelor\'s Degree',
  },
  // 10 More Male Profiles
  {
    id: '42',
    name: 'Blake Turner',
    age: 28,
    bio: 'Police officer serving and protecting the community 🚔 Looking for someone who values integrity and service.',
    interests: ['Law Enforcement', 'Fitness', 'Community', 'Sports'],
    distance: 3,
    wealth: 'average',
    income: 72000,
    personality: 'dedicated',
    gender: 'male',
    seekingGender: 'female',
    job: 'Police Officer',
    education: 'Associate\'s Degree',
  },
  {
    id: '43',
    name: 'Dylan Roberts',
    age: 25,
    bio: 'Mechanic who loves working on cars and motorcycles 🏍️ Looking for someone who appreciates craftsmanship.',
    interests: ['Cars', 'Motorcycles', 'Mechanics', 'Racing'],
    distance: 2,
    wealth: 'average',
    income: 52000,
    personality: 'handy',
    gender: 'male',
    seekingGender: 'female',
    job: 'Automotive Mechanic',
    education: 'Trade School',
  },
  {
    id: '44',
    name: 'Parker Evans',
    age: 27,
    bio: 'Dentist helping people achieve healthy smiles 😁 Love my work and looking for someone positive and caring.',
    interests: ['Dentistry', 'Health', 'Fitness', 'Travel'],
    distance: 4,
    wealth: 'wealthy',
    income: 145000,
    personality: 'caring',
    gender: 'male',
    seekingGender: 'female',
    job: 'Dentist',
    education: 'Doctorate Degree',
  },
  {
    id: '45',
    name: 'Riley Cooper',
    age: 24,
    bio: 'Elementary school teacher shaping young minds 📚 Passionate about education and looking for someone who values learning.',
    interests: ['Education', 'Reading', 'Volunteering', 'Music'],
    distance: 1,
    wealth: 'average',
    income: 48000,
    personality: 'patient',
    gender: 'male',
    seekingGender: 'female',
    job: 'Elementary Teacher',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '46',
    name: 'Sawyer Mitchell',
    age: 29,
    bio: 'Construction manager building the future 🏗️ Love seeing projects come to life and working with my team.',
    interests: ['Construction', 'Architecture', 'DIY', 'Sports'],
    distance: 5,
    wealth: 'wealthy',
    income: 95000,
    personality: 'leadership',
    gender: 'male',
    seekingGender: 'female',
    job: 'Construction Manager',
    education: 'Bachelor\'s Degree',
  },
  {
    id: '47',
    name: 'Quinn Foster',
    age: 26,
    bio: 'Pharmacist ensuring people get the right medications 💊 Love helping others and looking for someone thoughtful.',
    interests: ['Pharmacy', 'Health', 'Science', 'Reading'],
    distance: 3,
    wealth: 'wealthy',
    income: 125000,
    personality: 'thoughtful',
    gender: 'male',
    seekingGender: 'female',
    job: 'Pharmacist',
    education: 'Doctorate Degree',
  },
  {
    id: '48',
    name: 'River Stone',
    age: 25,
    bio: 'Landscape architect designing beautiful outdoor spaces 🌳 Love nature and creating sustainable environments.',
    interests: ['Landscape Architecture', 'Nature', 'Sustainability', 'Hiking'],
    distance: 2,
    wealth: 'average',
    income: 68000,
    personality: 'environmentalist',
    gender: 'male',
    seekingGender: 'female',
    job: 'Landscape Architect',
    education: 'Master\'s Degree',
  },
  {
    id: '49',
    name: 'Phoenix Wright',
    age: 28,
    bio: 'Paramedic saving lives every day 🚑 Looking for someone who understands the importance of helping others.',
    interests: ['Emergency Medicine', 'Fitness', 'Adventure', 'Community'],
    distance: 4,
    wealth: 'average',
    income: 58000,
    personality: 'heroic',
    gender: 'male',
    seekingGender: 'female',
    job: 'Paramedic',
    education: 'Certification',
  },
  {
    id: '50',
    name: 'Sage Thompson',
    age: 27,
    bio: 'Librarian who loves books and knowledge 📖 Seeking someone who enjoys quiet moments and intellectual conversations.',
    interests: ['Reading', 'Literature', 'History', 'Research'],
    distance: 3,
    wealth: 'average',
    income: 52000,
    personality: 'intellectual',
    gender: 'male',
    seekingGender: 'female',
    job: 'Librarian',
    education: 'Master\'s Degree',
  },
  {
    id: '51',
    name: 'Kai Martinez',
    age: 24,
    bio: 'Bartender mixing drinks and creating experiences 🍹 Love the nightlife and meeting new people.',
    interests: ['Mixology', 'Socializing', 'Music', 'Nightlife'],
    distance: 1,
    wealth: 'poor',
    income: 35000,
    personality: 'social',
    gender: 'male',
    seekingGender: 'female',
    job: 'Bartender',
    education: 'Some College',
  },
];

