export type IdentitySex = 'male' | 'female' | 'random';
export type IdentitySexuality = 'straight' | 'gay' | 'bi';

export interface OnboardingIdentityStateShape {
  firstName: string;
  lastName: string;
  sex: IdentitySex;
  sexuality: IdentitySexuality;
}

interface SexChangeRegenerationArgs {
  sex: IdentitySex;
  firstName: string;
  lastName: string;
  lastAutoGeneratedSex: IdentitySex | null;
}

interface IdentityDraftNameShape {
  firstName: string;
  lastName: string;
}

export const shouldGenerateInitialIdentityName = (firstName: string, lastName: string): boolean => {
  return !firstName && !lastName;
};

export const canContinueFromIdentityDraft = ({ firstName, lastName }: IdentityDraftNameShape): boolean => {
  return firstName.trim().length > 0 && lastName.trim().length > 0;
};

export const shouldRegenerateIdentityNameForSexChange = ({
  sex,
  firstName,
  lastName,
  lastAutoGeneratedSex,
}: SexChangeRegenerationArgs): boolean => {
  const isExplicitSex = sex === 'male' || sex === 'female';
  if (!isExplicitSex) {
    return false;
  }
  // Only regenerate if the current name was auto-generated for a known sex.
  if (!lastAutoGeneratedSex) {
    return false;
  }
  if (!firstName || !lastName) {
    return false;
  }
  return lastAutoGeneratedSex !== sex;
};

export const applyIdentityDraftToOnboardingState = <T extends OnboardingIdentityStateShape>(
  previousState: T,
  identityDraft: OnboardingIdentityStateShape
): T => {
  return {
    ...previousState,
    ...identityDraft,
  };
};
