/**
 * The built ICT-FaceKit head, checked against the binder.
 *
 * The GLB is generated by `scripts/build-ict-head.mjs`, which derives semantic
 * morphs from ICT's 100 Light Stage identity modes. Its morph names are our own
 * `FACE_MORPH_KEYS`, so binding must be exact.
 *
 * Read from the artifact, never from a list kept alongside it — see the note on
 * ICT_HEAD.
 */

import { bindGenomeToRig, genomeToInfluences, randomizeFace, neutralMorphs, FACE_MORPH_KEYS } from '@/lib/identity';
import type { FaceGenome } from '@/lib/identity';
import { readHeadGlb } from './helpers/readHeadGlb';

/**
 * The morph names in the SHIPPED asset, read off disk.
 *
 * Not a hardcoded list. This file used to carry one — 21 names, plus three
 * "underivable" axes — and it went on passing after the rig gained region-based
 * measurements for exactly those three. The suite kept describing an asset that
 * had changed underneath it, which is the failure a test list cannot detect
 * about itself.
 */
const head = readHeadGlb();
const ICT_HEAD = head?.morphNames ?? [];

// A checkout without the build artifact falls back to the procedural head, so
// skipping is the honest outcome rather than a failure.
const withAsset = ICT_HEAD.length > 0 ? describe : describe.skip;

withAsset('ICT-FaceKit head binding', () => {
  const binding = bindGenomeToRig(ICT_HEAD);

  it('binds every morph in the asset, with nothing left over', () => {
    expect(Object.keys(binding.bound).sort()).toEqual([...ICT_HEAD].sort());
    expect(binding.unused).toEqual([]);
  });

  it('drives every slider the creator offers — no dead controls', () => {
    // BACK TO EMPTY, and that is the point of the assertion.
    //
    // It briefly listed seven exceptions. `head_ict.glb` is generated by
    // `scripts/build-ict-head.mjs`, and when the second batch of morphs was
    // appended the asset had not been regenerated — so on the scanned head,
    // which is the one that ships once the GLB loads, those seven sliders were
    // HIDDEN by `binding.unbound` rather than rendered dead. The rig has since
    // been rebuilt with a measured axis for each, so the exception list is gone
    // and this is a plain "everything binds" again.
    //
    // `earSize`, `neckThickness` and `foreheadSlope` were unbound for as long
    // as every morph was a span between two of the 68 landmarks, which has no
    // ear, neck or above-brow points; they are derived from vertex-region
    // measurements instead, as are the four grooves and hollows in the second
    // batch. If one ever falls out of the asset again this fails rather than
    // the UI quietly hiding a control.
    expect([...binding.unbound]).toEqual([]);
    expect(Object.keys(binding.bound).sort()).toEqual([...FACE_MORPH_KEYS].sort());
  });

  it('drives one morph per slider — no left/right pairs to keep in sync', () => {
    for (const names of Object.values(binding.bound)) expect(names).toHaveLength(1);
  });

  it('has no negative half, so the UI must clamp those controls', () => {
    // Each derived axis is a single baked target: full influence is "more",
    // zero is neutral, and the rig cannot express "less". genomeToInfluences
    // reports that rather than silently deadening the lower half.
    const genome = { ...randomizeFace('ict'), morphs: neutralMorphs() } satisfies FaceGenome;
    for (const key of ICT_HEAD) genome.morphs[key as keyof typeof genome.morphs] = 0;
    expect(genomeToInfluences(genome, binding).oneSided.sort()).toEqual([...ICT_HEAD].sort());
  });

  it('maps a railed morph to full influence and neutral to zero', () => {
    const genome = { ...randomizeFace('ict'), morphs: neutralMorphs() } satisfies FaceGenome;
    expect(genomeToInfluences(genome, binding).influences.jawWidth).toBe(0);
    genome.morphs.jawWidth = 1;
    expect(genomeToInfluences(genome, binding).influences.jawWidth).toBeCloseTo(1);
  });
});
