/**
 * The built ICT-FaceKit head, checked against the binder.
 *
 * The GLB is generated by `scripts/build-ict-head.mjs`, which derives semantic
 * morphs from ICT's 100 Light Stage identity modes. Its morph names are our own
 * `FACE_MORPH_KEYS`, so binding must be exact — and the three axes the 68-point
 * landmark set cannot express must come back as `unbound`, so `FaceStudio`
 * hides them instead of shipping controls that move the wrong feature.
 */

import { bindGenomeToRig, genomeToInfluences, randomizeFace, neutralMorphs } from '@/lib/identity';
import type { FaceGenome } from '@/lib/identity';

/** Exactly what `npm run head:list` prints for assets/models/head_ict.glb. */
const ICT_HEAD = [
  'faceWidth', 'faceLength', 'jawWidth', 'jawAngle', 'chinLength', 'chinProtrusion',
  'cheekboneHeight', 'cheekFullness', 'browHeight', 'browProtrusion',
  'eyeSize', 'eyeSpacing', 'eyeDepth', 'eyeTilt',
  'noseLength', 'noseWidth', 'noseBridge', 'noseTip',
  'mouthWidth', 'lipFullness', 'mouthHeight',
];

/** The three the landmark set has no points for. */
const UNDERIVABLE = ['earSize', 'foreheadSlope', 'neckThickness'];

describe('ICT-FaceKit head binding', () => {
  const binding = bindGenomeToRig(ICT_HEAD);

  it('binds all 21 derived morphs exactly, with nothing left over', () => {
    expect(Object.keys(binding.bound).sort()).toEqual([...ICT_HEAD].sort());
    expect(binding.unused).toEqual([]);
  });

  it('reports exactly the three underivable axes as dead sliders', () => {
    // Not a shortfall being hidden — these are reported precisely so the UI can
    // drop them. A slider derived from stand-in landmarks would move something
    // plausible in the wrong place, which reads as a modelling bug.
    expect([...binding.unbound].sort()).toEqual([...UNDERIVABLE].sort());
  });

  it('drives one morph per slider — no left/right pairs to keep in sync', () => {
    for (const names of Object.values(binding.bound)) expect(names).toHaveLength(1);
  });

  it('has no negative half, so the UI must clamp those controls', () => {
    // Each derived axis is a single baked target: full influence is "more",
    // zero is neutral, and the rig cannot express "less". genomeToInfluences
    // reports that rather than silently deadening the lower half.
    const genome = { ...randomizeFace('ict'), morphs: neutralMorphs() } satisfies FaceGenome;
    for (const key of ICT_HEAD) genome.morphs[key as keyof typeof genome.morphs] = 0;
    expect(genomeToInfluences(genome, binding).oneSided.sort()).toEqual([...ICT_HEAD].sort());
  });

  it('maps a railed morph to full influence and neutral to zero', () => {
    const genome = { ...randomizeFace('ict'), morphs: neutralMorphs() } satisfies FaceGenome;
    expect(genomeToInfluences(genome, binding).influences.jawWidth).toBe(0);
    genome.morphs.jawWidth = 1;
    expect(genomeToInfluences(genome, binding).influences.jawWidth).toBeCloseTo(1);
  });
});
