import {
  applyIdentityDraftToOnboardingState,
  canContinueFromIdentityDraft,
  shouldGenerateInitialIdentityName,
  shouldRegenerateIdentityNameForSexChange,
} from '@/src/features/onboarding/customizeIdentity';

describe('Customize identity logic', () => {
  describe('shouldGenerateInitialIdentityName', () => {
    it('returns true when both names are empty', () => {
      expect(shouldGenerateInitialIdentityName('', '')).toBe(true);
    });

    it('returns false when first name exists', () => {
      expect(shouldGenerateInitialIdentityName('Alex', '')).toBe(false);
    });

    it('returns false when last name exists', () => {
      expect(shouldGenerateInitialIdentityName('', 'River')).toBe(false);
    });
  });

  describe('canContinueFromIdentityDraft', () => {
    it('returns true when both names are non-empty after trimming', () => {
      expect(canContinueFromIdentityDraft({ firstName: ' Alex ', lastName: ' Rivera ' })).toBe(true);
    });

    it('returns false when either name is empty or whitespace', () => {
      expect(canContinueFromIdentityDraft({ firstName: '', lastName: 'Rivera' })).toBe(false);
      expect(canContinueFromIdentityDraft({ firstName: 'Alex', lastName: '   ' })).toBe(false);
    });
  });

  describe('shouldRegenerateIdentityNameForSexChange', () => {
    it('returns true for explicit sex change with existing names', () => {
      expect(
        shouldRegenerateIdentityNameForSexChange({
          sex: 'female',
          firstName: 'John',
          lastName: 'Doe',
          lastAutoGeneratedSex: 'male',
        })
      ).toBe(true);
    });

    it('returns false when sex is random', () => {
      expect(
        shouldRegenerateIdentityNameForSexChange({
          sex: 'random',
          firstName: 'Taylor',
          lastName: 'Sky',
          lastAutoGeneratedSex: 'male',
        })
      ).toBe(false);
    });

    it('returns false when both names are empty', () => {
      expect(
        shouldRegenerateIdentityNameForSexChange({
          sex: 'male',
          firstName: '',
          lastName: '',
          lastAutoGeneratedSex: 'female',
        })
      ).toBe(false);
    });

    it('returns false when no auto-generated sex is tracked', () => {
      expect(
        shouldRegenerateIdentityNameForSexChange({
          sex: 'male',
          firstName: 'Sam',
          lastName: 'Fields',
          lastAutoGeneratedSex: null,
        })
      ).toBe(false);
    });

    it('returns false when only one name field has content', () => {
      expect(
        shouldRegenerateIdentityNameForSexChange({
          sex: 'female',
          firstName: 'Jamie',
          lastName: '',
          lastAutoGeneratedSex: 'male',
        })
      ).toBe(false);
    });

    it('returns false when same explicit sex was already auto-generated', () => {
      expect(
        shouldRegenerateIdentityNameForSexChange({
          sex: 'male',
          firstName: 'Mike',
          lastName: 'Stone',
          lastAutoGeneratedSex: 'male',
        })
      ).toBe(false);
    });
  });

  describe('applyIdentityDraftToOnboardingState', () => {
    it('applies identity fields while preserving unrelated onboarding state', () => {
      const previousState = {
        slot: 2,
        scenario: { id: 'corporate_intern', title: 'Corporate Intern' },
        challengeScenarioId: 'rags_to_riches',
        firstName: 'Old',
        lastName: 'Name',
        sex: 'male' as const,
        sexuality: 'straight' as const,
        perks: ['legacy_builder'],
      };

      const nextState = applyIdentityDraftToOnboardingState(previousState, {
        firstName: 'New',
        lastName: 'Person',
        sex: 'female',
        sexuality: 'bi',
      });

      expect(nextState.firstName).toBe('New');
      expect(nextState.lastName).toBe('Person');
      expect(nextState.sex).toBe('female');
      expect(nextState.sexuality).toBe('bi');
      expect(nextState.slot).toBe(2);
      expect(nextState.scenario).toEqual(previousState.scenario);
      expect(nextState.challengeScenarioId).toBe('rags_to_riches');
      expect(nextState.perks).toEqual(['legacy_builder']);
    });
  });
});
